### ISSUE TITLE
val sometimes fails to be parsed correctly

### ISSUE THREAD

**Issue by twilek** [mplushnikov/lombok-intellij-plugin#105]
I pretty frequently gets red underlines in our code with "Incopatible types"-errors when I'm using val. This happens very often when we use IntelliJ:s refactoring tools (for example extract variable). It seems like the plugin mix up the variables in the methods bacuse the "Incopatible types"-errors says it expects another type used in the same method, here is an example:

    @Test
    public void isLegacy_mapObjectWithDTO_returnFalse() throws Exception {
        val entity = new AccountUserEntity(); // <-- this row gives an "Incopatible types" asking for a User

        val dto = mapper.map(entity, User.class); // <-- while this row gives an "Incopatible types" asking for a AccountUserEntity

        assertThat(dto.isLegacyUser(), is(false));
    }

I also sometimes gets the error "Unknown class: java.lang.Object" when I hover over it. The errors often goes away if I cut out the whole file (Ctrl-A Ctrl-X) and then paste it back (Ctrl-V) and trigger a reparse of the whole document.

I have looked in the IntelliJ log and see lot of errors like this when this is happening (don't know if they are related though):

    2015-04-27 12:03:15,353 [1284960]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 14.1.2  Build #IU-141.713.2 
    2015-04-27 12:03:15,353 [1284960]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_31 
    2015-04-27 12:03:15,353 [1284960]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
    2015-04-27 12:03:15,353 [1284960]  ERROR - aemon.impl.PassExecutorService - Vendor: Oracle Corporation 
    2015-04-27 12:03:15,353 [1284960]  ERROR - aemon.impl.PassExecutorService - OS: Linux 
    2015-04-27 12:03:15,353 [1284960]  ERROR - aemon.impl.PassExecutorService - Last Action: IntroduceVariable 
    2015-04-27 12:03:15,353 [1284960]  ERROR - aemon.impl.PassExecutorService - Element: class com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl because: containing file is null
    invalidated at: see attachment 
    com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl because: containing file is null
    invalidated at: see attachment
        at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:479)
        at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:140)
        at com.intellij.psi.impl.source.PsiClassReferenceType.resolve(PsiClassReferenceType.java:89)
        at com.intellij.psi.util.PsiUtil.ensureValidType(PsiUtil.java:1089)
        at com.intellij.psi.util.PsiUtil.ensureValidType(PsiUtil.java:1078)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$TypeEvaluator.fun(PsiReferenceExpressionImpl.java:405)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$TypeEvaluator.fun(PsiReferenceExpressionImpl.java:351)
        at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:90)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.getType(PsiReferenceExpressionImpl.java:418)
        at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.a(PsiOldInferenceHelper.java:61)
        at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferTypeArguments(PsiOldInferenceHelper.java:214)
        at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.inferTypeArguments(PsiResolveHelperImpl.java:189)
        at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:307)
        at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:265)
        at com.intellij.psi.infos.MethodCandidateInfo.getSubstitutor(MethodCandidateInfo.java:202)
        at com.intellij.psi.scope.conflictResolvers.JavaMethodsConflictResolver$2.create(JavaMethodsConflictResolver.java:103)
        at com.intellij.psi.scope.conflictResolvers.JavaMethodsConflictResolver$2.create(JavaMethodsConflictResolver.java:99)
        at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:56)
        at com.intellij.psi.scope.conflictResolvers.JavaMethodsConflictResolver.a(JavaMethodsConflictResolver.java:347)
        at com.intellij.psi.scope.conflictResolvers.JavaMethodsConflictResolver.checkSameSignatures(JavaMethodsConflictResolver.java:232)
        at com.intellij.psi.scope.conflictResolvers.JavaMethodsConflictResolver.guardedOverloadResolution(JavaMethodsConflictResolver.java:106)
        at com.intellij.psi.scope.conflictResolvers.JavaMethodsConflictResolver$1.compute(JavaMethodsConflictResolver.java:86)
        at com.intellij.psi.scope.conflictResolvers.JavaMethodsConflictResolver$1.compute(JavaMethodsConflictResolver.java:83)
        at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
        at com.intellij.psi.scope.conflictResolvers.JavaMethodsConflictResolver.resolveConflict(JavaMethodsConflictResolver.java:83)
        at com.intellij.psi.scope.processor.ConflictFilterProcessor.getResult(ConflictFilterProcessor.java:90)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.a(PsiReferenceExpressionImpl.java:291)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.a(PsiReferenceExpressionImpl.java:271)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:59)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:194)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:183)
        at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
        at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
        at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
        at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
        at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:767)
        at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:757)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:332)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionBase.advancedResolve(PsiReferenceExpressionBase.java:86)
        at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.resolveMethodGenerics(PsiMethodCallExpressionImpl.java:63)
        at com.intellij.codeInsight.ExceptionUtil.getUnhandledExceptions(ExceptionUtil.java:412)
        at com.intellij.codeInsight.ExceptionUtil.a(ExceptionUtil.java:252)
        at com.intellij.codeInsight.ExceptionUtil.collectUnhandledExceptions(ExceptionUtil.java:240)
        at com.intellij.codeInsight.ExceptionUtil.collectUnhandledExceptions(ExceptionUtil.java:233)
        at com.intellij.psi.controlFlow.ControlFlowAnalyzer.d(ControlFlowAnalyzer.java:282)
        at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitMethodCallExpression(ControlFlowAnalyzer.java:1475)
        at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:139)
        at com.intellij.psi.controlFlow.ControlFlowAnalyzer.a(ControlFlowAnalyzer.java:502)
        at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitDeclarationStatement(ControlFlowAnalyzer.java:487)
        at com.intellij.psi.impl.source.tree.java.PsiDeclarationStatementImpl.accept(PsiDeclarationStatementImpl.java:89)
        at com.intellij.psi.controlFlow.ControlFlowAnalyzer.visitCodeBlock(ControlFlowAnalyzer.java:371)
        at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:202)
        at com.intellij.psi.controlFlow.ControlFlowAnalyzer.buildControlFlow(ControlFlowAnalyzer.java:112)
        at com.intellij.psi.controlFlow.ControlFlowFactory.getControlFlow(ControlFlowFactory.java:142)
        at com.intellij.psi.controlFlow.ControlFlowFactory.getControlFlow(ControlFlowFactory.java:124)
        at com.intellij.codeInspection.varScopeCanBeNarrowed.FieldCanBeLocalInspectionBase.a(FieldCanBeLocalInspectionBase.java:192)
        at com.intellij.codeInspection.varScopeCanBeNarrowed.FieldCanBeLocalInspectionBase.access$000(FieldCanBeLocalInspectionBase.java:47)
        at com.intellij.codeInspection.varScopeCanBeNarrowed.FieldCanBeLocalInspectionBase$4.visitMethod(FieldCanBeLocalInspectionBase.java:163)
        at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:291)
        at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:64)
        at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:26)
        at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
        at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
        at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:73)
        at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitElement(JavaRecursiveElementWalkingVisitor.java:34)
        at com.intellij.codeInspection.varScopeCanBeNarrowed.FieldCanBeLocalInspectionBase$4.visitElement(FieldCanBeLocalInspectionBase.java:154)
        at com.intellij.psi.JavaElementVisitor.visitClass(JavaElementVisitor.java:56)
        at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:470)
        at com.intellij.codeInspection.varScopeCanBeNarrowed.FieldCanBeLocalInspectionBase.a(FieldCanBeLocalInspectionBase.java:151)
        at com.intellij.codeInspection.varScopeCanBeNarrowed.FieldCanBeLocalInspectionBase.a(FieldCanBeLocalInspectionBase.java:73)
        at com.intellij.codeInspection.varScopeCanBeNarrowed.FieldCanBeLocalInspectionBase.access$100(FieldCanBeLocalInspectionBase.java:47)
        at com.intellij.codeInspection.varScopeCanBeNarrowed.FieldCanBeLocalInspectionBase$5.visitJavaFile(FieldCanBeLocalInspectionBase.java:291)
        at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:424)
        at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:309)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:304)
        at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
        at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
        at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
        at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
        at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
        at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
        at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
        at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
        at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
        at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
        at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
        at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
    2015-04-27 12:03:15,364 [1284971]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 14.1.2  Build #IU-141.713.2 
    2015-04-27 12:03:15,365 [1284972]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_31 
    2015-04-27 12:03:15,365 [1284972]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
    2015-04-27 12:03:15,365 [1284972]  ERROR - aemon.impl.PassExecutorService - Vendor: Oracle Corporation 
    2015-04-27 12:03:15,365 [1284972]  ERROR - aemon.impl.PassExecutorService - OS: Linux 
    2015-04-27 12:03:15,365 [1284972]  ERROR - aemon.impl.PassExecutorService - Last Action: IntroduceVariable 
    2015-04-27 12:03:16,947 [1286554]  ERROR - ava.PsiReferenceExpressionImpl - invalid type of PsiLocalVariable:entity of class class com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl, valid=true 
    java.lang.Throwable
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$TypeEvaluator.fun(PsiReferenceExpressionImpl.java:380)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$TypeEvaluator.fun(PsiReferenceExpressionImpl.java:351)
        at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:90)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.getType(PsiReferenceExpressionImpl.java:418)
        at com.intellij.psi.scope.util.PsiScopesUtil.setupAndRunProcessor(PsiScopesUtil.java:314)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.a(PsiReferenceExpressionImpl.java:286)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.a(PsiReferenceExpressionImpl.java:271)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:59)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:194)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:183)
        at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
        at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
        at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
        at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
        at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:767)
        at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:757)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:332)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionBase.advancedResolve(PsiReferenceExpressionBase.java:86)
        at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionBase.resolve(PsiReferenceExpressionBase.java:48)
        at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.resolveMethod(PsiMethodCallExpressionImpl.java:57)
        at com.intellij.codeInspection.testOnly.TestOnlyInspection.a(TestOnlyInspection.java:61)
        at com.intellij.codeInspection.testOnly.TestOnlyInspection.access$000(TestOnlyInspection.java:31)
        at com.intellij.codeInspection.testOnly.TestOnlyInspection$1.visitCallExpression(TestOnlyInspection.java:55)
        at com.intellij.psi.JavaElementVisitor.visitMethodCallExpression(JavaElementVisitor.java:184)
        at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:139)
        at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
        at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:285)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:75)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:254)
        at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:251)
        at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
        at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
        at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
        at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
        at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
        at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
        at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
        at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
        at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
        at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
        at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
        at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

I am using Lombok Plugin 0.9.3.14 with IDEA 14.1.2

Here is a case how I can reproduce this every time I try.
Add the following code to a test class:

    import lombok.Data;
    import lombok.val;
    import org.junit.Test;
    import org.modelmapper.ModelMapper;

    import static org.hamcrest.MatcherAssert.assertThat;
    import static org.hamcrest.Matchers.is;

    public class MyTest {

        private final ModelMapper mapper = new ModelMapper();

        @Test
        public void testLombokPlugin() throws Exception {
            val entity = new MyEntityClass();

            val dto = mapper.map(entity, MyDtoClass.class);

            assertThat(dto.isValue(), is(true));
        }

        @Data
        private class MyEntityClass {
            boolean value = true;
        }

        @Data
        private class MyDtoClass {
            boolean value;
        }
    }
    
Then use IntelliJ:s Extract Variable on true in the row assertThat(dto.isValue(), is(true));
The method shall then look like this:

    @Test
    public void testLombokPlugin() throws Exception {
        val entity = new MyEntityClass();

        val dto = mapper.map(entity, MyDtoClass.class);

        boolean value = true;
        assertThat(dto.isValue(), is(value));
    }

Then do UNDO. When doing this the first row (val entity = new MyEntityClass();) turns red with an error telling "Incompatible types. Required MyDtoClass. Found MyEntityClass."
    
I'm using ModelMapper (http://modelmapper.org/) and Hamcrest (https://code.google.com/p/hamcrest/) in this code.

**Comment by twilek** [comment]
Here is a case how I can reproduce this every time I try.
Add the following code to a test class:

    import lombok.Data;
    import lombok.val;
    import org.junit.Test;
    import org.modelmapper.ModelMapper;

    import static org.hamcrest.MatcherAssert.assertThat;
    import static org.hamcrest.Matchers.is;

    public class MyTest {

        private final ModelMapper mapper = new ModelMapper();

        @Test
        public void testLombokPlugin() throws Exception {
            val entity = new MyEntityClass();

            val dto = mapper.map(entity, MyDtoClass.class);

            assertThat(dto.isValue(), is(true));
        }

        @Data
        private class MyEntityClass {
            boolean value = true;
        }

        @Data
        private class MyDtoClass {
            boolean value;
        }
    }
    
Then use IntelliJ:s Extract Variable on true in the row assertThat(dto.isValue(), is(true));
The method shall then look like this:

    @Test
    public void testLombokPlugin() throws Exception {
        val entity = new MyEntityClass();

        val dto = mapper.map(entity, MyDtoClass.class);

        boolean value = true;
        assertThat(dto.isValue(), is(value));
    }

Then do UNDO. When doing this the first row (val entity = new MyEntityClass();) turns red with an error telling "Incompatible types. Required MyDtoClass. Found MyEntityClass."
    
I'm using ModelMapper (http://modelmapper.org/) and Hamcrest (https://code.google.com/p/hamcrest/) in this code.

**Comment by bramklg** [comment]
We have the same issue, they seem to occur randomly in classes using the val keyword. Replacing val with object, save, and then replace object with val again solves the issue.

**Comment by alabax** [comment]
I have issues when I declare two vals one after another, second val does not get resolved and when hoevered says "Unknown class: 'java.lang.Object'".

**Comment by alabax** [comment]
Ok, now I see 1 case why it happens for me. I declare `val foo = someObj.someMethod()` and there is no import for the returned type of that method. Idea cannot suggest a balloon to import thingy because in its view no new unseen type was defined (`val` is already there).

**Comment by mogren** [comment]
Same here, annoying bug for sure. Some devs switched to Eclipse because of this issue.

**Comment by mplushnikov** [comment]
It looks similar to https://github.com/mplushnikov/lombok-intellij-plugin/issues/142
Maybe both have same cause.
I also create issue for Jetbrains: https://youtrack.jetbrains.com/issue/IDEA-147214
Maybe we get some help:)

**Comment by AlexejK** [comment]
To me it sounds more like a #168 issue rather than #142 ?

**Comment by mplushnikov** [comment]
New version 0.10 of the plugin was released today and contains fixes and improvements for this issue.
