### ISSUE TITLE
Stackoverflow. (rename field and accessors)

### ISSUE THREAD

**Issue by Lekanich** [mplushnikov/lombok-intellij-plugin#112]
Idea throwed this exception when I renamed field with @Getter annotation and pressed button "rename accessors". 
Maybe it's Idea bug?

I attached piece of log.
```code
null
java.lang.StackOverflowError
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getParentByStub(StubBasedPsiElementBase.java:259)
	at com.intellij.psi.impl.source.JavaStubPsiElement.getParent(JavaStubPsiElement.java:63)
	at com.intellij.psi.impl.PsiElementBase.getContainingFile(PsiElementBase.java:235)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:197)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getProject(StubBasedPsiElementBase.java:234)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:62)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:37)
	at com.intellij.psi.impl.source.PsiModifierListImpl.getAnnotations(PsiModifierListImpl.java:254)
	at com.intellij.psi.impl.PsiImplUtil.findAnnotation(PsiImplUtil.java:311)
	at com.intellij.psi.impl.source.PsiModifierListImpl.findAnnotation(PsiModifierListImpl.java:275)
	at com.intellij.codeInsight.AnnotationUtil.isAnnotated(AnnotationUtil.java:317)
	at com.intellij.codeInsight.AnnotationUtil.isAnnotated(AnnotationUtil.java:308)
	at com.intellij.codeInsight.AnnotationUtil.isAnnotated(AnnotationUtil.java:297)
	at com.intellij.codeInsight.NullableNotNullManager.findNullabilityAnnotation(NullableNotNullManager.java:199)
	at com.intellij.codeInsight.NullableNotNullManager.isNotNull(NullableNotNullManager.java:222)
	at com.intellij.codeInsight.NullableNotNullManager.isNotNull(NullableNotNullManager.java:351)
	at com.intellij.codeInsight.NullableNotNullManager.isNullable(NullableNotNullManager.java:347)
	at com.intellij.codeInspection.dataFlow.DfaPsiUtil.getElementNullability(DfaPsiUtil.java:72)
	at com.intellij.codeInspection.dataFlow.value.DfaVariableValue.a(DfaVariableValue.java:169)
	at com.intellij.codeInspection.dataFlow.value.DfaVariableValue.getInherentNullability(DfaVariableValue.java:164)
	at com.intellij.codeInspection.dataFlow.StandardInstructionVisitor.visitAssign(StandardInstructionVisitor.java:76)
	at com.intellij.codeInspection.dataFlow.instructions.AssignInstruction.accept(AssignInstruction.java:46)
	at com.intellij.codeInspection.dataFlow.DataFlowRunner.acceptInstruction(DataFlowRunner.java:232)
	at com.intellij.codeInspection.dataFlow.DfaPsiUtil$1$1.acceptInstruction(DfaPsiUtil.java:173)
	at com.intellij.codeInspection.dataFlow.DataFlowRunner.analyzeMethod(DataFlowRunner.java:186)
	at com.intellij.codeInspection.dataFlow.DataFlowRunner.analyzeMethod(DataFlowRunner.java:103)
	at com.intellij.codeInspection.dataFlow.DfaPsiUtil$1.compute(DfaPsiUtil.java:176)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:125)
	at com.intellij.codeInspection.dataFlow.DfaPsiUtil.a(DfaPsiUtil.java:118)
	at com.intellij.codeInspection.dataFlow.DfaPsiUtil.isInitializedNotNull(DfaPsiUtil.java:108)
	at com.intellij.codeInspection.dataFlow.value.DfaVariableValue.a(DfaVariableValue.java:212)
	at com.intellij.codeInspection.dataFlow.value.DfaVariableValue.getInherentNullability(DfaVariableValue.java:164)
	at com.intellij.codeInspection.dataFlow.DfaVariableState.<init>(DfaVariableState.java:50)
	at com.intellij.codeInspection.dataFlow.DfaMemoryStateImpl.createVariableState(DfaMemoryStateImpl.java:853)
	at com.intellij.codeInspection.dataFlow.DfaMemoryStateImpl.getVariableState(DfaMemoryStateImpl.java:831)
	at com.intellij.codeInspection.dataFlow.DfaMemoryStateImpl.isNotNull(DfaMemoryStateImpl.java:488)
	at com.intellij.codeInspection.dataFlow.DfaPsiUtil$1$1.acceptInstruction(DfaPsiUtil.java:164)
	at com.intellij.codeInspection.dataFlow.DataFlowRunner.analyzeMethod(DataFlowRunner.java:186)
	at com.intellij.codeInspection.dataFlow.DataFlowRunner.analyzeMethod(DataFlowRunner.java:103)
	at com.intellij.codeInspection.dataFlow.DfaPsiUtil$1.compute(DfaPsiUtil.java:176)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
```

**Comment by mplushnikov** [comment]
New pluginversion with some changes for this issue was released today. Please verify and open new issue if the problem still exists...
