### ISSUE TITLE
JDK18+IDEA2021.2.4+because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x6bbab114 #8

### ISSUE THREAD

**Issue by CandyKIng1991** [mplushnikov/lombok-intellij-plugin#1138]
class lombok.javac.apt.LombokProcessor (in unnamed module @0x6bbab114) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x6bbab114

JDK18

2022-06-15 10:20:53,847 [ 38459] ERROR - nSystem.impl.ActionManagerImpl - IntelliJ IDEA 2021.2.4 Build #IU-212.5712.43
2022-06-15 10:20:53,850 [ 38462] ERROR - nSystem.impl.ActionManagerImpl - JDK: 11.0.13; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-06-15 10:20:53,854 [ 38466] ERROR - nSystem.impl.ActionManagerImpl - OS: Windows 10
2022-06-15 10:20:53,857 [ 38469] ERROR - nSystem.impl.ActionManagerImpl - ID "defaultLombokData" is already taken by action "Default @DaTa (Action to replace getter/setter/equals/hashcode/toString methods with lombok @DaTa annotation)" (Plugin: Hrisey Plugin). Action "Default @DaTa (Action to replace getter/setter/equals/hashcode/toString methods with lombok @DaTa annotation)" (Plugin: Lombok) cannot use the same ID [Plugin: Lombook Plugin]
com.intellij.diagnostic.PluginException: ID "defaultLombokData" is already taken by action "Default @DaTa (Action to replace getter/setter/equals/hashcode/toString methods with lombok @DaTa annotation)" (Plugin: Hrisey Plugin). Action "Default @DaTa (Action to replace getter/setter/equals/hashcode/toString methods with lombok @DaTa annotation)" (Plugin: Lombok) cannot use the same ID [Plugin: Lombook Plugin]
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:354)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:349)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionIdCollision(ActionManagerImpl.java:1296)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1239)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerOrReplaceActionInner(ActionManagerImpl.java:714)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionElement(ActionManagerImpl.java:684)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processGroupElement(ActionManagerImpl.java:842)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:483)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$registerActions$3(ActionManagerImpl.java:170)
at com.intellij.serviceContainer.PrecomputedExtensionModelKt.executeRegisterTask(PrecomputedExtensionModel.kt:55)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerActions(ActionManagerImpl.java:169)
at com.intellij.ide.plugins.DynamicPluginsKt.loadPluginDescriptor(DynamicPlugins.kt:1036)
at com.intellij.ide.plugins.DynamicPluginsKt.access$loadPluginDescriptor(DynamicPlugins.kt:1)
at com.intellij.ide.plugins.DynamicPlugins$loadPlugin$1.run(DynamicPlugins.kt:814)
at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:810)
at com.intellij.ide.plugins.DynamicPlugins.access$loadPlugin(DynamicPlugins.kt:100)
at com.intellij.ide.plugins.DynamicPlugins$loadPlugins$1.invoke(DynamicPlugins.kt:121)
at com.intellij.ide.plugins.DynamicPlugins$loadPlugins$1.invoke(DynamicPlugins.kt:100)
at com.intellij.ide.plugins.DynamicPlugins.updateDescriptorsWithoutRestart(DynamicPlugins.kt:165)
at com.intellij.ide.plugins.DynamicPlugins.loadPlugins(DynamicPlugins.kt:120)
at com.intellij.ide.plugins.ProjectPluginTrackerManager$updatePluginsState$3.invoke(ProjectPluginTrackerManager.kt:154)
at com.intellij.ide.plugins.ProjectPluginTrackerManager.updatePluginsState(ProjectPluginTrackerManager.kt:173)
at com.intellij.ide.plugins.ProjectPluginTrackerManager.updatePluginsState$default(ProjectPluginTrackerManager.kt:144)
at com.intellij.ide.plugins.ProjectPluginTrackerManager.updatePluginsState(ProjectPluginTrackerManager.kt)
at com.intellij.ide.ui.PluginBooleanOptionDescriptor.togglePluginState(PluginBooleanOptionDescriptor.java:59)
at com.intellij.openapi.updateSettings.impl.pluginsAdvertisement.PluginAdvertiserService$run$$inlined$invokeLater$1$lambda$1.run(PluginAdvertiserService.kt:122)
at com.intellij.notification.NotificationAction.lambda$createSimpleExpiring$2(NotificationAction.java:61)
at com.intellij.notification.NotificationAction$Simple.actionPerformed(NotificationAction.java:95)
at com.intellij.notification.NotificationAction.actionPerformed(NotificationAction.java:32)
at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:240)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:240)
at com.intellij.notification.Notification.fire(Notification.java:194)
at com.intellij.notification.impl.NotificationsManagerImpl.lambda$createActionPanel$9(NotificationsManagerImpl.java:733)
at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:177)
at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:389)
at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:363)
at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
at java.desktop/java.awt.Component.processEvent(Component.java:6417)
at java.desktop/java.awt.Container.processEvent(Container.java:2263)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:814)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:751)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2022-06-15 10:20:53,859 [ 38471] ERROR - nSystem.impl.ActionManagerImpl - IntelliJ IDEA 2021.2.4 Build #IU-212.5712.43
2022-06-15 10:20:53,863 [ 38475] ERROR - nSystem.impl.ActionManagerImpl - JDK: 11.0.13; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-06-15 10:20:53,867 [ 38479] ERROR - nSystem.impl.ActionManagerImpl - OS: Windows 10
2022-06-15 10:20:53,868 [ 38480] ERROR - nSystem.impl.ActionManagerImpl - ID "defaultLombokGetter" is already taken by action "Default @getter (Action to replace all getter methods with lombok @getter annotation)" (Plugin: Hrisey Plugin). Action "Default @getter (Action to replace all getter methods with lombok @getter annotation)" (Plugin: Lombok) cannot use the same ID [Plugin: Lombook Plugin]
com.intellij.diagnostic.PluginException: ID "defaultLombokGetter" is already taken by action "Default @getter (Action to replace all getter methods with lombok @getter annotation)" (Plugin: Hrisey Plugin). Action "Default @getter (Action to replace all getter methods with lombok @getter annotation)" (Plugin: Lombok) cannot use the same ID [Plugin: Lombook Plugin]
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:354)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:349)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionIdCollision(ActionManagerImpl.java:1296)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1239)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerOrReplaceActionInner(ActionManagerImpl.java:714)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionElement(ActionManagerImpl.java:684)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processGroupElement(ActionManagerImpl.java:842)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:483)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$registerActions$3(ActionManagerImpl.java:170)
at com.intellij.serviceContainer.PrecomputedExtensionModelKt.executeRegisterTask(PrecomputedExtensionModel.kt:55)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerActions(ActionManagerImpl.java:169)
at com.intellij.ide.plugins.DynamicPluginsKt.loadPluginDescriptor(DynamicPlugins.kt:1036)
at com.intellij.ide.plugins.DynamicPluginsKt.access$loadPluginDescriptor(DynamicPlugins.kt:1)
at com.intellij.ide.plugins.DynamicPlugins$loadPlugin$1.run(DynamicPlugins.kt:814)
at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:810)
at com.intellij.ide.plugins.DynamicPlugins.access$loadPlugin(DynamicPlugins.kt:100)
at com.intellij.ide.plugins.DynamicPlugins$loadPlugins$1.invoke(DynamicPlugins.kt:121)
at com.intellij.ide.plugins.DynamicPlugins$loadPlugins$1.invoke(DynamicPlugins.kt:100)
at com.intellij.ide.plugins.DynamicPlugins.updateDescriptorsWithoutRestart(DynamicPlugins.kt:165)
at com.intellij.ide.plugins.DynamicPlugins.loadPlugins(DynamicPlugins.kt:120)
at com.intellij.ide.plugins.ProjectPluginTrackerManager$updatePluginsState$3.invoke(ProjectPluginTrackerManager.kt:154)
at com.intellij.ide.plugins.ProjectPluginTrackerManager.updatePluginsState(ProjectPluginTrackerManager.kt:173)
at com.intellij.ide.plugins.ProjectPluginTrackerManager.updatePluginsState$default(ProjectPluginTrackerManager.kt:144)
at com.intellij.ide.plugins.ProjectPluginTrackerManager.updatePluginsState(ProjectPluginTrackerManager.kt)
at com.intellij.ide.ui.PluginBooleanOptionDescriptor.togglePluginState(PluginBooleanOptionDescriptor.java:59)
at com.intellij.openapi.updateSettings.impl.pluginsAdvertisement.PluginAdvertiserService$run$$inlined$invokeLater$1$lambda$1.run(PluginAdvertiserService.kt:122)
at com.intellij.notification.NotificationAction.lambda$createSimpleExpiring$2(NotificationAction.java:61)
at com.intellij.notification.NotificationAction$Simple.actionPerformed(NotificationAction.java:95)
at com.intellij.notification.NotificationAction.actionPerformed(NotificationAction.java:32)
at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:240)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:240)
at com.intellij.notification.Notification.fire(Notification.java:194)
at com.intellij.notification.impl.NotificationsManagerImpl.lambda$createActionPanel$9(NotificationsManagerImpl.java:733)
at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:177)
at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:389)
at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:363)
at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
at java.desktop/java.awt.Component.processEvent(Component.java:6417)
at java.desktop/java.awt.Container.processEvent(Container.java:2263)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:814)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:751)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by vickyhrithik** [comment]
change your jdk version,because some library not converted

**Comment by cathyHuyenTran** [comment]
Which JDK version should I change? I changed JDK 1, 18, 19 and got the same issue.

**Comment by prachi-datey-sp** [comment]
same here :(

**Comment by enciyo** [comment]
Enter your terminal  ``` rm -rf $HOME/.gradle/ ``` and try again. It resolved my issue

**Comment by cathyHuyenTran** [comment]
> Enter your terminal `rm -rf $HOME/.gradle/` and try again. It resolved my issue

Thank you.

**Comment by Idreesmakman** [comment]
> Which JDK version should I change? I changed JDK 1, 18, 19 and got the same issue.

same issue how to solve it?

**Comment by oaherrera** [comment]
the same ide IntelliJ, changed me to gradle version 7.2 and it was fixed. I have JDK 17

**Comment by azizimusa** [comment]
happen to me too. Finally change my JDK to Zulu because it provide support to Apple Chip M1/M2. https://www.azul.com/downloads/?package=jdk#zulu

**Comment by Mahendra-gowdru-k** [comment]
> Enter your terminal `rm -rf $HOME/.gradle/` and try again. It resolved my issue

This solved my issue, thank you :)

**Comment by mengleizu** [comment]
you can update lombok
`<dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.24</version>
            </dependency>`

**Comment by asifali9145** [comment]
> Enter your terminal `rm -rf $HOME/.gradle/` and try again. It resolved my issue
I tried this solution but not working this time.
