### ISSUE TITLE
"Invalid stub element type in index:" exception

### ISSUE THREAD

**Issue by fedotxxl** [mplushnikov/lombok-intellij-plugin#118]
IDEA 14.1.1
Plugin 0.9.4.14

````
Invalid stub element type in index:
file: file:///home/fbelov/job/projects-active/stackcare/aggregator/src/main/java/com/stackcare/agg/miner/FileDownloadScheduler.java
psiElement: PsiAnnotationParameterList
requiredClass: interface com.intellij.psi.PsiClass
actualClass: class com.intellij.psi.impl.source.tree.java.PsiAnnotationParamListImpl
virtualFile: size:3022; stamp:482259; modCount:1435181826999; fileType:JAVA; language:JAVA
document: size:3022; stamp:482259; committed:true; saved:true
psiFile: size:3022; stamp:482259; class:com.intellij.psi.impl.source.PsiJavaFileImpl; language:JAVA
fileAST: size:3022; parsed:true
indexing info: indexed at 1435181757127 with size 3022
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.psi.stubs.StubIndexImpl.reportStubPsiMismatch(StubIndexImpl.java:534)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:155)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.a(JavaFileManagerImpl.java:145)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:138)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:99)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:385)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:331)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:767)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:757)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:366)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:359)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:328)
	at com.intellij.psi.impl.source.PsiImportStatementBaseImpl.resolve(PsiImportStatementBaseImpl.java:64)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.a(PsiJavaFileBaseImpl.java:314)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.access$100(PsiJavaFileBaseImpl.java:58)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl$MyCacheBuilder.compute(PsiJavaFileBaseImpl.java:480)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:283)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:146)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:438)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:331)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:767)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:268)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:259)
	at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.getQualifiedName(PsiAnnotationImpl.java:96)
	at com.intellij.codeInsight.AnnotationUtil$1$1.create(AnnotationUtil.java:131)
	at com.intellij.codeInsight.AnnotationUtil$1$1.create(AnnotationUtil.java:124)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:52)
	at com.intellij.codeInsight.AnnotationUtil.findOwnAnnotation(AnnotationUtil.java:141)
	at com.intellij.codeInsight.AnnotationUtil.findAnnotation(AnnotationUtil.java:110)
	at com.intellij.codeInsight.AnnotationUtil.findAnnotation(AnnotationUtil.java:92)
	at de.plushnikov.intellij.plugin.util.PsiAnnotationUtil.findAnnotation(PsiAnnotationUtil.java:54)
	at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:47)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.process(LombokAugmentProvider.java:150)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:102)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:44)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.a(ClassInnerStuffCache.java:169)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$200(ClassInnerStuffCache.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$2.compute(ClassInnerStuffCache.java:64)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:131)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getFields(ClassInnerStuffCache.java:60)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.d(ClassInnerStuffCache.java:189)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$500(ClassInnerStuffCache.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$5.compute(ClassInnerStuffCache.java:100)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:131)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.findFieldByName(ClassInnerStuffCache.java:96)
	at com.intellij.psi.impl.source.PsiClassImpl.findFieldByName(PsiClassImpl.java:363)
	at com.intellij.psi.impl.source.PsiFieldImpl.getOriginalElement(PsiFieldImpl.java:404)
	at com.intellij.codeInsight.BaseExternalAnnotationsManager.preferCompiledElement(BaseExternalAnnotationsManager.java:80)
	at com.intellij.codeInsight.BaseExternalAnnotationsManager.findExternalAnnotationsFiles(BaseExternalAnnotationsManager.java:233)
	at com.intellij.codeInsight.BaseExternalAnnotationsManager.a(BaseExternalAnnotationsManager.java:207)
	at com.intellij.codeInsight.BaseExternalAnnotationsManager.a(BaseExternalAnnotationsManager.java:141)
	at com.intellij.codeInsight.BaseExternalAnnotationsManager.findExternalAnnotations(BaseExternalAnnotationsManager.java:118)
	at com.intellij.codeInsight.ExternalAnnotationsLineMarkerProvider.b(ExternalAnnotationsLineMarkerProvider.java:112)
	at com.intellij.codeInsight.ExternalAnnotationsLineMarkerProvider.a(ExternalAnnotationsLineMarkerProvider.java:98)
	at com.intellij.codeInsight.ExternalAnnotationsLineMarkerProvider.getLineMarkerInfo(ExternalAnnotationsLineMarkerProvider.java:86)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.addLineMarkers(LineMarkersPass.java:166)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:105)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
````

**Comment by mplushnikov** [comment]
It look like a problem in base IntelliJ, like: https://youtrack.jetbrains.com/issue/RUBY-16276, and should be fixed in last version of IntelliJ.
I will close this issue here. Feel free to open new issue, if it still occured!
