### ISSUE TITLE
[occasional] on rename: cannot share data context between Swing events

### ISSUE THREAD

**Issue by Janmm14** [mplushnikov/lombok-intellij-plugin#122]
```
cannot share data context between Swing events; initial event count = 612416; current event count = 612735
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:346)
	at com.intellij.openapi.actionSystem.DataContextWrapper.getData(DataContextWrapper.java:38)
	at com.intellij.openapi.actionSystem.AnActionEvent$1.getData(AnActionEvent.java:145)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:75)
	at de.plushnikov.intellij.plugin.extension.LombokElementRenameHandler.isAvailableOnDataContext(LombokElementRenameHandler.java:23)
	at de.plushnikov.intellij.plugin.extension.LombokElementRenameHandler.isRenaming(LombokElementRenameHandler.java:28)
	at com.intellij.refactoring.rename.RenameHandlerRegistry.getRenameHandler(RenameHandlerRegistry.java:76)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenameHandler.performDialogRename(VariableInplaceRenameHandler.java:136)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenameHandler.doRename(MemberInplaceRenameHandler.java:88)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenameHandler.invoke(VariableInplaceRenameHandler.java:90)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:122)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:593)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:644)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:483)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mplushnikov** [comment]
Hello Jan,

can you provide more information for context? Can you describe any steps to reproduce this issue?

**Comment by Janmm14** [comment]
Well I did nothing special just renaming. Not always lombok fields/methods were included when I recieved that error. However intellij says I should report. I'm using Idea CE 14.1.4 and latest version of this plugin.

**Comment by mplushnikov** [comment]
I will close this issue at the moment. Can still not reproduce the problem.
Feel free to open new issue if it occurs again!

**Comment by Janmm14** [comment]
Totally forgot this issue. Did not occurred again.

**Comment by rakpan** [comment]
Hi,

The same issue occurred to me today (using Intellij EAP 2016.2 with latest version of lombok). Below is the trace

`
cannot share data context between Swing events; initial event count = 2677523; current event count = 2677530
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:356)
	at com.intellij.openapi.actionSystem.DataContextWrapper.getData(DataContextWrapper.java:38)
	at com.intellij.openapi.actionSystem.AnActionEvent$1.getData(AnActionEvent.java:145)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:75)
	at com.intellij.refactoring.actions.BaseRefactoringAction.getPsiElementArray(BaseRefactoringAction.java:242)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.getElement(PsiElementRenameHandler.java:217)
	at de.plushnikov.intellij.plugin.extension.LombokElementRenameHandler.isAvailableOnDataContext(LombokElementRenameHandler.java:25)
	at de.plushnikov.intellij.plugin.extension.LombokElementRenameHandler.isRenaming(LombokElementRenameHandler.java:30)
	at com.intellij.refactoring.rename.RenameHandlerRegistry.getRenameHandler(RenameHandlerRegistry.java:76)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenameHandler.performDialogRename(VariableInplaceRenameHandler.java:136)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenameHandler$1.pass(MemberInplaceRenameHandler.java:71)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenameHandler$1.pass(MemberInplaceRenameHandler.java:65)
	at com.intellij.refactoring.rename.RenamePsiElementProcessor.substituteElementToRename(RenamePsiElementProcessor.java:190)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenameHandler.doRename(MemberInplaceRenameHandler.java:65)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenameHandler.invoke(VariableInplaceRenameHandler.java:90)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:123)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:677)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`
