### ISSUE TITLE
IDE Error in IDEA 14.1.4

### ISSUE THREAD

**Issue by jkwatson** [mplushnikov/lombok-intellij-plugin#133]
Got this after running some unit tests.  Nothing unusual that I know of was going on.

null
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:793)
	at java.util.HashMap$KeyIterator.next(HashMap.java:828)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:305)
	at java.util.HashSet.<init>(HashSet.java:100)
	at com.intellij.ui.docking.impl.DockManagerImpl.getContainers(DockManagerImpl.java:129)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getAllSplitters(FileEditorManagerImpl.java:223)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.d(FileEditorManagerImpl.java:1329)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.isFileOpen(FileEditorManagerImpl.java:1206)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:86)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:44)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.b(ClassInnerStuffCache.java:176)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:75)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:131)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:71)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.e(ClassInnerStuffCache.java:204)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$600(ClassInnerStuffCache.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$6.compute(ClassInnerStuffCache.java:114)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:131)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.findMethodsByName(ClassInnerStuffCache.java:110)
	at com.intellij.psi.impl.compiled.ClsClassImpl.findMethodsByName(ClsClassImpl.java:253)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:677)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:478)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:448)
	at com.intellij.psi.impl.compiled.ClsClassImpl.processDeclarations(ClsClassImpl.java:456)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:238)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:227)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl.multiResolve(PsiImportStaticReferenceElementImpl.java:223)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.a(PsiJavaFileBaseImpl.java:358)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:289)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:146)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:438)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:331)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:779)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:769)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:366)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:359)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:328)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher$3.compute(AnnotatedElementsSearcher.java:77)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher$3.compute(AnnotatedElementsSearcher.java:63)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.execute(AnnotatedElementsSearcher.java:63)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.execute(AnnotatedElementsSearcher.java:38)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:43)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.InstanceofQuery.forEach(InstanceofQuery.java:58)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getChildren(JamAnnotationTypeUtilImpl.java:209)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.collectClassWithChildren(JamAnnotationTypeUtilImpl.java:194)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.collectClassWithChildren(JamAnnotationTypeUtilImpl.java:196)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getAnnotationTypes(JamAnnotationTypeUtilImpl.java:90)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.access$200(JamAnnotationTypeUtilImpl.java:44)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl$4.compute(JamAnnotationTypeUtilImpl.java:179)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getAnnotationTypesWithChildren(JamAnnotationTypeUtilImpl.java:186)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getCustomComponentAnnotations(JamAnnotationTypeUtilImpl.java:160)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getUserDefinedCustomComponentAnnotations(JamAnnotationTypeUtilImpl.java:140)
	at com.intellij.spring.model.jam.SpringSemContributor$2.fun(SpringSemContributor.java:159)
	at com.intellij.spring.model.jam.SpringSemContributor$2.fun(SpringSemContributor.java:156)
	at com.intellij.spring.model.jam.SpringSemContributorUtil$2.fun(SpringSemContributorUtil.java:69)
	at com.intellij.spring.model.jam.SpringSemContributorUtil$2.fun(SpringSemContributorUtil.java:64)
	at com.intellij.semantic.SemServiceImpl$6$1.fun(SemServiceImpl.java:129)
	at com.intellij.semantic.SemServiceImpl$6$1.fun(SemServiceImpl.java:125)
	at com.intellij.semantic.SemServiceImpl.a(SemServiceImpl.java:216)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:186)
	at com.intellij.jam.JamService.getMetas(JamService.java:118)
	at com.intellij.jam.JamSemContributor$3.fun(JamSemContributor.java:58)
	at com.intellij.jam.JamSemContributor$3.fun(JamSemContributor.java:50)
	at com.intellij.semantic.SemServiceImpl$6$1.fun(SemServiceImpl.java:129)
	at com.intellij.semantic.SemServiceImpl$6$1.fun(SemServiceImpl.java:125)
	at com.intellij.semantic.SemServiceImpl.a(SemServiceImpl.java:216)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:186)
	at com.intellij.semantic.SemService.getSemElement(SemService.java:37)
	at com.intellij.jam.JamService.getMeta(JamService.java:128)
	at com.intellij.spring.gutter.SpringClassAnnotator.isComponentScanAnno(SpringClassAnnotator.java:194)
	at com.intellij.spring.gutter.SpringClassAnnotator.annotateComponentScan(SpringClassAnnotator.java:209)
	at com.intellij.spring.gutter.SpringClassAnnotator.collectNavigationMarkers(SpringClassAnnotator.java:112)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:48)
	at com.intellij.spring.gutter.SpringClassAnnotator.collectNavigationMarkers(SpringClassAnnotator.java:96)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:39)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:189)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by mplushnikov** [comment]
Hmh, look like a bug in IntelliJ. Can you reproduce it often or in the last IntelliJ version? If it was occurred only once, I will not investigate it at much.

**Comment by jkwatson** [comment]
I haven't seen it again. I wouldn't worry about it.  Feel free to close this.

**Comment by mplushnikov** [comment]
Ok, thank you!
