### ISSUE TITLE
Exception in @Singular handling

### ISSUE THREAD

**Issue by Zteve** [mplushnikov/lombok-intellij-plugin#156]
Just typed in:

```
    @Builder
    StringMapBuilder(@Singular Map<String, R> entries) {
        super(entries);
    }
```
and changed the `R` (which is a generic parameter) to `? extends R` and get the following, repeatedly:
```
com.intellij.psi.PsiWildcardType cannot be cast to com.intellij.psi.PsiClassType
java.lang.ClassCastException: com.intellij.psi.PsiWildcardType cannot be cast to com.intellij.psi.PsiClassType
	at de.plushnikov.intellij.plugin.processor.handler.singular.SingularMapHandler.getBuilderFieldType(SingularMapHandler.java:63)
	at de.plushnikov.intellij.plugin.processor.handler.singular.SingularMapHandler.addBuilderField(SingularMapHandler.java:53)
	at de.plushnikov.intellij.plugin.processor.handler.BuilderHandler.generateFields(BuilderHandler.java:377)
	at de.plushnikov.intellij.plugin.processor.handler.BuilderHandler.createBuilderClass(BuilderHandler.java:250)
	at de.plushnikov.intellij.plugin.processor.method.BuilderMethodProcessor.processIntern(BuilderMethodProcessor.java:50)
	at de.plushnikov.intellij.plugin.processor.method.AbstractMethodProcessor.process(AbstractMethodProcessor.java:42)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.process(LombokAugmentProvider.java:135)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:90)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:50)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.b(ClassInnerStuffCache.java:170)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:75)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:136)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:71)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.e(ClassInnerStuffCache.java:198)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$600(ClassInnerStuffCache.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$6.compute(ClassInnerStuffCache.java:114)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:136)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.findMethodsByName(ClassInnerStuffCache.java:110)
	at com.intellij.psi.impl.source.PsiClassImpl.findMethodsByName(PsiClassImpl.java:383)
	at com.intellij.execution.junit.JUnitUtil.findSuiteMethod(JUnitUtil.java:273)
	at com.intellij.execution.junit.JUnit3Framework.isTestClass(JUnit3Framework.java:76)
	at com.intellij.testIntegration.JavaTestFramework.isTestClass(JavaTestFramework.java:63)
	at com.intellij.codeInsight.TestFrameworksImpl.isTestClass(TestFrameworksImpl.java:38)
	at com.intellij.psi.impl.ElementPresentationUtil.a(ElementPresentationUtil.java:140)
	at com.intellij.psi.impl.ElementPresentationUtil.access$000(ElementPresentationUtil.java:36)
	at com.intellij.psi.impl.ElementPresentationUtil$1.compute(ElementPresentationUtil.java:107)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.impl.ElementPresentationUtil.getClassKind(ElementPresentationUtil.java:112)
	at com.intellij.psi.impl.PsiClassImplUtil$1.fun(PsiClassImplUtil.java:271)
	at com.intellij.psi.impl.PsiClassImplUtil$1.fun(PsiClassImplUtil.java:263)
	at com.intellij.ui.IconDeferrerImpl.a(IconDeferrerImpl.java:87)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:77)
	at com.intellij.psi.impl.PsiClassImplUtil.getClassIcon(PsiClassImplUtil.java:291)
	at com.intellij.psi.impl.PsiClassImplUtil.getClassIcon(PsiClassImplUtil.java:278)
	at com.intellij.psi.impl.source.PsiClassImpl.getElementIcon(PsiClassImpl.java:637)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:125)
	at com.intellij.psi.impl.ElementBase.access$000(ElementBase.java:50)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:61)
	at com.intellij.psi.impl.ElementBase$1.fun(ElementBase.java:54)
	at com.intellij.ui.IconDeferrerImpl.a(IconDeferrerImpl.java:87)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:77)
	at com.intellij.psi.impl.ElementBase.computeIcon(ElementBase.java:113)
	at com.intellij.psi.impl.ElementBase.getIcon(ElementBase.java:89)
	at com.intellij.ide.JavaFileIconPatcher.a(JavaFileIconPatcher.java:71)
	at com.intellij.ide.JavaFileIconPatcher.patchIcon(JavaFileIconPatcher.java:44)
	at com.intellij.util.IconUtil$2.fun(IconUtil.java:153)
	at com.intellij.util.IconUtil$2.fun(IconUtil.java:135)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:238)
	at com.intellij.ui.DeferredIconImpl$1$1$1.run(DeferredIconImpl.java:119)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:122)
	at com.intellij.ui.DeferredIconImpl$1$1.run(DeferredIconImpl.java:116)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$2.run(ProgressIndicatorUtils.java:87)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$5.run(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:94)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:84)
	at com.intellij.ui.DeferredIconImpl$1.run(DeferredIconImpl.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by Zteve** [comment]
Apologies for the heavy repetition there.  :-)

**Comment by mplushnikov** [comment]
Good catch, thank you! 
Should be fixed in the next release.

**Comment by mplushnikov** [comment]
Plugin 0.9.8 was released today
