### ISSUE TITLE
StackOverflowError on opening project

### ISSUE THREAD

**Issue by Zteve** [mplushnikov/lombok-intellij-plugin#160]
I've no idea what produces this, but it occurs as soon as I open my project:
```
null
java.lang.StackOverflowError
    at com.intellij.psi.impl.source.PsiClassImpl.getOwnInnerClasses(PsiClassImpl.java:331)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.c(ClassInnerStuffCache.java:176)

18 copies of:
    at com.intellij.psi.impl.source.ClassInnerStuffCache.access$400(ClassInnerStuffCache.java:38)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$4.compute(ClassInnerStuffCache.java:86)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:136)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.getInnerClasses(ClassInnerStuffCache.java:82)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.f(ClassInnerStuffCache.java:220)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.access$700(ClassInnerStuffCache.java:38)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$7.compute(ClassInnerStuffCache.java:130)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:136)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.findInnerClassByName(ClassInnerStuffCache.java:126)
    at com.intellij.psi.impl.source.PsiClassImpl.findInnerClassByName(PsiClassImpl.java:400)
    at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:548)
    at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:486)
    at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:463)
    at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:491)
    at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
    at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
    at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
    at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:146)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:440)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:341)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:333)
    at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
    at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
    at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:785)
    at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:774)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:368)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:361)
    at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:330)
    at de.plushnikov.intellij.plugin.processor.ValProcessor.isVal(ValProcessor.java:92)
    at de.plushnikov.intellij.plugin.processor.ValProcessor.inferType(ValProcessor.java:106)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.inferType(LombokAugmentProvider.java:110)
    at com.intellij.psi.augment.PsiAugmentProvider.getInferredType(PsiAugmentProvider.java:79)
    at com.intellij.psi.impl.source.PsiTypeElementImpl.e(PsiTypeElementImpl.java:79)
    at com.intellij.psi.impl.source.PsiTypeElementImpl.getType(PsiTypeElementImpl.java:73)
    at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:46)
    at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:42)
    at com.intellij.psi.impl.source.PsiParameterImpl.getType(PsiParameterImpl.java:180)
    at de.plushnikov.intellij.plugin.processor.handler.singular.NonSingularHandler.addBuilderField(NonSingularHandler.java:26)
    at de.plushnikov.intellij.plugin.processor.handler.BuilderHandler.generateFields(BuilderHandler.java:377)
    at de.plushnikov.intellij.plugin.processor.handler.BuilderHandler.createBuilderClass(BuilderHandler.java:250)
    at de.plushnikov.intellij.plugin.processor.method.BuilderClassMethodProcessor.processIntern(BuilderClassMethodProcessor.java:43)
    at de.plushnikov.intellij.plugin.processor.method.AbstractMethodProcessor.process(AbstractMethodProcessor.java:42)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.process(LombokAugmentProvider.java:135)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:90)
    at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:50)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.c(ClassInnerStuffCache.java:177)

preceded by:
    at com.intellij.psi.impl.source.ClassInnerStuffCache.access$400(ClassInnerStuffCache.java:38)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$4.compute(ClassInnerStuffCache.java:86)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:136)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.getInnerClasses(ClassInnerStuffCache.java:82)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.f(ClassInnerStuffCache.java:220)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.access$700(ClassInnerStuffCache.java:38)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$7.compute(ClassInnerStuffCache.java:130)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:136)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.findInnerClassByName(ClassInnerStuffCache.java:126)
    at com.intellij.psi.impl.source.PsiClassImpl.findInnerClassByName(PsiClassImpl.java:400)
    at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:548)
    at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:486)
    at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:463)
    at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:491)
    at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
    at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
    at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
```
This looks like a logic error in lombok processing.

**Comment by jpboudreault** [comment]
Having the same problem here!

**Comment by mplushnikov** [comment]
New pluginversion with some changes for this issue was released today. Please verify and open new issue if the problem still exists...

**Comment by Zteve** [comment]
Thank you. I cannot verify this, as the problem no longer occurs for me and the "testcase" is impossible to reproduce. I have not seen the problem again.

**Comment by mplushnikov** [comment]
Thank you for information!
