### ISSUE TITLE
null java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by relgames** [mplushnikov/lombok-intellij-plugin#164]
Happened in IDEA 15.0.2

```
null
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at java.util.HashSet.<init>(HashSet.java:119)
	at com.intellij.ui.docking.impl.DockManagerImpl.getContainers(DockManagerImpl.java:129)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getAllSplitters(FileEditorManagerImpl.java:233)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.b(FileEditorManagerImpl.java:1368)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.isFileOpen(FileEditorManagerImpl.java:1245)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:86)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:50)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.c(ClassInnerStuffCache.java:177)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$400(ClassInnerStuffCache.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$4.compute(ClassInnerStuffCache.java:86)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:136)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getInnerClasses(ClassInnerStuffCache.java:82)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.a(ClassInnerStuffCache.java:220)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$700(ClassInnerStuffCache.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$7.compute(ClassInnerStuffCache.java:130)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:136)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.findInnerClassByName(ClassInnerStuffCache.java:126)
	at com.intellij.psi.impl.source.PsiClassImpl.findInnerClassByName(PsiClassImpl.java:400)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:548)
	at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:486)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:463)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:491)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:146)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:440)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:341)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:333)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:794)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:783)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:368)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:361)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:330)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher$3.compute(AnnotatedElementsSearcher.java:77)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher$3.compute(AnnotatedElementsSearcher.java:63)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:955)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.execute(AnnotatedElementsSearcher.java:63)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.execute(AnnotatedElementsSearcher.java:38)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.AbstractQuery.findAll(AbstractQuery.java:37)
	at com.intellij.util.InstanceofQuery.findAll(InstanceofQuery.java:38)
	at com.intellij.spring.contexts.model.LocalXmlModelImpl$15.compute(LocalXmlModelImpl.java:577)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:84)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:118)
	at com.intellij.spring.contexts.model.LocalXmlModelImpl.getExplicitBeanCandidatePsiClasses(LocalXmlModelImpl.java:568)
	at com.intellij.spring.contexts.model.LocalXmlModelImpl.access$700(LocalXmlModelImpl.java:57)
	at com.intellij.spring.contexts.model.LocalXmlModelImpl$14$1.compute(LocalXmlModelImpl.java:527)
	at com.intellij.spring.contexts.model.LocalXmlModelImpl$14$1.compute(LocalXmlModelImpl.java:520)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
	at com.intellij.spring.contexts.model.BeansSpringModel.calculateLocalBeans(BeansSpringModel.java:66)
	at com.intellij.spring.contexts.model.CachedLocalModel.getLocalBeans(CachedLocalModel.java:74)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processByClass(AbstractSimpleSpringModel.java:126)
	at com.intellij.spring.contexts.model.CachedLocalModel$6.process(CachedLocalModel.java:173)
	at com.intellij.spring.contexts.model.CachedLocalModel$6.process(CachedLocalModel.java:170)
	at com.intellij.spring.contexts.model.CachedLocalModel$5.compute(CachedLocalModel.java:144)
	at com.intellij.spring.contexts.model.CachedLocalModel$5.compute(CachedLocalModel.java:140)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.spring.contexts.model.CachedLocalModel.processRelatedModels(CachedLocalModel.java:140)
	at com.intellij.spring.contexts.model.CachedLocalModel.processRelatedModels(CachedLocalModel.java:170)
	at com.intellij.spring.contexts.model.LocalXmlModelImpl.processByClass(LocalXmlModelImpl.java:419)
	at com.intellij.spring.contexts.model.SpringModel.processByClass(SpringModel.java:174)
	at com.intellij.spring.contexts.model.SpringModel.processByClass(SpringModel.java:174)
	at com.intellij.spring.model.utils.SpringModelSearchers.containsBean(SpringModelSearchers.java:89)
	at com.intellij.spring.model.utils.SpringModelSearchers.doesBeanExist(SpringModelSearchers.java:77)
	at com.intellij.spring.java.SpringJavaClassInfo$1.compute(SpringJavaClassInfo.java:83)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.spring.java.SpringJavaClassInfo.isMapped(SpringJavaClassInfo.java:208)
	at com.intellij.spring.code.SpringImplicitUsageProvider.isMappedBeanClass(SpringImplicitUsageProvider.java:82)
	at com.intellij.spring.code.SpringImplicitUsageProvider.isBeanClassOrConstructor(SpringImplicitUsageProvider.java:69)
	at com.intellij.spring.code.SpringImplicitUsageProvider.isImplicitUsage(SpringImplicitUsageProvider.java:36)
	at com.intellij.codeInsight.daemon.impl.UnusedSymbolUtil.isImplicitUsage(UnusedSymbolUtil.java:53)
	at com.intellij.codeInsight.daemon.impl.UnusedSymbolUtil.a(UnusedSymbolUtil.java:307)
	at com.intellij.codeInsight.daemon.impl.UnusedSymbolUtil.isClassUsed(UnusedSymbolUtil.java:296)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.a(PostHighlightingVisitor.java:477)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.a(PostHighlightingVisitor.java:263)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.collectHighlights(PostHighlightingVisitor.java:197)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl$3.run(HighlightVisitorImpl.java:186)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:306)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:179)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:65)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by mplushnikov** [comment]
New pluginversion with some changes for this issue was released today. Please verify and open new issue if the problem still exists...
