### ISSUE TITLE
IntelliJ 15.0.2 - Processor could not be initalized

### ISSUE THREAD

**Issue by dmydlarz** [mplushnikov/lombok-intellij-plugin#167]
My configuration:

* Intellij 15.0.2 (#IU-143.1184)
* Lombok Plugin (0.9.6.14)
* Java (1.8.0.66)
* I've enabled both *Enable Annotation processing* in preferences & default preferences.

While starting Spock test from IntellIJ I am getting:

```
Warning:(11, 8) java: lombok.javac.apt.Processor could not be initialized. Lombok will not run during this compilation: java.lang.RuntimeException: java.lang.ClassNotFoundException: lombok.javac.handlers.HandleHelper
  	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:114)
  	at lombok.javac.HandlerLibrary.loadAnnotationHandlers(HandlerLibrary.java:170)
  	at lombok.javac.HandlerLibrary.load(HandlerLibrary.java:155)
  	at lombok.javac.JavacTransformer.<init>(JavacTransformer.java:43)
  	at lombok.javac.apt.Processor.init(Processor.java:86)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:141)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:53)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:168)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:385)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:286)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:194)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:166)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1230)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:904)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:976)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:870)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:695)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:386)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:193)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:137)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:294)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
  	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:42)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  	at java.lang.Thread.run(Thread.java:745)
  Caused by: java.lang.ClassNotFoundException: lombok.javac.handlers.HandleHelper
  	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:373)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	at java.lang.Class.forName0(Native Method)
  	at java.lang.Class.forName(Class.java:344)
  	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:111)
  	... 40 more
```

**Comment by mplushnikov** [comment]
It looks like a problem with lombok itself. (Similar to: https://github.com/rzwitserloot/lombok/issues/930) Please make an issue on lombok page.
