### ISSUE TITLE
"Invalid method call expression" calling super() with enclosing type

### ISSUE THREAD

**Issue by danjl1100** [mplushnikov/lombok-intellij-plugin#169]
I'm using Android Studio v1.5.1 (with Android Support plugin v10.1.5.1).

When using the following code:

```java
public class OuterA {

    class InnerA {

    }

}

class OuterB {

    static class InnerB extends OuterA.InnerA {

        public InnerB(OuterA enclosingReference) {
            enclosingReference.super();
        }

    }

}
```

I get the following error:
```
Invalid method call expression. Children:
PsiReferenceExpression:enclosingReference.super
  PsiReferenceExpression:enclosingReference
    PsiReferenceParameterList
      <empty list>
    PsiIdentifier:enclosingReference('enclosingReference')
  PsiJavaToken:DOT('.')
  PsiKeyword:super('super')

com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:117)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.getTypeArgumentList(PsiMethodCallExpressionImpl.java:80)
	at org.jetbrains.android.inspections.lint.LombokPsiConverter.toMethodInvocation(LombokPsiConverter.java:1208)
	at org.jetbrains.android.inspections.lint.LombokPsiConverter.toExpression(LombokPsiConverter.java:916)
	at org.jetbrains.android.inspections.lint.LombokPsiConverter.toStatement(LombokPsiConverter.java:1246)
	at org.jetbrains.android.inspections.lint.LombokPsiConverter.toBlock(LombokPsiConverter.java:1531)
	at org.jetbrains.android.inspections.lint.LombokPsiConverter.toConstructorDeclaration(LombokPsiConverter.java:1854)
	at org.jetbrains.android.inspections.lint.LombokPsiConverter.toTypeBody(LombokPsiConverter.java:442)
	at org.jetbrains.android.inspections.lint.LombokPsiConverter.toTypeDeclaration(LombokPsiConverter.java:419)
	at org.jetbrains.android.inspections.lint.LombokPsiConverter.toTypeBody(LombokPsiConverter.java:448)
	at org.jetbrains.android.inspections.lint.LombokPsiConverter.toTypeDeclaration(LombokPsiConverter.java:419)
	at org.jetbrains.android.inspections.lint.LombokPsiConverter.toCompilationUnit(LombokPsiConverter.java:304)
	at org.jetbrains.android.inspections.lint.LombokPsiConverter.convert(LombokPsiConverter.java:196)
	at org.jetbrains.android.inspections.lint.LombokPsiParser.parse(LombokPsiParser.java:100)
	at org.jetbrains.android.inspections.lint.LombokPsiParser.parseJava(LombokPsiParser.java:71)
	at com.android.tools.lint.client.api.JavaVisitor.visitFile(JavaVisitor.java:245)
	at com.android.tools.lint.client.api.LintDriver.checkIndividualJavaFiles(LintDriver.java:1569)
	at com.android.tools.lint.client.api.LintDriver.runFileDetectors(LintDriver.java:1047)
	at com.android.tools.lint.client.api.LintDriver.checkProject(LintDriver.java:906)
	at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:435)
	at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:376)
	at org.jetbrains.android.inspections.lint.AndroidLintExternalAnnotator.doAnnotate(AndroidLintExternalAnnotator.java:162)
	at org.jetbrains.android.inspections.lint.AndroidLintExternalAnnotator.doAnnotate(AndroidLintExternalAnnotator.java:67)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:183)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:45)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:125)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
	at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
	at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
	at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
	at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

The code compiles using javac v1.7.0_05, so I think that there might be something wrong with the lombok plugin.

**Comment by mplushnikov** [comment]
I think it has nothing with lombok plugin for intellij. As I see, it comes from android studio classes. I found similar issue for example here: https://code.google.com/p/android/issues/detail?id=161534
Maybe you can ask guys from android studio?
