### ISSUE TITLE
Null pointer in intellij version 15.0.3

### ISSUE THREAD

**Issue by devshorts** [mplushnikov/lombok-intellij-plugin#177]
IDEA Build #IU-143.1821

I am getting a consistent null pointer error with the following stack

```
null
java.lang.AssertionError
	at de.plushnikov.intellij.plugin.provider.LombokProcessorProvider.addApplicableProcessors(LombokProcessorProvider.java:130)
	at de.plushnikov.intellij.plugin.provider.LombokProcessorProvider.getApplicableProcessors(LombokProcessorProvider.java:122)
	at de.plushnikov.intellij.plugin.provider.LombokImplicitUsageProvider.checkUsage(LombokImplicitUsageProvider.java:39)
	at de.plushnikov.intellij.plugin.provider.LombokImplicitUsageProvider.isImplicitWrite(LombokImplicitUsageProvider.java:33)
	at de.plushnikov.intellij.plugin.provider.LombokImplicitUsageProvider.isImplicitUsage(LombokImplicitUsageProvider.java:23)
	at com.intellij.codeInsight.daemon.impl.UnusedSymbolUtil.isImplicitUsage(UnusedSymbolUtil.java:53)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.a(PostHighlightingVisitor.java:315)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.a(PostHighlightingVisitor.java:253)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.collectHighlights(PostHighlightingVisitor.java:197)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl$3.run(HighlightVisitorImpl.java:186)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:306)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:179)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:65)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:219)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by mplushnikov** [comment]
Should be fixed in the next release 0.9.8

**Comment by devshorts** [comment]
Awesome, thanks! Love the plugin :)

**Comment by mplushnikov** [comment]
Plugin 0.9.8 was released today
