### ISSUE TITLE
lombok not support java8 

### ISSUE THREAD

**Issue by intohole** [mplushnikov/lombok-intellij-plugin#216]
Warning:(14, 8) java: Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/code/TypeTags
  	at lombok.javac.handlers.HandleGetter.<clinit>(HandleGetter.java:263)
  	at java.lang.Class.forName0(Native Method)
  	at java.lang.Class.forName(Class.java:348)
  	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:111)
  	at lombok.javac.HandlerLibrary.loadAnnotationHandlers(HandlerLibrary.java:107)
  	at lombok.javac.HandlerLibrary.load(HandlerLibrary.java:94)
  	at lombok.javac.JavacTransformer.<init>(JavacTransformer.java:43)
  	at lombok.javac.apt.Processor.init(Processor.java:81)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:89)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:143)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:168)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:385)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:286)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:194)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:166)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1230)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:904)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:976)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:870)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:695)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:386)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:193)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:137)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:294)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
  	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:42)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  	at java.lang.Thread.run(Thread.java:745)
  Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.code.TypeTags
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	... 43 more

my env:
jdk1.8 
mac air 10.11
idea 15

i check old issue , but i didn't find work method ;

**Comment by AlexejK** [comment]
Hi and thank you for reporting this.

I have a few questions to get further with this:
 - Can you please provide a sample project that exhibits this issues?
 - Which plugin version are you using?
 - What version of a Lombok dependency do you have?

**Comment by intohole** [comment]
lombok version:0.11.15

**Comment by AlexejK** [comment]
`0.11.15` is the lombok plugin for intellij.
You must, however also have the lombok itself as a project dependency. for instances the latest version is `1.16.8`, and dependency artifact name is "org.projectlombok:lombok:1.16.8" (In Gradle notation).

A sample project helps a lot to understand what's wrong with your setup.

Java 8 is supported and we are using it extensively, so I believe it's related to the project configuration.

Do you also have Annotation processing enabled?

**Comment by intohole** [comment]
i config Annotation processing enabled ; I locate in china , i couldn't download lastest release ,  Could you upload other location that i can download it ?

**Comment by AlexejK** [comment]
The lombok dependency on your classpath should be installed according to either readme of this project, or from https://projectlombok.org/download.html

As I mentioned before, this plugin is **only** providing IDEA support. Compiler still needs Lombok itself to be on your classpath. Please refer to [README.md](https://github.com/mplushnikov/lombok-intellij-plugin/blob/master/README.md#installation) for more information.

If you can provide a link to a sample project where you are having this problem - I can take a further look at it. Without that information, it's hard to do anything about it.

**Comment by Janmm14** [comment]
@intohole If you can't access specific sites, consider using some tools that will unblock it.

**Comment by intohole** [comment]
thx , i found  i config wrong , i  will check my config , and update my pom.xml to newest version ;
