### ISSUE TITLE
Error logged: SpinAllocator has exhausted! Too manySpinAllocator has exhausted! Too many threads or you're going to get StackOverflow. threads or you're going to get StackOverflow.

### ISSUE THREAD

**Issue by devshorts** [mplushnikov/lombok-intellij-plugin#224]
Getting this error while in a scala project. It seems to still work fine in java land. Not sure what gives.  I'm not seeing any actual side effects of the issue other than an error that pop ups sometimes

```
SpinAllocator has exhausted! Too many threads or you're going to get StackOverflow.
com.intellij.util.SpinAllocator$AllocatorExhaustedException: SpinAllocator has exhausted! Too many threads or you're going to get StackOverflow.
    at com.intellij.util.SpinAllocator.alloc(SpinAllocator.java:75)
    at com.intellij.util.StringBuilderSpinAllocator.alloc(StringBuilderSpinAllocator.java:47)
    at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.createEqualsBlockString(EqualsAndHashCodeProcessor.java:229)
    at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.createEqualsCodeBlock(EqualsAndHashCodeProcessor.java:164)
    at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.createEqualsMethod(EqualsAndHashCodeProcessor.java:151)
    at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.createEqualAndHashCode(EqualsAndHashCodeProcessor.java:120)
    at de.plushnikov.intellij.plugin.processor.clazz.ValueProcessor.generatePsiElements(ValueProcessor.java:90)
    at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:53)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:125)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:80)
    at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:50)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.b(ClassInnerStuffCache.java:170)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:38)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:75)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:71)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.f(ClassInnerStuffCache.java:198)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.access$600(ClassInnerStuffCache.java:38)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$6.compute(ClassInnerStuffCache.java:114)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.findMethodsByName(ClassInnerStuffCache.java:110)
    at com.intellij.psi.impl.source.PsiClassImpl.findMethodsByName(PsiClassImpl.java:383)
    at com.intellij.psi.impl.PsiImplUtil.findAttributeValue(PsiImplUtil.java:103)
    at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.findAttributeValue(PsiAnnotationImpl.java:66)
    at de.plushnikov.intellij.plugin.util.PsiAnnotationUtil.getAnnotationValues(PsiAnnotationUtil.java:55)
    at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.filterFields(AbstractClassProcessor.java:151)
    at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.createEqualsBlockString(EqualsAndHashCodeProcessor.java:242)
    at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.createEqualsCodeBlock(EqualsAndHashCodeProcessor.java:164)
    at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.createEqualsMethod(EqualsAndHashCodeProcessor.java:151)
    at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.createEqualAndHashCode(EqualsAndHashCodeProcessor.java:120)
    at de.plushnikov.intellij.plugin.processor.clazz.ValueProcessor.generatePsiElements(ValueProcessor.java:90)
    at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:53)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:125)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:80)
    at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:50)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.b(ClassInnerStuffCache.java:170)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:38)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:75)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:71)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.f(ClassInnerStuffCache.java:198)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.access$600(ClassInnerStuffCache.java:38)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$6.compute(ClassInnerStuffCache.java:114)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.findMethodsByName(ClassInnerStuffCache.java:110)
    at com.intellij.psi.impl.source.PsiClassImpl.findMethodsByName(PsiClassImpl.java:383)
    at com.intellij.psi.impl.PsiImplUtil.findAttributeValue(PsiImplUtil.java:103)
    at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.findAttributeValue(PsiAnnotationImpl.java:66)
    at de.plushnikov.intellij.plugin.util.PsiAnnotationUtil.getAnnotationValues(PsiAnnotationUtil.java:55)
    at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.filterFields(AbstractClassProcessor.java:151)
    at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.createEqualsBlockString(EqualsAndHashCodeProcessor.java:242)
    at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.createEqualsCodeBlock(EqualsAndHashCodeProcessor.java:164)
    at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.createEqualsMethod(EqualsAndHashCodeProcessor.java:151)
    at de.plushnikov.intellij.plugin.processor.clazz.EqualsAndHashCodeProcessor.createEqualAndHashCode(EqualsAndHashCodeProcessor.java:120)
    at de.plushnikov.intellij.plugin.processor.clazz.ValueProcessor.generatePsiElements(ValueProcessor.java:90)
    at de

... truncated ...

de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:125)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:80)
    at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:50)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.b(ClassInnerStuffCache.java:170)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:38)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:75)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:71)
    at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:301)
    at com.intellij.psi.impl.PsiImplUtil.getConstructors(PsiImplUtil.java:71)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$1.compute(ClassInnerStuffCache.java:53)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:84)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:133)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.getConstructors(ClassInnerStuffCache.java:49)
    at com.intellij.psi.impl.source.PsiClassImpl.getConstructors(PsiClassImpl.java:307)
    at com.intellij.codeInsight.intention.impl.CreateSubclassAction.isAvailable(CreateSubclassAction.java:92)
    at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
    at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:128)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:307)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:304)
    at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:153)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:304)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:225)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:201)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)



```

**Comment by mplushnikov** [comment]
Are you using last version (0.11) of plugin? What is your Intellij version? OS?

**Comment by devshorts** [comment]
I am using version 0.11.6, intellij version 2016.1.1 build 145.597, osx el capitan

**Comment by archenroot** [comment]
Same here.

Message: provider: de.plushnikov.intellij.plugin.provider.LombokAugmentProvider@29b940a7: SpinAllocator has exhausted! Too many threads or you're going to get StackOverflow.

Running on:
IntelliJ IDEA 2016.2.5
Build #IU-162.2228.15, built on October 14, 2016

JRE: 1.8.0_91-b14 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Lombok plugin:
0.3.16

**Comment by mplushnikov** [comment]
Exception like this should not be occurring anymore, because all usages of SpinAllocator were removed in last plugin release 0.15.
