### ISSUE TITLE
Problem with Intellij IDEA 2016.2

### ISSUE THREAD

**Issue by nickus** [mplushnikov/lombok-intellij-plugin#242]
Hi! Problem with Intellij IDEA 2016.2

IntelliJ IDEA 2016.2 EAP
Build #IU-162.646.4, built on May 31, 2016
IntelliJ IDEA EAP User
Expiration date: ******
JRE: 1.8.0_76-release-b205 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.16.6</version>
            <scope>provided</scope>
        </dependency>

null
java.lang.StackOverflowError
	at com.intellij.ide.util.PropertiesComponent.getBoolean(PropertiesComponent.java:94)
	at de.plushnikov.intellij.plugin.settings.ProjectSettings.isEnabled(ProjectSettings.java:32)
	at de.plushnikov.intellij.plugin.settings.ProjectSettings.isEnabled(ProjectSettings.java:28)
	at de.plushnikov.intellij.plugin.settings.ProjectSettings.isLombokEnabledInProject(ProjectSettings.java:20)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:71)
	at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:95)
	at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:92)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:146)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:92)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.d(ClassInnerStuffCache.java:170)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:75)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:71)
	at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:301)
	at com.intellij.psi.impl.source.PsiModifierListImpl.a(PsiModifierListImpl.java:149)
	at com.intellij.psi.impl.source.PsiModifierListImpl.b(PsiModifierListImpl.java:91)
	at com.intellij.psi.impl.source.PsiModifierListImpl.hasModifierProperty(PsiModifierListImpl.java:84)
	at com.intellij.psi.impl.source.PsiClassImpl.hasModifierProperty(PsiClassImpl.java:208)
	at com.intellij.psi.util.PsiUtil.typeParametersIterable(PsiUtil.java:938)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createRawSubstitutor(PsiElementFactoryImpl.java:367)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createType(PsiElementFactoryImpl.java:339)
	at com.intellij.psi.impl.source.PsiEnumConstantImpl.getType(PsiEnumConstantImpl.java:123)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.filterGetterFields(GetterProcessor.java:104)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.createFieldGetters(GetterProcessor.java:78)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.generatePsiElements(GetterProcessor.java:71)
	at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:53)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:125)
	.....

**Comment by nickus** [comment]
Additional StackTrace:

null
java.lang.StackOverflowError
	at java.lang.ThreadLocal.get(ThreadLocal.java:161)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.isReadLockedByThisThread(ReadMostlyRWLock.java:77)
	at com.intellij.openapi.application.impl.ApplicationImpl.isReadAccessAllowed(ApplicationImpl.java:977)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:956)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:178)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:758)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:747)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:371)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:364)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:333)
	at com.intellij.psi.impl.PsiImplUtil.findAttributeValue(PsiImplUtil.java:102)
	at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.findAttributeValue(PsiAnnotationImpl.java:66)
	at de.plushnikov.intellij.plugin.util.PsiAnnotationUtil.getStringAnnotationValue(PsiAnnotationUtil.java:82)
	at de.plushnikov.intellij.plugin.util.LombokProcessorUtil.getMethodModifier(LombokProcessorUtil.java:35)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.validateVisibility(GetterProcessor.java:64)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.validate(GetterProcessor.java:45)
	at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:51)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:125)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:80)
	at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:95)
	at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:92)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:146)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:92)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.d(ClassInnerStuffCache.java:170)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:75)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:71)
	at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:301)
	at com.intellij.psi.impl.source.PsiModifierListImpl.a(PsiModifierListImpl.java:149)
	at com.intellij.psi.impl.source.PsiModifierListImpl.b(PsiModifierListImpl.java:91)
	at com.intellij.psi.impl.source.PsiModifierListImpl.hasModifierProperty(PsiModifierListImpl.java:84)
	at com.intellij.psi.impl.source.PsiClassImpl.hasModifierProperty(PsiClassImpl.java:208)
	at com.intellij.psi.util.PsiUtil.typeParametersIterable(PsiUtil.java:938)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createRawSubstitutor(PsiElementFactoryImpl.java:367)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createType(PsiElementFactoryImpl.java:339)
	at com.intellij.psi.impl.source.PsiEnumConstantImpl.getType(PsiEnumConstantImpl.java:123)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.filterGetterFields(GetterProcessor.java:104)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.createFieldGetters(GetterProcessor.java:78)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.generatePsiElements(GetterProcessor.java:71)
	at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:53)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:125)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:80)
	at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:95)
	at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:92)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:146)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:92)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.d(ClassInnerStuffCache.java:170)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:38)
	at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:75)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:71)
	at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:301)
	at com.intellij.psi.impl.source.PsiModifierListImpl.a(PsiModifierListImpl.java:149)
	at com.intellij.psi.impl.source.PsiModifierListImpl.b(PsiModifierListImpl.java:91)
	at com.intellij.psi.impl.source.PsiModifierListImpl.hasModifierProperty(PsiModifierListImpl.java:84)
	at com.intellij.psi.impl.source.PsiClassImpl.hasModifierProperty(PsiClassImpl.java:208)
	at com.intellij.psi.util.PsiUtil.typeParametersIterable(PsiUtil.java:938)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createRawSubstitutor(PsiElementFactoryImpl.java:367)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createType(PsiElementFactoryImpl.java:339)
	at com.intellij.psi.impl.source.PsiEnumConstantImpl.getType(PsiEnumConstantImpl.java:123)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.filterGetterFields(GetterProcessor.java:104)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.createFieldGetters(GetterProcessor.java:78)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.generatePsiElements(GetterProcessor.java:71)
	at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:53)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:125)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)

**Comment by AlexejK** [comment]
Sounds like related to #241 and is due to latest EAP changes. Any sample projects where the issue exhibits and could be reproduced?

**Comment by mplushnikov** [comment]
Hello @nickus, 
please verify it again with IntelliJ EAP Build >=162.844
Jetbrains changed some possible problem places.

**Comment by nickus** [comment]
Hello @mplushnikov 
The bug is fixed! Thanks!
