### ISSUE TITLE
IntelliJ EAP 2016.2 StackOverflow

### ISSUE THREAD

**Issue by mplushnikov** [mplushnikov/lombok-intellij-plugin#244]
> @IceMan81 
> seeing the following Fatal Error when trying to use Intellij. This shows up as soon as the project is opened in the IDE. The stack trace does look different from the one listed here but it didn't make sense to create a new issue, so adding it here.

[Full Stacktrace](http://pastebin.ca/3621542)

```
java.lang.StackOverflowError
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:183)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:161)
    at com.intellij.lang.java.parser.ExpressionParser.d(ExpressionParser.java:215)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:158)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:183)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:155)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:183)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:152)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:183)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:149)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:183)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:146)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:183)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:143)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:183)
    at com.intellij.lang.java.parser.ExpressionParser.a(ExpressionParser.java:140)
    at com.intellij.lang.java.parser.ExpressionParser.parseConditional(ExpressionParser.java:104)
    at com.intellij.lang.java.parser.DeclarationParser.parseAnnotationValue(DeclarationParser.java:911)
    at com.intellij.lang.java.parser.DeclarationParser.a(DeclarationParser.java:933)
    at com.intellij.lang.java.parser.DeclarationParser.parseAnnotationValue(DeclarationParser.java:908)
    at com.intellij.lang.java.parser.DeclarationParser.a(DeclarationParser.java:878)
    at com.intellij.lang.java.parser.DeclarationParser.b(DeclarationParser.java:832)
    at com.intellij.lang.java.parser.DeclarationParser.parseAnnotation(DeclarationParser.java:812)
    at com.intellij.psi.impl.PsiJavaParserFacadeImpl$1.parse(PsiJavaParserFacadeImpl.java:61)
    at com.intellij.lang.java.parser.JavaParserUtil.parseFragment(JavaParserUtil.java:202)
    at com.intellij.psi.impl.source.tree.JavaElementType$JavaDummyElementType.parseContents(JavaElementType.java:286)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.b(LazyParseableElement.java:192)
    at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:231)
    at com.intellij.psi.impl.source.JavaDummyElement.getFirstChildNode(JavaDummyElement.java:69)
    at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createAnnotationFromText(PsiJavaParserFacadeImpl.java:169)
    at com.intellij.psi.impl.PsiElementFactoryImpl.createAnnotationFromText(PsiElementFactoryImpl.java:682)
    at de.plushnikov.intellij.plugin.psi.LombokLightModifierList.addAnnotation(LombokLightModifierList.java:74)
    at de.plushnikov.intellij.plugin.processor.clazz.constructor.AbstractConstructorClassProcessor.createConstructor(AbstractConstructorClassProcessor.java:267)
    at de.plushnikov.intellij.plugin.processor.clazz.constructor.AbstractConstructorClassProcessor.createConstructorMethod(AbstractConstructorClassProcessor.java:241)
    at de.plushnikov.intellij.plugin.processor.clazz.constructor.RequiredArgsConstructorProcessor.createRequiredArgsConstructor(RequiredArgsConstructorProcessor.java:54)
    at de.plushnikov.intellij.plugin.processor.clazz.constructor.RequiredArgsConstructorProcessor.generatePsiElements(RequiredArgsConstructorProcessor.java:46)
    at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:53)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:125)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:80)
    at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:95)
    at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:92)
    at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:146)
    at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:92)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.d(ClassInnerStuffCache.java:170)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:38)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:75)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:71)
    at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:301)
    at com.intellij.psi.impl.source.PsiModifierListImpl.a(PsiModifierListImpl.java:149)
    at com.intellij.psi.impl.source.PsiModifierListImpl.b(PsiModifierListImpl.java:91)
    at com.intellij.psi.impl.source.PsiModifierListImpl.hasModifierProperty(PsiModifierListImpl.java:84)
    at com.intellij.psi.impl.source.PsiClassImpl.hasModifierProperty(PsiClassImpl.java:208)
    at com.intellij.psi.util.PsiUtil.typeParametersIterable(PsiUtil.java:938)
    at com.intellij.psi.impl.PsiElementFactoryImpl.createRawSubstitutor(PsiElementFactoryImpl.java:367)
    at com.intellij.psi.impl.PsiElementFactoryImpl.createType(PsiElementFactoryImpl.java:339)
    at com.intellij.psi.impl.source.PsiEnumConstantImpl.getType(PsiEnumConstantImpl.java:123)
    at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.filterGetterFields(GetterProcessor.java:104)
    at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.createFieldGetters(GetterProcessor.java:78)
    at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.generatePsiElements(GetterProcessor.java:71)
    at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:53)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:125)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:80)
    at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:95)
    at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:92)
    at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:146)
    at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:92)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.d(ClassInnerStuffCache.java:170)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:38)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:75)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:71)
    at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:301)
    at com.intellij.psi.impl.source.PsiModifierListImpl.a(PsiModifierListImpl.java:149)
    at com.intellij.psi.impl.source.PsiModifierListImpl.b(PsiModifierListImpl.java:91)
    at com.intellij.psi.impl.source.PsiModifierListImpl.hasModifierProperty(PsiModifierListImpl.java:84)
    at com.intellij.psi.impl.source.PsiClassImpl.hasModifierProperty(PsiClassImpl.java:208)
    at com.intellij.psi.util.PsiUtil.typeParametersIterable(PsiUtil.java:938)
    at com.intellij.psi.impl.PsiElementFactoryImpl.createRawSubstitutor(PsiElementFactoryImpl.java:367)
    at com.intellij.psi.impl.PsiElementFactoryImpl.createType(PsiElementFactoryImpl.java:339)
    at com.intellij.psi.impl.source.PsiEnumConstantImpl.getType(PsiEnumConstantImpl.java:123)
    at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.filterGetterFields(GetterProcessor.java:104)
    at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.createFieldGetters(GetterProcessor.java:78)
    at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.generatePsiElements(GetterProcessor.java:71)
    at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:53)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:125)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:80)
    at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:95)
    at com.intellij.psi.augment.PsiAugmentProvider$1.process(PsiAugmentProvider.java:92)
    at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:146)
    at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:92)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.d(ClassInnerStuffCache.java:170)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.access$300(ClassInnerStuffCache.java:38)
    at com.intellij.psi.impl.source.ClassInnerStuffCache$3.compute(ClassInnerStuffCache.java:75)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
    at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:71)
    at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:301)
    at com.intellij.psi.impl.source.PsiModifierListImpl.a(PsiModifierListImpl.java:149)
    at com.intellij.psi.impl.source.PsiModifierListImpl.b(PsiModifierListImpl.java:91)
    at com.intellij.psi.impl.source.PsiModifierListImpl.hasModifierProperty(PsiModifierListImpl.java:84)
    at com.intellij.psi.impl.source.PsiClassImpl.hasModifierProperty(PsiClassImpl.java:208)
    at com.intellij.psi.util.PsiUtil.typeParametersIterable(PsiUtil.java:938)
    at com.intellij.psi.impl.PsiElementFactoryImpl.createRawSubstitutor(PsiElementFactoryImpl.java:367)
    at com.intellij.psi.impl.PsiElementFactoryImpl.createType(PsiElementFactoryImpl.java:339)
    at com.intellij.psi.impl.source.PsiEnumConstantImpl.getType(PsiEnumConstantImpl.java:123)
    at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.filterGetterFields(GetterProcessor.java:104)
    at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.createFieldGetters(GetterProcessor.java:78)
    at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.generatePsiElements(GetterProcessor.java:71)
    at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:53)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:125)
```

**Comment by mplushnikov** [comment]
Another issue from #241

**Comment by mplushnikov** [comment]
@IceMan81 
Please provide more information, at least version of IntelliJ EAP you are using.
Minimal sample project reproducing the issue would be great!

**Comment by mplushnikov** [comment]
After looking deeper in your stacktrace, it's the same issue as reported by original #241. It should be fixed in the next EAP Build >=162.844

**Comment by IceMan81** [comment]
@mplushnikov Sorry for the lack of information. I just got 162.844, but I've disabled the plugin. Do you want me to try with it?

**Comment by mplushnikov** [comment]
Yes, sure, please verify it in your environment!
