### ISSUE TITLE
IDE Fatal Error on startup

### ISSUE THREAD

**Issue by ldub** [mplushnikov/lombok-intellij-plugin#286]
The IDE does not crash but it shows this exception and my lombok no longer works. I am using version 2016.2

`Recursive conflict resolution for:PsiMethod:uniqueIndex; (allItems, new Function<Item.ItemData, ItemType>() {
            @Override public ItemType apply(@Nullable Item.ItemData input) {
                return input.getItemType(); }}); file=PsiFile:Maps.class
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
    at com.intellij.psi.scope.conflictResolvers.JavaMethodsConflictResolver.resolveConflict(JavaMethodsConflictResolver.java:79)
    at com.intellij.psi.scope.processor.ConflictFilterProcessor.getResult(ConflictFilterProcessor.java:91)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolveToMethod(PsiReferenceExpressionImpl.java:304)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolve(PsiReferenceExpressionImpl.java:284)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:61)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:196)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:185)
    at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
    at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
    at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:752)
    at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:741)
    at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:345)
    at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:161)
    at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:155)
    at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:87)
    at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.getType(PsiMethodCallExpressionImpl.java:55)
    at de.plushnikov.intellij.plugin.processor.ValProcessor$1.compute(ValProcessor.java:139)
    at de.plushnikov.intellij.plugin.processor.ValProcessor$1.compute(ValProcessor.java:136)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at de.plushnikov.intellij.plugin.processor.ValProcessor.processLocalVariableInitializer(ValProcessor.java:136)
    at de.plushnikov.intellij.plugin.processor.ValProcessor.inferType(ValProcessor.java:120)
    at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.inferType(LombokAugmentProvider.java:95)
    at com.intellij.psi.augment.PsiAugmentProvider$2.process(PsiAugmentProvider.java:110)
    at com.intellij.psi.augment.PsiAugmentProvider$2.process(PsiAugmentProvider.java:107)
    at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:146)
    at com.intellij.psi.augment.PsiAugmentProvider.getInferredType(PsiAugmentProvider.java:107)
    at com.intellij.psi.impl.source.PsiTypeElementImpl.calculateType(PsiTypeElementImpl.java:72)
    at com.intellij.psi.impl.source.PsiTypeElementImpl.access$000(PsiTypeElementImpl.java:39)
    at com.intellij.psi.impl.source.PsiTypeElementImpl$1.compute(PsiTypeElementImpl.java:66)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:84)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:133)
    at com.intellij.psi.impl.source.PsiTypeElementImpl.getType(PsiTypeElementImpl.java:62)
    at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:50)
    at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:46)
    at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.getType(PsiLocalVariableImpl.java:98)
    at com.intellij.psi.util.PsiTypesUtil.getExpectedTypeByParent(PsiTypesUtil.java:202)
    at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferMethodTypeParameterFromParent(PsiOldInferenceHelper.java:677)
    at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferMethodTypeParameterFromParent(PsiOldInferenceHelper.java:423)
    at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferTypeArguments(PsiOldInferenceHelper.java:286)
    at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.inferTypeArguments(PsiResolveHelperImpl.java:190)
    at com.intellij.psi.infos.MethodCandidateInfo$4.compute(MethodCandidateInfo.java:396)
    at com.intellij.psi.infos.MethodCandidateInfo$4.compute(MethodCandidateInfo.java:381)
    at com.intellij.psi.infos.MethodCandidateInfo.computeForOverloadedCandidate(MethodCandidateInfo.java:251)
    at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:381)
    at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:360)
    at com.intellij.psi.infos.MethodCandidateInfo.getSubstitutor(MethodCandidateInfo.java:295)
    at com.intellij.psi.scope.conflictResolvers.DuplicateConflictResolver.resolveConflict(DuplicateConflictResolver.java:51)
    at com.intellij.psi.scope.processor.ConflictFilterProcessor.getResult(ConflictFilterProcessor.java:91)
    at com.intellij.psi.scope.processor.MethodCandidatesProcessor.getCandidates(MethodCandidatesProcessor.java:153)
    at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.getReferencedMethodCandidates(PsiResolveHelperImpl.java:148)
    at com.intellij.codeInsight.ExpectedTypesProvider$MyParentVisitor.visitExpressionList(ExpectedTypesProvider.java:564)
    at com.intellij.psi.impl.source.tree.java.PsiExpressionListImpl.accept(PsiExpressionListImpl.java:142)
    at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:151)
    at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:120)
    at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:115)
    at com.intellij.codeInsight.folding.impl.JavaFoldingBuilder.shouldShowExplicitLambdaType(JavaFoldingBuilder.java:46)
    at com.intellij.codeInsight.folding.impl.JavaFoldingBuilderBase.getOptionalLambdaType(JavaFoldingBuilderBase.java:415)
    at com.intellij.codeInsight.folding.impl.JavaFoldingBuilderBase.addClosureFolding(JavaFoldingBuilderBase.java:841)
    at com.intellij.codeInsight.folding.impl.JavaFoldingBuilderBase.access$000(JavaFoldingBuilderBase.java:60)
    at com.intellij.codeInsight.folding.impl.JavaFoldingBuilderBase$1.visitClass(JavaFoldingBuilderBase.java:749)
    at com.intellij.psi.JavaElementVisitor.visitAnonymousClass(JavaElementVisitor.java:23)
    at com.intellij.psi.impl.source.PsiAnonymousClassImpl.accept(PsiAnonymousClassImpl.java:168)
    at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:64)
    at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:26)
    at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
    at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
    at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:73)
    at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitElement(JavaRecursiveElementWalkingVisitor.java:41)
    at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:67)
    at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:202)
    at com.intellij.codeInsight.folding.impl.JavaFoldingBuilderBase.addCodeBlockFolds(JavaFoldingBuilderBase.java:746)
    at com.intellij.codeInsight.folding.impl.JavaFoldingBuilderBase.addElementsToFold(JavaFoldingBuilderBase.java:571)
    at com.intellij.codeInsight.folding.impl.JavaFoldingBuilderBase.buildLanguageFoldRegions(JavaFoldingBuilderBase.java:510)
    at com.intellij.lang.folding.CustomFoldingBuilder.buildFoldRegions(CustomFoldingBuilder.java:59)
    at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
    at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:60)
    at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:83)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:243)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:229)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.getUpdateResult(FoldingUpdate.java:116)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.access$000(FoldingUpdate.java:55)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate$1.compute(FoldingUpdate.java:104)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate$1.compute(FoldingUpdate.java:99)
    at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:53)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
    at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:43)
    at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:97)
    at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:98)
    at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegions(CodeFoldingManagerImpl.java:335)
    at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:320)
    at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:434)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1034)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:427)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Comment by ldub** [comment]
old.
