### ISSUE TITLE
java.lang.IllegalStateException: agent injection not supported on this platform due to unknown reason

### ISSUE THREAD

**Issue by lssilva** [mplushnikov/lombok-intellij-plugin#305]
The plugin keeps crashing with different exceptions this is one of them:

`java.lang.IllegalStateException: agent injection not supported on this platform due to unknown reason
	at de.plushnikov.intellij.lombok.patcher.inject.LiveInjector.injectInternal(LiveInjector.java:114)
	at de.plushnikov.intellij.lombok.patcher.inject.LiveInjector.inject(LiveInjector.java:101)
	at de.plushnikov.intellij.plugin.LombokPluginApplicationComponent.injectAgent(LombokPluginApplicationComponent.java:109)
	at de.plushnikov.intellij.plugin.LombokPluginApplicationComponent.initComponent(LombokPluginApplicationComponent.java:78)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:518)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:436)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:384)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:62)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:358)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.UnsatisfiedLinkError: no attach in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.tools.attach.LinuxVirtualMachine.<clinit>(LinuxVirtualMachine.java:342)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	at de.plushnikov.intellij.lombok.patcher.inject.LiveInjector.injectInternal(LiveInjector.java:111)
	... 36 more
`

**Comment by Janmm14** [comment]
Which jvm are you using?

**Comment by lssilva** [comment]
Oracle JDK 
javac 1.8.0_92

**Comment by AlexejK** [comment]
Agent injection should not be needed for 2016.2. What patching does is rewrite byte-code of one class you support some of the functionality for the sake of back-port. But this is only useful on IDEA < 2016.1 and we are making sure that this specific part only runs on older IDEs. However the error seem to do more with attaching of the agent, which is a bit weird.

Did you by any chance tick-in "Patch" option under lombok settings?

Linux is a very generic OS :). Any specific distro? Do you somehow constain what IDEA is able to do with itself?

**Comment by lssilva** [comment]
I can no longer reproduce the error with the latest JDK / Idea
