### ISSUE TITLE
Write access is allowed from write-safe contexts only

### ISSUE THREAD

**Issue by relgames** [mplushnikov/lombok-intellij-plugin#308]
Latest IntelliJ IDEA 2016.3 Build #IU-163.7743.37 shows an error due to Lombok plugin:

```
Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities={ModalityState.NON_MODAL=true}
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:246)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAllDocuments(PsiDocumentManagerBase.java:219)
	at de.plushnikov.intellij.plugin.action.delombok.BaseDelombokAction.isValidForFile(BaseDelombokAction.java:205)
	at de.plushnikov.intellij.plugin.action.delombok.BaseDelombokAction.update(BaseDelombokAction.java:135)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:122)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.updateGroupChild(Utils.java:265)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:239)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:205)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.c(ActionMenu.java:324)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:51)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:278)
	at javax.swing.JMenu.fireMenuSelected(JMenu.java:1038)
	at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1118)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
	at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:232)
	at javax.swing.JMenu.setSelected(JMenu.java:305)
	at com.apple.laf.ScreenMenu$2.run(ScreenMenu.java:135)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by AlexejK** [comment]
What operation did you try to perform?
Looks like De-lombok?

**Comment by relgames** [comment]
I tried to open github.com/akka/akka in IDEA - it does not use Lombok at all.

**Comment by AlexejK** [comment]
Yes, but it's also a Scala project, not Java one.
You might want to disable Lombok plugin for this.

We can ofc try to do better and figure out how to detect projects that use Java and ignore it on e.g Scala ones. I haven't had an issue with Groovy projects however, so I wonder why Scala behaves differently. At the same time we've had multiple Scala+Gradle projects (mainly for Gatling tests) that did not cause any issue whatsoever with the plugin.

**Comment by relgames** [comment]
How can I disable Lombok selectively? I also have projects with Lombok.
What about trying looking for a marker class in the current project classpath? If there is no Lombok in classpath then it's not a Lombok project.

**Comment by jasonjoneski** [comment]
I have a Java only project, and am getting the same exception on startup of the IDE.

**Comment by mplushnikov** [comment]
This problem should be fixed in the next release of the plugin (>=0.14)
Please verify it with current [snapshot build ](https://github.com/mplushnikov/lombok-intellij-plugin/releases/tag/eap-0.14.1)

**Comment by beedaan** [comment]
I have verified the bug is fixed in the current snapshot build.  However, the current snapshot build breaks all lombak generated getters and setters.  I will open a separate issue for further discussion and investigation

![screen shot 2016-12-01 at 8 15 53 am](https://cloud.githubusercontent.com/assets/884240/20801685/8a3260cc-b79e-11e6-8710-49ec8bdddeb3.png)

**Comment by jkolobok** [comment]
Do you plan to release it any time soon? it's a bit annoying to see this exception :(

**Comment by AlexejK** [comment]
You can install it manually by downloading from the Releases page and then "Install plugin from file" in IntelliJ. You will still be able to get new plugin updates when they are released automatically.
