### ISSUE TITLE
StackOverflowError in compile state

### ISSUE THREAD

**Issue by Ivashchyk** [mplushnikov/lombok-intellij-plugin#310]
When I'm trying to compile my lombok-based project in IntellijIDEA I get StackOverflowError. Data from IDEA log:

java.lang.RuntimeException: java.lang.StackOverflowError
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:166)
	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:423)
	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:290)
	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:197)
	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:168)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1237)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:911)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:983)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:870)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:696)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:387)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:194)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:294)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StackOverflowError
	at lombok.javac.JavacAST.drill(JavacAST.java:327)
	at lombok.javac.JavacAST.buildStatementOrExpression(JavacAST.java:321)
	at lombok.javac.JavacAST.buildTree(JavacAST.java:180)
	at lombok.javac.JavacAST.buildTree(JavacAST.java:64)
	at lombok.core.AST.buildWithField0(AST.java:384)
	at lombok.core.AST.buildWithField(AST.java:282)
	at lombok.javac.JavacAST.drill(JavacAST.java:327)
	at lombok.javac.JavacAST.buildStatementOrExpression(JavacAST.java:321)
	at lombok.javac.JavacAST.buildTree(JavacAST.java:180)
	at lombok.javac.JavacAST.buildTree(JavacAST.java:64)
	at lombok.core.AST.buildWithField0(AST.java:384)
	at lombok.core.AST.buildWithField(AST.java:282)
	at lombok.javac.JavacAST.drill(JavacAST.java:327)
	at lombok.javac.JavacAST.buildStatementOrExpression(JavacAST.java:321)
	at lombok.javac.JavacAST.buildTree(JavacAST.java:180)
	at lombok.javac.JavacAST.buildTree(JavacAST.java:64)
	at lombok.core.AST.buildWithField0(AST.java:384)
	at lombok.core.AST.buildWithField(AST.java:282)
	at lombok.javac.JavacAST.drill(JavacAST.java:327)
	at lombok.javac.JavacAST.buildStatementOrExpression(JavacAST.java:321)
	at lombok.javac.JavacAST.buildTree(JavacAST.java:180)
	at lombok.javac.JavacAST.buildTree(JavacAST.java:64)
	at lombok.core.AST.buildWithField0(AST.java:384)
...

The same issue on PC of my colleague.

IntelliJ IDEA 2016.2.5
Build #IU-162.2228.15, built on October 14, 2016
Licensed to Anton Ivashchyk
Subscription is active until May 17, 2017
JRE: 1.8.0_112-release-287-b2 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

OS: Windows 10

My contact email: anton.ivashchyk@gmail.com

Please fix.

**Comment by Janmm14** [comment]
Looks like an issue of lombok itself on the first glance.

**Comment by mplushnikov** [comment]
Hello Ivashchyk, I apologize, but this looks like an issue in lombok itself. Please look on existing bugs for lombok project like [#1171](https://github.com/rzwitserloot/lombok/issues/1171) and [#1118](https://github.com/rzwitserloot/lombok/issues/1118).
I can't do anything here.
