### ISSUE TITLE
Wrong dependency type: class de.plushnikov.intellij.plugin.psi.LombokLightParameter

### ISSUE THREAD

**Issue by dovchinnikov** [mplushnikov/lombok-intellij-plugin#358]
IDEA build 163.12024

```
Wrong dependency type: class de.plushnikov.intellij.plugin.psi.LombokLightParameter

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.util.CachedValueBase.getTimeStamp(CachedValueBase.java:177)
	at com.intellij.psi.impl.PsiCachedValue.getTimeStamp(PsiCachedValue.java:106)
	at com.intellij.util.CachedValueBase.isDependencyOutOfDate(CachedValueBase.java:138)
	at com.intellij.psi.impl.PsiCachedValue.isDependencyOutOfDate(PsiCachedValue.java:79)
	at com.intellij.util.CachedValueBase.isUpToDate(CachedValueBase.java:128)
	at com.intellij.psi.impl.PsiCachedValue.isUpToDate(PsiCachedValue.java:70)
	at com.intellij.util.CachedValueBase.getUpToDateOrNull(CachedValueBase.java:107)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:214)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:130)
	at com.intellij.codeInsight.AnnotationUtil.getSuperAnnotationOwners(AnnotationUtil.java:199)
	at com.intellij.codeInsight.NullableNotNullManager.findNullabilityAnnotationWithDefault(NullableNotNullManager.java:223)
	at com.intellij.codeInsight.NullableNotNullManager.getNotNullAnnotation(NullableNotNullManager.java:135)
	at com.intellij.codeInspection.dataFlow.DfaPsiUtil.isNotNullLocally(DfaPsiUtil.java:158)
	at com.intellij.codeInspection.dataFlow.DfaPsiUtil.getElementNullability(DfaPsiUtil.java:99)
	at com.intellij.codeInspection.dataFlow.value.DfaVariableValue.calcInherentNullability(DfaVariableValue.java:174)
	at com.intellij.codeInspection.dataFlow.value.DfaVariableValue.getInherentNullability(DfaVariableValue.java:168)
	at com.intellij.codeInspection.dataFlow.DfaVariableState.<init>(DfaVariableState.java:50)
	at com.intellij.codeInspection.dataFlow.DfaMemoryStateImpl.createVariableState(DfaMemoryStateImpl.java:956)
	at com.intellij.codeInspection.dataFlow.DfaMemoryStateImpl.getVariableState(DfaMemoryStateImpl.java:932)
	at com.intellij.codeInspection.dataFlow.DfaMemoryStateImpl.isNotNull(DfaMemoryStateImpl.java:557)
	at com.intellij.codeInspection.dataFlow.DfaMemoryStateImpl.applyEquivalenceRelation(DfaMemoryStateImpl.java:742)
	at com.intellij.codeInspection.dataFlow.DfaMemoryStateImpl.applyRelationCondition(DfaMemoryStateImpl.java:711)
	at com.intellij.codeInspection.dataFlow.DfaMemoryStateImpl.applyCondition(DfaMemoryStateImpl.java:651)
	at com.intellij.codeInspection.dataFlow.StandardInstructionVisitor.handleRelationBinop(StandardInstructionVisitor.java:432)
	at com.intellij.codeInspection.dataFlow.StandardInstructionVisitor.visitBinop(StandardInstructionVisitor.java:389)
	at com.intellij.codeInspection.dataFlow.instructions.BinopInstruction.accept(BinopInstruction.java:53)
	at com.intellij.codeInspection.dataFlow.DataFlowRunner.acceptInstruction(DataFlowRunner.java:282)
	at com.intellij.codeInspection.dataFlow.DataFlowRunner.analyzeMethod(DataFlowRunner.java:186)
	at com.intellij.codeInspection.dataFlow.DataFlowInspectionBase.analyzeDfaWithNestedClosures(DataFlowInspectionBase.java:211)
	at com.intellij.codeInspection.dataFlow.DataFlowInspectionBase.analyzeCodeBlock(DataFlowInspectionBase.java:167)
	at com.intellij.codeInspection.dataFlow.DataFlowInspectionBase.access$000(DataFlowInspectionBase.java:63)
	at com.intellij.codeInspection.dataFlow.DataFlowInspectionBase$1.visitMethod(DataFlowInspectionBase.java:107)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:284)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:280)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:249)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$0(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by mplushnikov** [comment]
Closed as not reproducible
