### ISSUE TITLE
Yet another Intellij Issue: Recursive conflict resolution for:PsiMethod:valueOf; 

### ISSUE THREAD

**Issue by thelaurg** [mplushnikov/lombok-intellij-plugin#372]
**Intellij IDEA 2016.3.5**

Recursive conflict resolution for:PsiMethod:valueOf; (prod.getPIntellijIdeaRulezzz; file=PsiFile:Enum.class

```Recursive conflict resolution for:PsiMethod:valueOf; (prod.getPIntellijIdeaRulezzz; file=PsiFile:Enum.class
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.psi.scope.conflictResolvers.JavaMethodsConflictResolver.resolveConflict(JavaMethodsConflictResolver.java:77)
	at com.intellij.psi.scope.processor.ConflictFilterProcessor.getResult(ConflictFilterProcessor.java:91)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolveToMethod(PsiReferenceExpressionImpl.java:305)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolve(PsiReferenceExpressionImpl.java:285)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:61)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:197)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:186)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
	at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:754)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:743)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:346)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:161)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:155)
	at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:87)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.getType(PsiMethodCallExpressionImpl.java:55)
	at de.plushnikov.intellij.plugin.processor.ValProcessor$1.compute(ValProcessor.java:160)
	at de.plushnikov.intellij.plugin.processor.ValProcessor$1.compute(ValProcessor.java:157)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at de.plushnikov.intellij.plugin.processor.ValProcessor.processLocalVariableInitializer(ValProcessor.java:157)
	at de.plushnikov.intellij.plugin.processor.ValProcessor.inferType(ValProcessor.java:141)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.inferType(LombokAugmentProvider.java:95)
	at com.intellij.psi.augment.PsiAugmentProvider$2.process(PsiAugmentProvider.java:110)
	at com.intellij.psi.augment.PsiAugmentProvider$2.process(PsiAugmentProvider.java:107)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:146)
	at com.intellij.psi.augment.PsiAugmentProvider.getInferredType(PsiAugmentProvider.java:107)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.calculateType(PsiTypeElementImpl.java:72)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.access$000(PsiTypeElementImpl.java:39)
	at com.intellij.psi.impl.source.PsiTypeElementImpl$1.compute(PsiTypeElementImpl.java:66)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:137)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:84)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:133)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.getType(PsiTypeElementImpl.java:62)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:50)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:46)
	at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.getType(PsiLocalVariableImpl.java:98)
	at com.intellij.psi.util.PsiTypesUtil.getExpectedTypeByParent(PsiTypesUtil.java:205)
	at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferMethodTypeParameterFromParent(PsiOldInferenceHelper.java:677)
	at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferMethodTypeParameterFromParent(PsiOldInferenceHelper.java:423)
	at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferTypeArguments(PsiOldInferenceHelper.java:282)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.inferTypeArguments(PsiResolveHelperImpl.java:190)
	at com.intellij.psi.infos.MethodCandidateInfo$4.compute(MethodCandidateInfo.java:418)
	at com.intellij.psi.infos.MethodCandidateInfo$4.compute(MethodCandidateInfo.java:403)
	at com.intellij.psi.infos.MethodCandidateInfo.computeForOverloadedCandidate(MethodCandidateInfo.java:273)
	at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:403)
	at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:382)
	at com.intellij.psi.infos.MethodCandidateInfo.getSubstitutor(MethodCandidateInfo.java:317)
	at com.intellij.psi.scope.conflictResolvers.DuplicateConflictResolver.resolveConflict(DuplicateConflictResolver.java:51)
	at com.intellij.psi.scope.processor.ConflictFilterProcessor.getResult(ConflictFilterProcessor.java:91)
	at com.intellij.psi.scope.processor.MethodCandidatesProcessor.getCandidates(MethodCandidatesProcessor.java:153)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.getReferencedMethodCandidates(PsiResolveHelperImpl.java:148)
	at com.intellij.codeInsight.ExpectedTypesProvider$MyParentVisitor.visitExpressionList(ExpectedTypesProvider.java:585)
	at com.intellij.psi.impl.source.tree.java.PsiExpressionListImpl.accept(PsiExpressionListImpl.java:142)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:155)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:124)
	at com.intellij.codeInsight.completion.JavaSmartCompletionContributor.getExpectedTypes(JavaSmartCompletionContributor.java:275)
	at com.intellij.codeInsight.completion.JavaSmartCompletionContributor.getExpectedTypes(JavaSmartCompletionContributor.java:252)
	at com.intellij.codeInsight.completion.JavaCompletionSorting.addJavaSorting(JavaCompletionSorting.java:56)
	at com.intellij.codeInsight.completion.JavaCompletionContributor.fillCompletionVariants(JavaCompletionContributor.java:215)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
	at com.intellij.codeInsight.completion.JavaNoVariantsDelegator.fillCompletionVariants(JavaNoVariantsDelegator.java:65)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:132)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:125)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:773)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:91)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:755)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by ealasu** [comment]
Seeing a similar error.
IntelliJ IDEA 2017.1.1
Build #IU-171.4073.35, built on April 6, 2017

```
Recursive conflict resolution for:PsiMethod:readTree; (rIntellijIdeaRulezzz); file=PsiFile:ObjectMapper.class
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.psi.scope.conflictResolvers.JavaMethodsConflictResolver.resolveConflict(JavaMethodsConflictResolver.java:76)
	at com.intellij.psi.scope.processor.ConflictFilterProcessor.getResult(ConflictFilterProcessor.java:91)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolveToMethod(PsiReferenceExpressionImpl.java:311)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolve(PsiReferenceExpressionImpl.java:284)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:60)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:196)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:185)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:185)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:184)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:721)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:713)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:352)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:160)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:154)
	at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:89)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.getType(PsiMethodCallExpressionImpl.java:54)
	at de.plushnikov.intellij.plugin.processor.ValProcessor$1.compute(ValProcessor.java:160)
	at de.plushnikov.intellij.plugin.processor.ValProcessor$1.compute(ValProcessor.java:157)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at de.plushnikov.intellij.plugin.processor.ValProcessor.processLocalVariableInitializer(ValProcessor.java:157)
	at de.plushnikov.intellij.plugin.processor.ValProcessor.inferType(ValProcessor.java:141)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.inferType(LombokAugmentProvider.java:95)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$getInferredType$1(PsiAugmentProvider.java:105)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:137)
	at com.intellij.psi.augment.PsiAugmentProvider.getInferredType(PsiAugmentProvider.java:104)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.calculateType(PsiTypeElementImpl.java:69)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.lambda$getType$0(PsiTypeElementImpl.java:65)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:141)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:137)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.getType(PsiTypeElementImpl.java:65)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:50)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:46)
	at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.getType(PsiLocalVariableImpl.java:98)
	at com.intellij.psi.util.PsiTypesUtil.getExpectedTypeByParent(PsiTypesUtil.java:212)
	at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferMethodTypeParameterFromParent(PsiOldInferenceHelper.java:678)
	at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferMethodTypeParameterFromParent(PsiOldInferenceHelper.java:424)
	at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferTypeArguments(PsiOldInferenceHelper.java:283)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.inferTypeArguments(PsiResolveHelperImpl.java:190)
	at com.intellij.psi.infos.MethodCandidateInfo.lambda$inferTypeArguments$3(MethodCandidateInfo.java:399)
	at com.intellij.psi.infos.MethodCandidateInfo.computeForOverloadedCandidate(MethodCandidateInfo.java:265)
	at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:386)
	at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:365)
	at com.intellij.psi.infos.MethodCandidateInfo.getSubstitutor(MethodCandidateInfo.java:305)
	at com.intellij.psi.scope.conflictResolvers.DuplicateConflictResolver.resolveConflict(DuplicateConflictResolver.java:51)
	at com.intellij.psi.scope.processor.ConflictFilterProcessor.getResult(ConflictFilterProcessor.java:91)
	at com.intellij.psi.scope.processor.MethodCandidatesProcessor.getCandidates(MethodCandidatesProcessor.java:153)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.getReferencedMethodCandidates(PsiResolveHelperImpl.java:148)
	at com.intellij.codeInsight.ExpectedTypesProvider$MyParentVisitor.visitExpressionList(ExpectedTypesProvider.java:584)
	at com.intellij.psi.impl.source.tree.java.PsiExpressionListImpl.accept(PsiExpressionListImpl.java:142)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:153)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:122)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:117)
	at com.intellij.psi.filters.getters.ExpectedTypesGetter.getExpectedTypes(ExpectedTypesGetter.java:41)
	at com.intellij.codeInsight.completion.JavaCompletionContributor.b(JavaCompletionContributor.java:709)
	at com.intellij.codeInsight.completion.JavaCompletionContributor.advertise(JavaCompletionContributor.java:605)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.scheduleAdvertising(CompletionProgressIndicator.java:295)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:108)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.psi.scope.conflictResolvers.JavaMethodsConflictResolver.resolveConflict(JavaMethodsConflictResolver.java:76)
	at com.intellij.psi.scope.processor.ConflictFilterProcessor.getResult(ConflictFilterProcessor.java:91)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolveToMethod(PsiReferenceExpressionImpl.java:311)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolve(PsiReferenceExpressionImpl.java:284)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:60)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:196)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:185)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:185)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:184)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:721)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:713)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:352)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:160)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:154)
	at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:89)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.getType(PsiMethodCallExpressionImpl.java:54)
	at de.plushnikov.intellij.plugin.processor.ValProcessor$1.compute(ValProcessor.java:160)
	at de.plushnikov.intellij.plugin.processor.ValProcessor$1.compute(ValProcessor.java:157)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at de.plushnikov.intellij.plugin.processor.ValProcessor.processLocalVariableInitializer(ValProcessor.java:157)
	at de.plushnikov.intellij.plugin.processor.ValProcessor.inferType(ValProcessor.java:141)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.inferType(LombokAugmentProvider.java:95)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$getInferredType$1(PsiAugmentProvider.java:105)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:137)
	at com.intellij.psi.augment.PsiAugmentProvider.getInferredType(PsiAugmentProvider.java:104)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.calculateType(PsiTypeElementImpl.java:69)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.lambda$getType$0(PsiTypeElementImpl.java:65)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:141)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:137)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.getType(PsiTypeElementImpl.java:65)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:50)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:46)
	at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.getType(PsiLocalVariableImpl.java:98)
	at com.intellij.psi.util.PsiTypesUtil.getExpectedTypeByParent(PsiTypesUtil.java:212)
	at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferMethodTypeParameterFromParent(PsiOldInferenceHelper.java:678)
	at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferMethodTypeParameterFromParent(PsiOldInferenceHelper.java:424)
	at com.intellij.psi.impl.source.resolve.PsiOldInferenceHelper.inferTypeArguments(PsiOldInferenceHelper.java:283)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.inferTypeArguments(PsiResolveHelperImpl.java:190)
	at com.intellij.psi.infos.MethodCandidateInfo.lambda$inferTypeArguments$3(MethodCandidateInfo.java:399)
	at com.intellij.psi.infos.MethodCandidateInfo.computeForOverloadedCandidate(MethodCandidateInfo.java:265)
	at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:386)
	at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:365)
	at com.intellij.psi.infos.MethodCandidateInfo.getSubstitutor(MethodCandidateInfo.java:305)
	at com.intellij.psi.scope.conflictResolvers.DuplicateConflictResolver.resolveConflict(DuplicateConflictResolver.java:51)
	at com.intellij.psi.scope.processor.ConflictFilterProcessor.getResult(ConflictFilterProcessor.java:91)
	at com.intellij.psi.scope.processor.MethodCandidatesProcessor.getCandidates(MethodCandidatesProcessor.java:153)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.getReferencedMethodCandidates(PsiResolveHelperImpl.java:148)
	at com.intellij.codeInsight.ExpectedTypesProvider$MyParentVisitor.visitExpressionList(ExpectedTypesProvider.java:584)
	at com.intellij.psi.impl.source.tree.java.PsiExpressionListImpl.accept(PsiExpressionListImpl.java:142)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:153)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:122)
	at com.intellij.codeInsight.ExpectedTypesProvider.getExpectedTypes(ExpectedTypesProvider.java:117)
	at com.intellij.psi.filters.getters.ExpectedTypesGetter.getExpectedTypes(ExpectedTypesGetter.java:41)
	at com.intellij.codeInsight.completion.JavaCompletionContributor.b(JavaCompletionContributor.java:709)
	at com.intellij.codeInsight.completion.JavaCompletionContributor.advertise(JavaCompletionContributor.java:605)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.scheduleAdvertising(CompletionProgressIndicator.java:295)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:108)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by AlexejK** [comment]
Any sample projects that exhibit the issue?
