### ISSUE TITLE
Lombok plugin threw an uncaught exception NoClassDefFoundError com.intellij.util.indexing.IndexId

### ISSUE THREAD

**Issue by mathroule** [mplushnikov/lombok-intellij-plugin#417]
### Short description
Lombok plugin threw an uncaught exception, and Intellij could not load it correctly. While the plugin is enabled, Intellij could not perform auto complete.

### Version information
 * **IDEA Version:** Android Studio 3.0 Beta 5 Build #AI-171.4316950, built on September 5, 2017
 * **JRE Version:** 1.8.0_152-release-915-b01 amd64
 * **JVM Version:** OpenJDK 64-Bit Server VM by JetBrains s.r.o
 * **OS Type & Version:** Windows 10 10.0
 * **Lombok Plugin Version:** 0.15.17.1
 * **Lombok Dependency Version:** 1.16.18

### Steps to reproduce
 1. Update Lombok plugin to last version
 2. Restart Android Studio
 3. Plugin crash on start up

### Stacktrace
```
com/intellij/util/indexing/IndexId
java.lang.NoClassDefFoundError: com/intellij/util/indexing/IndexId
	at de.plushnikov.intellij.plugin.lombokconfig.ConfigDiscovery.readProperty(ConfigDiscovery.java:153)
	at de.plushnikov.intellij.plugin.lombokconfig.ConfigDiscovery.discoverProperty(ConfigDiscovery.java:119)
	at de.plushnikov.intellij.plugin.lombokconfig.ConfigDiscovery.getStringLombokConfigProperty(ConfigDiscovery.java:37)
	at de.plushnikov.intellij.plugin.lombokconfig.ConfigDiscovery.getBooleanLombokConfigProperty(ConfigDiscovery.java:44)
	at de.plushnikov.intellij.plugin.processor.field.AccessorsInfo.buildAccessorsInfo(AccessorsInfo.java:84)
	at de.plushnikov.intellij.plugin.processor.field.AccessorsInfo.build(AccessorsInfo.java:62)
	at de.plushnikov.intellij.plugin.processor.field.AccessorsInfo.build(AccessorsInfo.java:47)
	at de.plushnikov.intellij.plugin.processor.field.SetterFieldProcessor.getAllSetterNames(SetterFieldProcessor.java:114)
	at de.plushnikov.intellij.plugin.processor.field.SetterFieldProcessor.validateExistingMethods(SetterFieldProcessor.java:90)
	at de.plushnikov.intellij.plugin.processor.field.SetterFieldProcessor.validate(SetterFieldProcessor.java:58)
	at de.plushnikov.intellij.plugin.processor.field.AbstractFieldProcessor.process(AbstractFieldProcessor.java:44)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:176)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:141)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:137)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:127)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$collectAugments$0(PsiAugmentProvider.java:93)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:137)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:92)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getAllMethods(ClassInnerStuffCache.java:132)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.lambda$getMethods$2(ClassInnerStuffCache.java:66)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:141)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:137)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:65)
	at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:297)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClassNotCached(PsiClassImplUtil.java:683)
	at com.intellij.psi.impl.PsiClassImplUtil.access$200(PsiClassImplUtil.java:63)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.create(PsiClassImplUtil.java:402)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.create(PsiClassImplUtil.java:350)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:57)
	at com.intellij.psi.impl.PsiClassImplUtil.getMap(PsiClassImplUtil.java:208)
	at com.intellij.psi.impl.PsiClassImplUtil.findByMap(PsiClassImplUtil.java:154)
	at com.intellij.psi.impl.PsiClassImplUtil.findMethodsByName(PsiClassImplUtil.java:97)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.findMethodsByName(ClassInnerStuffCache.java:88)
	at com.intellij.psi.impl.source.PsiClassImpl.findMethodsByName(PsiClassImpl.java:379)
	at com.intellij.psi.util.PsiMethodUtil.findMainMethod(PsiMethodUtil.java:45)
	at com.intellij.psi.util.PsiMethodUtil.findMainInClass(PsiMethodUtil.java:87)
	at com.intellij.execution.application.ApplicationRunLineMarkerProvider.getInfo(ApplicationRunLineMarkerProvider.java:41)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:58)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:186)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1156)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.indexing.IndexId PluginClassLoader[Lombook Plugin, 0.15.17.1]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 69 more


java.lang.NoClassDefFoundError: com/intellij/util/indexing/IndexId
	at de.plushnikov.intellij.plugin.lombokconfig.ConfigDiscovery.readProperty(ConfigDiscovery.java:153)
	at de.plushnikov.intellij.plugin.lombokconfig.ConfigDiscovery.discoverProperty(ConfigDiscovery.java:119)
	at de.plushnikov.intellij.plugin.lombokconfig.ConfigDiscovery.getStringLombokConfigProperty(ConfigDiscovery.java:37)
	at de.plushnikov.intellij.plugin.lombokconfig.ConfigDiscovery.getBooleanLombokConfigProperty(ConfigDiscovery.java:44)
	at de.plushnikov.intellij.plugin.processor.field.AccessorsInfo.buildAccessorsInfo(AccessorsInfo.java:84)
	at de.plushnikov.intellij.plugin.processor.field.AccessorsInfo.build(AccessorsInfo.java:62)
	at de.plushnikov.intellij.plugin.processor.field.AccessorsInfo.build(AccessorsInfo.java:47)
	at de.plushnikov.intellij.plugin.processor.field.SetterFieldProcessor.getAllSetterNames(SetterFieldProcessor.java:114)
	at de.plushnikov.intellij.plugin.processor.field.SetterFieldProcessor.validateExistingMethods(SetterFieldProcessor.java:90)
	at de.plushnikov.intellij.plugin.processor.field.SetterFieldProcessor.validate(SetterFieldProcessor.java:58)
	at de.plushnikov.intellij.plugin.processor.field.AbstractFieldProcessor.process(AbstractFieldProcessor.java:44)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:176)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:141)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:137)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:127)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$collectAugments$0(PsiAugmentProvider.java:93)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:137)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:92)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getAllMethods(ClassInnerStuffCache.java:132)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.lambda$getMethods$2(ClassInnerStuffCache.java:66)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:141)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:137)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:65)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethodsMap(ClassInnerStuffCache.java:160)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.lambda$findMethodsByName$5(ClassInnerStuffCache.java:91)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:141)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:137)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.findMethodsByName(ClassInnerStuffCache.java:90)
	at com.intellij.psi.impl.source.PsiClassImpl.findMethodsByName(PsiClassImpl.java:379)
	at com.intellij.execution.junit.JUnitUtil.findSuiteMethod(JUnitUtil.java:376)
	at com.intellij.execution.junit.JUnit3Framework.isTestClass(JUnit3Framework.java:82)
	at com.intellij.testIntegration.JavaTestFramework.isTestClass(JavaTestFramework.java:63)
	at com.intellij.codeInsight.TestFrameworksImpl.isTestClass(TestFrameworksImpl.java:38)
	at com.intellij.psi.impl.ElementPresentationUtil.getClassKindImpl(ElementPresentationUtil.java:137)
	at com.intellij.psi.impl.ElementPresentationUtil.lambda$getClassKind$0(ElementPresentationUtil.java:106)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.impl.ElementPresentationUtil.getClassKind(ElementPresentationUtil.java:109)
	at com.intellij.psi.impl.PsiClassImplUtil.lambda$static$0(PsiClassImplUtil.java:259)
	at com.intellij.ui.IconDeferrerImpl.deferImpl(IconDeferrerImpl.java:78)
	at com.intellij.ui.IconDeferrerImpl.defer(IconDeferrerImpl.java:68)
	at com.intellij.psi.impl.PsiClassImplUtil.getClassIcon(PsiClassImplUtil.java:280)
	at com.intellij.psi.impl.PsiClassImplUtil.getClassIcon(PsiClassImplUtil.java:267)
	at com.intellij.psi.impl.source.PsiClassImpl.getElementIcon(PsiClassImpl.java:633)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:122)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:59)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:275)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:161)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:111)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1156)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$2(ProgressIndicatorUtils.java:147)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:145)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:160)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.indexing.IndexId PluginClassLoader[Lombook Plugin, 0.15.17.1]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 83 more
```

**Comment by mplushnikov** [comment]
Please update to new version of plugin: 0.15.17.2 (released today, at 9 o'clock)
duplicate #415

**Comment by mathroule** [comment]
Sorry for the duplicate, thanks for the quick update ;)
