### ISSUE TITLE
Exception in IDEA 2017.3

### ISSUE THREAD

**Issue by chrkv** [mplushnikov/lombok-intellij-plugin#418]
```

Short name 'Convert2Diamond' is not unique
class 'de.plushnikov.intellij.plugin.inspection.LombokExplicitTypeCanBeDiamondInspection' in PluginDescriptor[name='Lombok Plugin', classpath='C:\Users\jack1\.IntelliJIdea2017.3\config\plugins\lombok-plugin']
and
class'com.intellij.codeInspection.ExplicitTypeCanBeDiamondInspection' in PluginDescriptor[name='IDEA CORE', classpath='C:\JetBrains\apps\IDEA-U\ch-0\173.2099.14\lib\resources.jar']
conflict

java.lang.Throwable: Short name 'Convert2Diamond' is not unique
class 'de.plushnikov.intellij.plugin.inspection.LombokExplicitTypeCanBeDiamondInspection' in PluginDescriptor[name='Lombok Plugin', classpath='C:\Users\jack1\.IntelliJIdea2017.3\config\plugins\lombok-plugin']
and
class'com.intellij.codeInspection.ExplicitTypeCanBeDiamondInspection' in PluginDescriptor[name='IDEA CORE', classpath='C:\JetBrains\apps\IDEA-U\ch-0\173.2099.14\lib\resources.jar']
conflict
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.checkForDuplicateShortName(InspectionToolRegistrar.java:80)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.ensureInitialized(InspectionToolRegistrar.java:58)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:123)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:34)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:49)
	at com.intellij.openapi.application.Preloader.lambda$null$0(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:171)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:158)
	at com.intellij.openapi.application.Preloader.lambda$initComponent$1(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by mplushnikov** [comment]
Hello chrkv,
please verify plugin version you are using. The last version (015.17.2) of plugin already contains a fix for it.

**Comment by mplushnikov** [comment]
duplicate #359
