### ISSUE TITLE
com.intellij.util.IncorrectOperationException: Incorrect method 'public static null.CacheKeyBuilder<C> builder(){  }' with Lombok Plugin 0.15.17.2 and IntelliJ 173.3531.6

### ISSUE THREAD

**Issue by ewirch** [mplushnikov/lombok-intellij-plugin#424]
Incorrect method 'public static null.CacheKeyBuilder<C> builder(){  }'
    com.intellij.util.IncorrectOperationException: Incorrect method 'public static null.CacheKeyBuilder<C> builder(){  }'
    	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.newException(PsiJavaParserFacadeImpl.java:426)
    	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createMethodFromText(PsiJavaParserFacadeImpl.java:231)
    	at com.intellij.psi.impl.PsiElementFactoryImpl.createMethodFromText(PsiElementFactoryImpl.java:758)
    	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createMethodFromText(PsiJavaParserFacadeImpl.java:240)
    	at de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder.rebuildMethodFromString(LombokLightMethodBuilder.java:193)
    	at de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder.getOrCreateMyPsiMethod(LombokLightMethodBuilder.java:206)
    	at de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder.getChildren(LombokLightMethodBuilder.java:214)
    	at com.intellij.psi.impl.PsiElementBase.getFirstChild(PsiElementBase.java:43)
    	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:49)
    	at com.intellij.psi.PsiWalkingState$PsiTreeGuide.getFirstChild(PsiWalkingState.java:31)
    	at com.intellij.util.WalkingState.next(WalkingState.java:73)
    	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:61)
    	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
    	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
    	at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitElement(JavaRecursiveElementWalkingVisitor.java:41)
    	at com.intellij.psi.JavaElementVisitor.visitMethod(JavaElementVisitor.java:178)
    	at com.intellij.psi.impl.light.LightMethodBuilder.accept(LightMethodBuilder.java:318)
    	at com.siyeh.ig.classmetrics.ClassComplexityInspection$ClassComplexityVisitor.a(ClassComplexityInspection.java:102)
    	at com.siyeh.ig.classmetrics.ClassComplexityInspection$ClassComplexityVisitor.a(ClassComplexityInspection.java:80)
    	at com.siyeh.ig.classmetrics.ClassComplexityInspection$ClassComplexityVisitor.visitClass(ClassComplexityInspection.java:71)
    	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:470)
    	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
    	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:309)
    	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:133)
    	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:223)
    	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:151)
    	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1132)
    	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:105)
    	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
    	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
    	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:116)
    	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:96)
    	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
    	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:234)
    	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
    	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
    	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
    Caused by: java.lang.AssertionError: Unexpected tokens
    	at com.intellij.lang.java.parser.JavaParserUtil.parseFragment(JavaParserUtil.java:206)
    	at com.intellij.psi.impl.source.tree.JavaElementType$JavaDummyElementType.parseContents(JavaElementType.java:275)
    	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
    	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
    	at com.intellij.psi.impl.source.JavaDummyElement.getFirstChildNode(JavaDummyElement.java:69)
    	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createMethodFromText(PsiJavaParserFacadeImpl.java:229)
    	... 39 more    

Can't tell when the exception occurred. I may have not noticed the error symbol immediately.

**Comment by mplushnikov** [comment]
Closed, outdated version, no more information found
