### ISSUE TITLE
Lombok plugin caches and returns invalid PSI

### ISSUE THREAD

**Issue by donnerpeter** [mplushnikov/lombok-intellij-plugin#425]
Method LombokLightMethodBuilder: setErrorReport of class de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder; param Light Parameter of class de.plushnikov.intellij.plugin.psi.LombokLightParameter

java.lang.RuntimeException: Method LombokLightMethodBuilder: setErrorReport of class de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder; param Light Parameter of class de.plushnikov.intellij.plugin.psi.LombokLightParameter
	at com.intellij.psi.util.PsiUtil.ensureValidType(PsiUtil.java:1192)
	at com.intellij.psi.util.MethodSignatureBackedByPsiMethod.create(MethodSignatureBackedByPsiMethod.java:88)
	at com.intellij.psi.util.MethodSignatureBackedByPsiMethod.create(MethodSignatureBackedByPsiMethod.java:68)
	at com.intellij.psi.impl.light.LightMethodBuilder.getSignature(LightMethodBuilder.java:272)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil$3.compute(PsiSuperMethodImplUtil.java:390)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil$3.compute(PsiSuperMethodImplUtil.java:384)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:45)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:96)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.getHierarchicalMethodSignature(PsiSuperMethodImplUtil.java:378)
	at com.intellij.psi.impl.light.LightMethodBuilder.getHierarchicalMethodSignature(LightMethodBuilder.java:145)
	at com.intellij.psi.impl.search.MethodSuperSearcher.lambda$execute$0(MethodSuperSearcher.java:42)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.psi.impl.search.MethodSuperSearcher.execute(MethodSuperSearcher.java:41)
	at com.intellij.psi.impl.search.MethodSuperSearcher.execute(MethodSuperSearcher.java:34)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:80)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:67)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:57)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:80)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethodSignatures(PsiSuperMethodImplUtil.java:95)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethodsInternal(PsiSuperMethodImplUtil.java:79)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethods(PsiSuperMethodImplUtil.java:73)
	at com.intellij.psi.impl.PsiSuperMethodImplUtil.findSuperMethods(PsiSuperMethodImplUtil.java:61)
	at com.intellij.psi.impl.light.LightMethodBuilder.findSuperMethods(LightMethodBuilder.java:283)
	at com.intellij.codeInsight.AnnotationUtil.isAnnotated(AnnotationUtil.java:321)
	at com.intellij.codeInsight.AnnotationUtil.isAnnotated(AnnotationUtil.java:259)
	at com.intellij.cdi.jam.CdiSemContributor.calcNamedBeanMeta(CdiSemContributor.java:72)
	at com.intellij.cdi.jam.CdiSemContributor.lambda$registerSemProviders$0(CdiSemContributor.java:46)
	at com.intellij.semantic.SemServiceImpl$2.lambda$registerSemElementProvider$0(SemServiceImpl.java:92)
	at com.intellij.semantic.SemServiceImpl.createSemElements(SemServiceImpl.java:189)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:160)
	at com.intellij.psi.impl.rename.AliasingPomTargetRenameHandler.getTargets(AliasingPomTargetRenameHandler.java:22)
	at com.intellij.psi.impl.rename.AliasingPomTargetRenameHandler.canProcessElement(AliasingPomTargetRenameHandler.java:60)
	at com.intellij.refactoring.rename.RenamePsiElementProcessor.forElement(RenamePsiElementProcessor.java:120)
	at com.intellij.refactoring.rename.RenameProcessor.performRefactoring(RenameProcessor.java:376)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$doRefactoring$11(BaseRefactoringProcessor.java:475)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$doRefactoring$12(BaseRefactoringProcessor.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteActionWithProgressInDispatchThread$15(ApplicationImpl.java:970)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.PotemkinProgress.runInSwingThread(PotemkinProgress.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithProgressInDispatchThread(ApplicationImpl.java:970)
	at com.intellij.refactoring.BaseRefactoringProcessor.doRefactoring(BaseRefactoringProcessor.java:486)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$execute$4(BaseRefactoringProcessor.java:314)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.refactoring.BaseRefactoringProcessor.execute(BaseRefactoringProcessor.java:312)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$null$7(BaseRefactoringProcessor.java:418)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$customizeUsagesView$8(BaseRefactoringProcessor.java:416)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.usages.impl.UsageViewImpl$MyPerformOperationRunnable.run(UsageViewImpl.java:1860)
	at com.intellij.usages.impl.UsageViewImpl$ButtonPanel.lambda$addButtonRunnable$0(UsageViewImpl.java:1773)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl because: different providers: DummyHolderViewProvider{myVirtualFile=LightVirtualFile: \DummyHolder, content=com.intellij.psi.AbstractFileViewProvider$PsiFileContent@4b6a386a}(563534b6); SingleRootFileViewProvider{myVirtualFile=LightVirtualFile: \DummyHolder, content=VirtualFileContent{size=0}}(74712d0a)
invalidated at: see attachment
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:502)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:190)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolve(PsiClassReferenceType.java:138)
	at com.intellij.psi.util.PsiUtil.ensureValidType(PsiUtil.java:1186)
	... 102 more

**Comment by donnerpeter** [comment]
Invalidated at:

java.lang.Throwable
	at com.intellij.psi.impl.DebugUtil.startPsiModification(DebugUtil.java:520)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:153)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:167)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:679)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:176)
	at com.intellij.psi.impl.source.tree.CompositeElement.replaceChildInternal(CompositeElement.java:506)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.bindToClass(PsiJavaCodeReferenceElementImpl.java:640)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.bindToElement(PsiJavaCodeReferenceElementImpl.java:563)
	at com.intellij.refactoring.rename.RenameJavaClassProcessor.renameElement(RenameJavaClassProcessor.java:96)
	at com.intellij.refactoring.rename.RenameUtil.doRename(RenameUtil.java:188)
	at com.intellij.refactoring.rename.RenameProcessor.performRefactoring(RenameProcessor.java:380)
	at com.intellij.refactoring.BaseRefactoringProcessor.a(BaseRefactoringProcessor.java:475)
	at com.intellij.refactoring.BaseRefactoringProcessor.a(BaseRefactoringProcessor.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.b(ApplicationImpl.java:977)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.PotemkinProgress.runInSwingThread(PotemkinProgress.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithProgressInDispatchThread(ApplicationImpl.java:977)
	at com.intellij.refactoring.BaseRefactoringProcessor.a(BaseRefactoringProcessor.java:486)
	at com.intellij.refactoring.BaseRefactoringProcessor.a(BaseRefactoringProcessor.java:314)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.refactoring.BaseRefactoringProcessor.execute(BaseRefactoringProcessor.java:312)
	at com.intellij.refactoring.BaseRefactoringProcessor.doRun(BaseRefactoringProcessor.java:243)
	at com.intellij.refactoring.rename.RenameProcessor.doRun(RenameProcessor.java:122)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenamer$MyRenameProcessor.doRun(MemberInplaceRenamer.java:329)
	at com.intellij.openapi.fileEditor.impl.NonProjectFileWritingAccessProvider.disableChecksDuring(NonProjectFileWritingAccessProvider.java:186)
	at com.intellij.refactoring.BaseRefactoringProcessor.run(BaseRefactoringProcessor.java:553)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenamer.performRenameInner(MemberInplaceRenamer.java:259)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenamer.a(MemberInplaceRenamer.java:228)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenamer.a(MemberInplaceRenamer.java:227)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:271)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mplushnikov** [comment]
Hello Peter,
thank you for your report. Do you have some suggestion, how to change it?

**Comment by donnerpeter** [comment]
To drop caches whenever what you cache changes :)

**Comment by donnerpeter** [comment]
`CachedValuesManager.getCachedValue(PsiElement, Provider)` with `PsiModificationTracker#MODIFICATION_COUNT` usually works well

**Comment by mplushnikov** [comment]
That is what I'm already using in AugmentProvider: CachedValuesManager and JAVA_STRUCTURE_MODIFICATION_COUNT
https://github.com/mplushnikov/lombok-intellij-plugin/blob/a061ab1a8b0e49b802bfa437ec963add8fc381d0/src/main/java/de/plushnikov/intellij/plugin/provider/LombokAugmentProvider.java#L127
https://github.com/mplushnikov/lombok-intellij-plugin/blob/a061ab1a8b0e49b802bfa437ec963add8fc381d0/src/main/java/de/plushnikov/intellij/plugin/provider/LombokAugmentProvider.java#L178

LombokLightParameter are method-parameter of LombokLightMethodBuilder and are created at the same time in AugmentProvider.
I'm not sure how to interpret this stacktraces.... any help is welcome:)

**Comment by donnerpeter** [comment]
This caching looks correct. Maybe there's another caching some place, that's not cleared.

It actually seems that this might be an IDE bug, namely, that invalid elements are attempted to be renamed. We'll add more diagnostics for it. I guess you can close this now, and if we get more reports with the diagnostics enabled, we'll notify you. Thanks!
