### ISSUE TITLE
PSI equals shouldn't perform resolve

### ISSUE THREAD

**Issue by donnerpeter** [mplushnikov/lombok-intellij-plugin#426]
First, it's slow. Second, invalid PSI is sometimes accessed inside (invalidated inside plain usual commitDocument):

Element: class com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl because: parent is null
invalidated at: see attachment

com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl because: parent is null
invalidated at: see attachment
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:502)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:190)
	at com.intellij.psi.PsiClassType.equals(PsiClassType.java:107)
	at de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder.equals(LombokLightMethodBuilder.java:268)
	at com.intellij.openapi.util.Comparing.equal(Comparing.java:43)
	at com.intellij.ide.structureView.newStructureView.StructureViewComponent$MyNodeWrapper.equals(StructureViewComponent.java:890)
	at java.util.HashMap$TreeNode.find(HashMap.java:1859)
	at java.util.HashMap$TreeNode.find(HashMap.java:1869)
	at java.util.HashMap$TreeNode.find(HashMap.java:1869)
	at java.util.HashMap$TreeNode.getTreeNode(HashMap.java:1881)
	at java.util.HashMap.removeNode(HashMap.java:823)
	at java.util.HashMap.remove(HashMap.java:798)
	at java.util.HashSet.remove(HashSet.java:235)
	at com.intellij.ide.util.treeView.AbstractTreeUi$ElementNode.remove(AbstractTreeUi.java:2562)
	at javax.swing.tree.DefaultTreeModel.removeNodeFromParent(DefaultTreeModel.java:260)
	at com.intellij.ide.util.treeView.AbstractTreeUi$51.perform(AbstractTreeUi.java:3248)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.UpdaterTreeState.process(UpdaterTreeState.java:123)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processInnerChange(AbstractTreeUi.java:3287)
	at com.intellij.ide.util.treeView.AbstractTreeUi.removeNodeFromParent(AbstractTreeUi.java:3237)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$3300(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$49.perform(AbstractTreeUi.java:3106)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.TreeRunnable$TreeConsumer.consume(TreeRunnable.java:50)
	at org.jetbrains.concurrency.DonePromise.done(DonePromise.java:40)
	at com.intellij.ide.util.treeView.AbstractTreeUi.lambda$processExistingNode$7(AbstractTreeUi.java:3074)
	at org.jetbrains.concurrency.AsyncPromise.setHandler(AsyncPromise.kt:201)
	at org.jetbrains.concurrency.AsyncPromise.done(AsyncPromise.kt:43)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExistingNode(AbstractTreeUi.java:3018)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5000(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$32$1.run(AbstractTreeUi.java:1718)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1835)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5300(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$33.perform(AbstractTreeUi.java:1801)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2090)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5900(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$36$1.perform(AbstractTreeUi.java:2002)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:410)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2185)
	at com.intellij.ide.util.treeView.AbstractTreeUi$36.perform(AbstractTreeUi.java:1997)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.lambda$new$0(AbstractTreeBuilder.java:49)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:120)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mplushnikov** [comment]
Hello Peter,
thank you for your warning! 

As I can see `resolve `is called inside from `equals `method of the `PsiClassType`. 
I'm just calling `equal `of `PsiType ` to check two returnTypes for equality. 

Should it not be fixed inside of `PsiClassType `itself, if its wrong? 
Or what would be your suggestion for me, to use instead of calling `equal `on `PsiType`?

**Comment by donnerpeter** [comment]
Slow `PsiClassType.equals` is somewhat OK, because normally it isn't called in contexts requiring very fast response. For example, types aren't normally shown in Project View or trees. But PSI elements are shown in trees and so their `equals` should be fast.

I don't understand why you need PSI elements with equality depending on types. Do you really need them different for `List<String>` and `List<Integer>`? Can you have them as singletons, one per type, with `==` equality? These questions are so general, because I don't know which problem you're solving. If you explain the reasons behind this decision, I could try to help more specifically.

**Comment by mplushnikov** [comment]
It's used in equals of my extension of LightMethodBuilder. 
The root issue was #70 or https://youtrack.jetbrains.com/issue/IDEA-133357
I need to compare multiple generated methods (before and after rename operation) so newly generated methods are equivalent to old ones...
This why, I'm actually comparing all attributes of a method, like: class name, method name, method parameter and even returnType of the method.

**Comment by donnerpeter** [comment]
Why are type checks necessary? I'd suppose that class name + method name (+ maybe parameter count) is enough to distinguish property accessors. 

Can you anchor your LightMethodBuilder to some real PSI element, and check equality of that `PsiElement` instead? Can you save some string from the type at the moment of creation (e.g. `getCanonicalText`) and compare that string instead of `PsiType`?

**Comment by mplushnikov** [comment]
Thank you for a suggestion, I used the last one with canonicalText saved at creation time as string.
