### ISSUE TITLE
Exception thrown when using *Find Usages* with ideavim

### ISSUE THREAD

**Issue by aristotll** [mplushnikov/lombok-intellij-plugin#427]
### Short description
When I use ideaVim `gd` to find the usage of a field the exception is thrown.

### Expected behavior
Just show the field usages normally.

### Version information

 * **IDEA Version:** IntelliJ IDEA 2017.2.6  Build #IU-172.4574.11 
 * **JDK Version:** 1.8.0_152-release 
 * **OS Type & Version:** _Mac OS X_  macOS 10.12.5 (16F73)
 * **Lombok Plugin Version:** _0.15.17.2_(the latest from Jetbrain plugins)
 * **Lombok Dependency Version:** _1.16.18_

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. active ideaVim
 2. normal mode, move to the field and type **gd**
 3. the exception is thrown.

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

Assertion failed: Find Usages should be shown in a transaction, see AnAction#startInTransaction
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.find.findUsages.JavaFindUsagesHandler.a(JavaFindUsagesHandler.java:212)
	at com.intellij.find.findUsages.JavaFindUsagesHandler.a(JavaFindUsagesHandler.java:204)
	at com.intellij.find.findUsages.JavaFindUsagesHandler.getSecondaryElements(JavaFindUsagesHandler.java:189)
	at de.plushnikov.intellij.plugin.extension.LombokFieldFindUsagesHandlerFactory$1.getSecondaryElements(LombokFieldFindUsagesHandlerFactory.java:65)
	at com.intellij.find.actions.ShowUsagesAction.a(ShowUsagesAction.java:350)
	at com.intellij.find.actions.ShowUsagesAction.startFindUsages(ShowUsagesAction.java:239)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.a(GotoDeclarationAction.java:139)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.invoke(GotoDeclarationAction.java:99)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$null$0(CodeInsightAction.java:73)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:79)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:70)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:43)
	at com.maddyhome.idea.vim.KeyHandler.executeAction(KeyHandler.java:610)
	at com.maddyhome.idea.vim.KeyHandler.executeAction(KeyHandler.java:591)
	at com.maddyhome.idea.vim.action.motion.search.GotoDeclarationAction$Handler.execute(GotoDeclarationAction.java:41)
	at com.maddyhome.idea.vim.handler.EditorActionHandlerBase.execute(EditorActionHandlerBase.java:45)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doExecute(EditorActionHandler.java:172)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:86)
	at com.maddyhome.idea.vim.KeyHandler.executeAction(KeyHandler.java:610)
	at com.maddyhome.idea.vim.KeyHandler$ActionRunner.run(KeyHandler.java:674)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:921)
	at com.maddyhome.idea.vim.helper.RunnableHelper$ReadAction.run(RunnableHelper.java:59)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.maddyhome.idea.vim.helper.RunnableHelper.runReadCommand(RunnableHelper.java:41)
	at com.maddyhome.idea.vim.KeyHandler.executeCommand(KeyHandler.java:459)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.java:199)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.java:104)
	at com.maddyhome.idea.vim.VimTypedActionHandler.execute(VimTypedActionHandler.java:53)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$0(TypedAction.java:142)
	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:42)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:142)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1133)
	at com.intellij.openapi.editor.impl.EditorImpl.a(EditorImpl.java:1121)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3141)
	at com.intellij.openapi.editor.impl.EditorImpl$6.keyTyped(EditorImpl.java:956)
	at java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:239)
	at java.awt.Component.processKeyEvent(Component.java:6496)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
	at java.awt.Component.processEvent(Component.java:6318)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:27)
	at java.awt.Component.dispatchEventImpl(Component.java:4768)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by mplushnikov** [comment]
The core issue is in ideaVim itself. But it is hidden by lombok plugin at the moment.
I'll change a little bit in my implementation, so next time only the root problem will be showed.
I also reported it to Jetbrains: https://ea.jetbrains.com/browser/ea_reports/1705896
