### ISSUE TITLE
No ideal what happen

### ISSUE THREAD

**Issue by JosephChanChan** [mplushnikov/lombok-intellij-plugin#431]
com/intellij/util/indexing/IndexId
java.lang.NoClassDefFoundError: com/intellij/util/indexing/IndexId
	at de.plushnikov.intellij.plugin.lombokconfig.ConfigDiscovery.readProperty(ConfigDiscovery.java:153)
	at de.plushnikov.intellij.plugin.lombokconfig.ConfigDiscovery.discoverProperty(ConfigDiscovery.java:119)
	at de.plushnikov.intellij.plugin.lombokconfig.ConfigDiscovery.getStringLombokConfigProperty(ConfigDiscovery.java:37)
	at de.plushnikov.intellij.plugin.lombokconfig.ConfigDiscovery.getBooleanLombokConfigProperty(ConfigDiscovery.java:44)
	at de.plushnikov.intellij.plugin.processor.field.AccessorsInfo.buildAccessorsInfo(AccessorsInfo.java:84)
	at de.plushnikov.intellij.plugin.processor.field.AccessorsInfo.build(AccessorsInfo.java:62)
	at de.plushnikov.intellij.plugin.processor.field.AccessorsInfo.build(AccessorsInfo.java:47)
	at de.plushnikov.intellij.plugin.processor.field.SetterFieldProcessor.getAllSetterNames(SetterFieldProcessor.java:114)
	at de.plushnikov.intellij.plugin.processor.clazz.SetterProcessor.filterSetterFields(SetterProcessor.java:97)
	at de.plushnikov.intellij.plugin.processor.clazz.SetterProcessor.createFieldSetters(SetterProcessor.java:70)
	at de.plushnikov.intellij.plugin.processor.clazz.SetterProcessor.generatePsiElements(SetterProcessor.java:63)
	at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:57)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:176)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:141)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:87)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:140)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:127)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$collectAugments$0(PsiAugmentProvider.java:93)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:137)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:92)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getAllMethods(ClassInnerStuffCache.java:132)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.lambda$getMethods$2(ClassInnerStuffCache.java:66)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:141)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:87)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:140)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:127)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:65)
	at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:297)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClassNotCached(PsiClassImplUtil.java:683)
	at com.intellij.psi.impl.PsiClassImplUtil.access$200(PsiClassImplUtil.java:63)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.create(PsiClassImplUtil.java:402)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.create(PsiClassImplUtil.java:350)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:57)
	at com.intellij.psi.impl.PsiClassImplUtil.processCachedMembersByName(PsiClassImplUtil.java:586)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:478)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:455)
	at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:487)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:238)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl$OurGenericsResolver.resolve(PsiImportStaticReferenceElementImpl.java:227)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:140)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:163)
	at com.intellij.psi.impl.source.PsiImportStaticReferenceElementImpl.multiResolve(PsiImportStaticReferenceElementImpl.java:223)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarationsNoGuess(PsiJavaFileBaseImpl.java:370)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:305)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:69)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:51)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:218)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:149)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:458)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:360)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:352)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:185)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:184)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:721)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:713)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:387)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:380)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:349)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher$3.compute(AnnotatedElementsSearcher.java:82)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher$3.compute(AnnotatedElementsSearcher.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:942)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.execute(AnnotatedElementsSearcher.java:64)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.execute(AnnotatedElementsSearcher.java:39)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:79)
	at com.intellij.util.InstanceofQuery.forEach(InstanceofQuery.java:58)
	at com.intellij.jam.model.util.JamCommonUtil.findAnnotatedElements(JamCommonUtil.java:423)
	at com.intellij.jam.JamService.getJamClassElements(JamService.java:179)
	at com.intellij.jam.JamService.getJamClassElements(JamService.java:144)
	at com.intellij.spring.model.jam.SpringJamModelImpl.getControllers(SpringJamModelImpl.java:98)
	at com.intellij.spring.model.jam.SpringJamModelImpl.getStereotypeComponents(SpringJamModelImpl.java:51)
	at com.intellij.spring.contexts.model.ComponentScanPackagesModel.lambda$getScannedComponents$1(ComponentScanPackagesModel.java:112)
	at com.intellij.spring.contexts.model.ComponentScanPackagesModel.getScannedComponents(ComponentScanPackagesModel.java:134)
	at com.intellij.spring.contexts.model.ComponentScanPackagesModel.getScannedComponents(ComponentScanPackagesModel.java:112)
	at com.intellij.spring.model.jam.stereotype.SpringComponentScan.getScannedBeans(SpringComponentScan.java:73)
	at com.intellij.spring.model.utils.SpringCacheUtils$1.create(SpringCacheUtils.java:64)
	at com.intellij.spring.model.utils.SpringCacheUtils$1.create(SpringCacheUtils.java:61)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:57)
	at com.intellij.spring.model.utils.SpringCacheUtils.getCreatedCachedBeans(SpringCacheUtils.java:72)
	at com.intellij.spring.model.jam.stereotype.SpringComponentScan.getScannedElements(SpringComponentScan.java:67)
	at com.intellij.spring.contexts.model.SpringComponentScanModel.calculateScannedBeans(SpringComponentScanModel.java:75)
	at com.intellij.spring.contexts.model.ComponentScanPackagesModel.calculateLocalBeans(ComponentScanPackagesModel.java:57)
	at com.intellij.spring.contexts.model.SpringComponentScanModel.lambda$getLocalBeans$0(SpringComponentScanModel.java:64)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.spring.contexts.model.SpringComponentScanModel.getLocalBeans(SpringComponentScanModel.java:70)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processLocalBeans(AbstractSimpleSpringModel.java:175)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.access$100(AbstractSimpleSpringModel.java:39)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel$1.doProcessBeans(AbstractSimpleSpringModel.java:46)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel$1.doProcessBeans(AbstractSimpleSpringModel.java:42)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel$LocalBeansCachingProcessor.findPointers(AbstractSimpleSpringModel.java:70)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$1.createValue(SpringCachingProcessor.java:52)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$1.createValue(SpringCachingProcessor.java:48)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$SpringSLRUCache.get(SpringCachingProcessor.java:118)
	at com.intellij.spring.contexts.model.SpringCachingProcessor.process(SpringCachingProcessor.java:83)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processByClass(AbstractSimpleSpringModel.java:166)
	at com.intellij.spring.contexts.model.CachedLocalModel.lambda$processRelatedModels$2(CachedLocalModel.java:185)
	at com.intellij.spring.contexts.model.CachedLocalModel.lambda$processRelatedModels$1(CachedLocalModel.java:160)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.spring.contexts.model.CachedLocalModel.processRelatedModels(CachedLocalModel.java:157)
	at com.intellij.spring.contexts.model.CachedLocalModel.processRelatedModels(CachedLocalModel.java:185)
	at com.intellij.spring.contexts.model.CachedLocalModel.processByClass(CachedLocalModel.java:173)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processByClass(AbstractSimpleSpringModel.java:168)
	at com.intellij.spring.contexts.model.SpringModel.lambda$processByClass$5(SpringModel.java:158)
	at com.intellij.spring.contexts.model.SpringModel.processModels(SpringModel.java:230)
	at com.intellij.spring.contexts.model.SpringModel.processModels(SpringModel.java:226)
	at com.intellij.spring.contexts.model.SpringModel.processModels(SpringModel.java:226)
	at com.intellij.spring.contexts.model.SpringModel.processModels(SpringModel.java:216)
	at com.intellij.spring.contexts.model.SpringModel.processByClass(SpringModel.java:154)
	at com.intellij.spring.model.utils.SpringModelSearchers.containsBean(SpringModelSearchers.java:91)
	at com.intellij.spring.model.utils.SpringModelSearchers.doesBeanExist(SpringModelSearchers.java:79)
	at com.intellij.spring.java.SpringJavaClassInfo.lambda$new$0(SpringJavaClassInfo.java:83)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.spring.java.SpringJavaClassInfo.isMapped(SpringJavaClassInfo.java:200)
	at com.intellij.spring.code.SpringImplicitUsageProvider.isMappedBeanClass(SpringImplicitUsageProvider.java:133)
	at com.intellij.spring.code.SpringImplicitUsageProvider.isBeanClassOrConstructor(SpringImplicitUsageProvider.java:120)
	at com.intellij.spring.code.SpringImplicitUsageProvider.isImplicitUsage(SpringImplicitUsageProvider.java:45)
	at com.intellij.codeInsight.daemon.impl.UnusedSymbolUtil.isImplicitUsage(UnusedSymbolUtil.java:54)
	at com.intellij.codeInsight.daemon.impl.UnusedSymbolUtil.a(UnusedSymbolUtil.java:312)
	at com.intellij.codeInsight.daemon.impl.UnusedSymbolUtil.isClassUsed(UnusedSymbolUtil.java:301)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.a(PostHighlightingVisitor.java:459)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.a(PostHighlightingVisitor.java:240)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.collectHighlights(PostHighlightingVisitor.java:160)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.a(HighlightVisitorImpl.java:176)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:335)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:172)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:298)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:238)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.indexing.IndexId PluginClassLoader[Lombook Plugin, 0.15.17]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 169 more

**Comment by mplushnikov** [comment]
Please provide your version informations like:
IDEA Version, JDK Version, OS Type & Version and Lombok Plugin Version

**Comment by mplushnikov** [comment]
Closed, no feedback, outdated version
