### ISSUE TITLE
Short name 'Convert2Diamond' is not unique

### ISSUE THREAD

**Issue by Charriu83** [mplushnikov/lombok-intellij-plugin#476]
### Short description
Error message "Short name 'Convert2Diamond' is not unique" is shown on every startup.

### Expected behavior
No error message on startup.

### Version information

 * **IDEA Version:** 2018.1 Build 181.4203.550 (26th March 2018)
 * **JDK Version:** 1.8.161
 * **OS Type & Version:** Windows 7 64-Bit
 * **Lombok Plugin Version:** 0.13.16
 * **Lombok Dependency Version:**  1.16.20

### Steps to reproduce
1) Start intelliJ

### Sample project
No

### Additional information
No

### Stacktrace
```

Short name 'Convert2Diamond' is not unique
class 'de.plushnikov.intellij.plugin.inspection.LombokExplicitTypeCanBeDiamondInspection' in PluginDescriptor[name='Lombok Plugin', classpath='C:\Users\fgel\.IntelliJIdea2018.1\config\plugins\lombok-plugin']
and
class'com.intellij.codeInspection.ExplicitTypeCanBeDiamondInspection' in PluginDescriptor[name='IDEA CORE', classpath='C:\Program Files\JetBrains\IntelliJ IDEA 2018.1\lib\resources.jar']
conflict [Plugin: Lombook Plugin]
com.intellij.diagnostic.PluginException: Short name 'Convert2Diamond' is not unique
class 'de.plushnikov.intellij.plugin.inspection.LombokExplicitTypeCanBeDiamondInspection' in PluginDescriptor[name='Lombok Plugin', classpath='C:\Users\fgel\.IntelliJIdea2018.1\config\plugins\lombok-plugin']
and
class'com.intellij.codeInspection.ExplicitTypeCanBeDiamondInspection' in PluginDescriptor[name='IDEA CORE', classpath='C:\Program Files\JetBrains\IntelliJ IDEA 2018.1\lib\resources.jar']
conflict [Plugin: Lombook Plugin]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.checkForDuplicateShortName(InspectionToolRegistrar.java:86)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.ensureInitialized(InspectionToolRegistrar.java:60)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:127)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:34)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:49)
	at com.intellij.openapi.application.Preloader.lambda$null$0(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.lambda$initComponent$1(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by mplushnikov** [comment]
Unfortunately you are using a very old version of lombok plugin.Please just update your lombok plugin version.
