### ISSUE TITLE
cached PSI class com.intellij.psi.impl.source.PsiJavaFileImpl

### ISSUE THREAD

**Issue by zhangkongjun** [mplushnikov/lombok-intellij-plugin#480]
### Short description
Outdated stub in index: jar://C:/Users/hp/.m2/repository/org/springframework/spring-core/4.3.13.RELEASE/spring-core-4.3.13.RELEASE-sources.jar!/org/springframework/core/convert/converter/Converter.java null, doc=null, docSaved=true, wasIndexedAlready=true, queried at 1523350822560

### Expected behavior
Outdated stub in index: jar://C:/Users/hp/.m2/repository/org/springframework/spring-core/4.3.13.RELEASE/spring-core-4.3.13.RELEASE-sources.jar!/org/springframework/core/convert/converter/Converter.java null, doc=null, docSaved=true, wasIndexedAlready=true, queried at 1523350822560
indexed lengths={chars=444, bytes=466}
doc length=-1
file length=1484
cached PSI class com.intellij.psi.impl.source.PsiJavaFileImpl
projects with file: 1
java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.diagnoseLengthMismatch(StubTreeLoaderImpl.java:175)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.checkLengthMatch(StubTreeLoaderImpl.java:145)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:113)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:53)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:652)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:1022)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubbedSpine(PsiFileImpl.java:240)
	at com.intellij.psi.stubs.StubProcessingHelperBase.lambda$getAllSpines$0(StubProcessingHelperBase.java:76)
	at com.intellij.util.containers.ContainerUtilRt.map2List(ContainerUtilRt.java:393)
	at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1865)
	at com.intellij.psi.stubs.StubProcessingHelperBase.getAllSpines(StubProcessingHelperBase.java:76)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:56)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:319)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:640)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:628)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:61)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:348)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:310)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:47)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:96)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClasses(JavaFileManagerImpl.java:83)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClasses(PsiElementFinderImpl.java:45)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClassesWithoutJvmFacade(JavaPsiFacadeImpl.java:195)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClassesWithJvmFacade(JavaPsiFacadeImpl.java:166)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClasses(JavaPsiFacadeImpl.java:158)
	at com.intellij.psi.impl.file.PsiPackageImpl.getCachedClassesByName(PsiPackageImpl.java:213)
	at com.intellij.psi.impl.file.PsiPackageImpl.findClassByShortName(PsiPackageImpl.java:275)
	at com.intellij.psi.impl.file.PsiPackageImpl.processDeclarations(PsiPackageImpl.java:309)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processPackageDeclarations(PsiJavaFileBaseImpl.java:438)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processOnDemandTarget(PsiJavaFileBaseImpl.java:448)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarationsNoGuess(PsiJavaFileBaseImpl.java:362)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:312)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:69)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:51)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:218)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:149)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:492)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:47)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:373)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:365)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:205)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:204)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:724)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:286)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:277)
	at com.intellij.psi.impl.source.PsiClassReferenceType.getText(PsiClassReferenceType.java:257)
	at com.intellij.psi.impl.source.PsiClassReferenceType.getCanonicalText(PsiClassReferenceType.java:243)
	at com.intellij.psi.PsiNameHelper.appendTypeArgs(PsiNameHelper.java:264)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:318)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:277)
	at com.intellij.psi.impl.source.PsiClassReferenceType.getText(PsiClassReferenceType.java:257)
	at com.intellij.psi.impl.source.PsiClassReferenceType.getCanonicalText(PsiClassReferenceType.java:243)
	at com.intellij.psi.PsiNameHelper.appendTypeArgs(PsiNameHelper.java:264)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:318)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:277)
	at com.intellij.psi.impl.source.PsiClassReferenceType.getText(PsiClassReferenceType.java:257)
	at com.intellij.psi.impl.source.PsiClassReferenceType.getCanonicalText(PsiClassReferenceType.java:243)
	at com.intellij.psi.PsiClassType$Stub.getCanonicalText(PsiClassType.java:356)
	at de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder.setMethodReturnType(LombokLightMethodBuilder.java:77)
	at de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder.withMethodReturnType(LombokLightMethodBuilder.java:71)
	at de.plushnikov.intellij.plugin.processor.field.GetterFieldProcessor.createGetterMethod(GetterFieldProcessor.java:124)
	at de.plushnikov.intellij.plugin.processor.clazz.GetterProcessor.createFieldGetters(GetterProcessor.java:80)
	at de.plushnikov.intellij.plugin.processor.clazz.DataProcessor.generatePsiElements(DataProcessor.java:78)
	at de.plushnikov.intellij.plugin.processor.clazz.AbstractClassProcessor.process(AbstractClassProcessor.java:57)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider$LombokCachedValueProvider.compute(LombokAugmentProvider.java:176)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:87)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:139)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.getAugments(LombokAugmentProvider.java:127)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$collectAugments$0(PsiAugmentProvider.java:90)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:134)
	at com.intellij.psi.augment.PsiAugmentProvider.collectAugments(PsiAugmentProvider.java:89)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getAllMethods(ClassInnerStuffCache.java:112)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.lambda$getMethods$2(ClassInnerStuffCache.java:46)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:87)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:139)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at com.intellij.psi.impl.source.ClassInnerStuffCache.getMethods(ClassInnerStuffCache.java:46)
	at com.intellij.psi.impl.source.PsiClassImpl.getMethods(PsiClassImpl.java:298)
	at com.intellij.jam.JamService.processMembers(JamService.java:81)
	at com.intellij.jam.JamService.getAnnotatedMembersList(JamService.java:226)
	at com.intellij.spring.model.jam.stereotype.SpringStereotypeElement.lambda$getBeans$1(SpringStereotypeElement.java:66)
	at com.intellij.jam.model.util.JamCommonUtil.processSuperClassList(JamCommonUtil.java:124)
	at com.intellij.spring.model.jam.stereotype.SpringStereotypeElement.getBeans(SpringStereotypeElement.java:65)
	at com.intellij.spring.contexts.model.ComponentScanPackagesModel.calculateLocalBeans(ComponentScanPackagesModel.java:64)
	at com.intellij.spring.contexts.model.SpringComponentScanModel.lambda$getLocalBeans$0(SpringComponentScanModel.java:64)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.spring.contexts.model.SpringComponentScanModel.getLocalBeans(SpringComponentScanModel.java:70)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processLocalBeans(AbstractSimpleSpringModel.java:169)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.access$100(AbstractSimpleSpringModel.java:39)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel$1.doProcessBeans(AbstractSimpleSpringModel.java:46)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel$1.doProcessBeans(AbstractSimpleSpringModel.java:42)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel$LocalBeansCachingProcessor.findPointers(AbstractSimpleSpringModel.java:70)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$1.createValue(SpringCachingProcessor.java:49)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$1.createValue(SpringCachingProcessor.java:45)
	at com.intellij.spring.contexts.model.SpringCachingProcessor$SpringSLRUCache.get(SpringCachingProcessor.java:110)
	at com.intellij.spring.contexts.model.SpringCachingProcessor.process(SpringCachingProcessor.java:76)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processByClass(AbstractSimpleSpringModel.java:160)
	at com.intellij.spring.contexts.model.CachedLocalModel.lambda$processRelatedModels$3(CachedLocalModel.java:137)
	at com.intellij.spring.contexts.model.CachedLocalModel.lambda$processRelatedModels$1(CachedLocalModel.java:108)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:67)
	at com.intellij.spring.contexts.model.CachedLocalModel.processRelatedModels(CachedLocalModel.java:105)
	at com.intellij.spring.contexts.model.CachedLocalModel.processRelatedModels(CachedLocalModel.java:137)
	at com.intellij.spring.contexts.model.CachedLocalModel.processByClass(CachedLocalModel.java:121)
	at com.intellij.spring.contexts.model.AbstractSimpleSpringModel.processByClass(AbstractSimpleSpringModel.java:162)
	at com.intellij.spring.model.utils.SpringModelSearchers.findBeans(SpringModelSearchers.java:48)
	at com.intellij.spring.java.SpringJavaClassInfo.lambda$new$1(SpringJavaClassInfo.java:98)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.spring.java.SpringJavaClassInfo.getStereotypeMappedBeans(SpringJavaClassInfo.java:267)
	at com.intellij.spring.model.highlighting.jam.SpringJavaAutowiredFieldsWarningInspection.checkClass(SpringJavaAutowiredFieldsWarningInspection.java:58)
	at com.intellij.codeInspection.AbstractBaseJavaLocalInspectionTool$1.visitClass(AbstractBaseJavaLocalInspectionTool.java:60)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:470)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$4(LocalInspectionsPass.java:301)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:223)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:151)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:223)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

### Version information

 * **IDEA Version:2018.1
 * **JDK Version:8
 * **OS Type & Version:windows 7
 * **Lombok Plugin Version:0.17-2018.1

**Comment by mplushnikov** [comment]
I think it's a problem of IntelliJ itself... Please try to rebuild IntelliJ caches (File->Invalidate caches/Restart)
