### ISSUE TITLE
using @Data annotation meet NullPointerException

### ISSUE THREAD

**Issue by MrFant** [mplushnikov/lombok-intellij-plugin#518]
I try to use @Data annotation on a POJO class , then , i meet nullpointerException when using spring jpa .  see blow:

> java.lang.NullPointerException
	at org.hibernate.engine.internal.StatefulPersistenceContext.getLoadedCollectionOwnerOrNull(StatefulPersistenceContext.java:788)
	at org.hibernate.event.spi.AbstractCollectionEvent.getLoadedOwnerOrNull(AbstractCollectionEvent.java:58)
	at org.hibernate.event.spi.InitializeCollectionEvent.<init>(InitializeCollectionEvent.java:22)
	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:2221)
	at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:565)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:247)
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:561)
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:132)
	at org.hibernate.collection.internal.PersistentSet.hashCode(PersistentSet.java:430)
	at com.example.acegi.domain.Student.hashCode(Student.java:17)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.put(HashMap.java:612)
	at java.util.HashSet.add(HashSet.java:220)

But the exception disappear when i change to use @Getter @Setter @NoArgsConstructor , i want to know why ? Thank u !

**Comment by mplushnikov** [comment]
Provide your code to make it clear. But I think it why @Data also generates equals and hashcode methods, wich are used by Hibernate somethere, but because your Objects are not fully initialized, you got NPE.
