### ISSUE TITLE
Help me please!!!! Getter and Setter can work, but Builder Can not work !

### ISSUE THREAD

**Issue by White99** [mplushnikov/lombok-intellij-plugin#519]
### Short description
Builder can not work 

### Expected behavior
Builder should be working

### Version information

IntelliJ IDEA 2018.2.1 (Ultimate Edition)
Build #IU-182.3911.36, built on August 6, 2018
Licensed to lan yu
Subscription is active until May 5, 2019
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

 * **Lombok Plugin Version:**  0.19-LATEST-EAP-SNAPSHOT
 * **Lombok Dependency Version:**  1.18.2

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. ???
 2. ???
 3. ???

STACKTRACE HERE (inside code markup)

```

**Comment by JackFe** [comment]
1、Please Setup：... > Compiler > Java Compiler > Use Compiler: Javac，I've solved this problem. 
2、Compiler Eclipse may be incompatible with lombok plugin

**Comment by White99** [comment]
@JackFe  Thanks for your reply!
But...
1.  "Use compiler:Javac" is default setting in my Intellij IDEA. but  it still can not work.

2.  After i switched back to Eclipse , it works fine.....

**Comment by JackFe** [comment]
It's incredible! Check if you're configured like "**IntelliJ and Eclipse compiler**". I Read README.md and find that Eclipse compiler requires additional configuration. I try it, but Configure not successful. So I swtiche compiler from Eclipse to Javac and the code will compile normally.
link：https://github.com/mplushnikov/lombok-intellij-plugin
> **IntelliJ and Eclipse compiler**
If you're using Eclipse compiler with lombok, try this setup:
install plugin
make sure Lombok dependency is added to the project
change compiler setting:
... > Compiler > Java Compiler > Use Compiler: Eclipse
... > Compiler > Annotation Processors > Enable annotation processing: checked (default configuration)
... > Compiler > Additional build process VM options: -javaagent:lombok.jar

**Comment by mplushnikov** [comment]
@White99 Please provide some example code or project showing your error.

**Comment by mplushnikov** [comment]
Closed, as no feedback provided. Not reproducible.

**Comment by InterestingSnow** [comment]
<dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            
            <version>1.18.0</version>
   </dependency>


Warning:(13, 8) java: lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation: java.lang.RuntimeException: java.lang.ClassNotFoundException: lombok.javac.handlers.HandleBuilderDefault
  	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:114)
  	at lombok.javac.HandlerLibrary.loadAnnotationHandlers(HandlerLibrary.java:170)
  	at lombok.javac.HandlerLibrary.load(HandlerLibrary.java:155)
  	at lombok.javac.JavacTransformer.<init>(JavacTransformer.java:43)
  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:86)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:140)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:54)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:168)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:388)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:289)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:197)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:168)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1238)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:912)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:984)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:871)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:696)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:387)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:194)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:137)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:294)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
  	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.ClassNotFoundException: lombok.javac.handlers.HandleBuilderDefault
  	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:418)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	at java.lang.Class.forName0(Native Method)
  	at java.lang.Class.forName(Class.java:348)
  	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:111)
  	... 40 more
jdk1.8

**Comment by InterestingSnow** [comment]
![image](https://user-images.githubusercontent.com/45022377/50071955-8541f200-020e-11e9-96d7-83a0b9ea73b2.png)

![image](https://user-images.githubusercontent.com/45022377/50071968-8ecb5a00-020e-11e9-9cae-0d4d3310e2dd.png)
