### ISSUE TITLE
2018.3 EAP Plugin error

### ISSUE THREAD

**Issue by monowai** [mplushnikov/lombok-intellij-plugin#536]
### Short description
Intellij IDEA is reporting an error requesting me to restart due to an error in the Lombok plugin.

### Version information

 * **IDEA Version:** 2018.3 EAP
 * **JDK Version:** 1.8.0_152-RELEASE-1342-b3
 * **OS Type & Version:** OSX 10.13.6
 * **Lombok Plugin Version:** v0.21.IDEA-EAP

### Steps to reproduce
Invalidate caches and restart. 
### Additional information
 My project does have a lombok.config file one entry:
```
lombok.anyConstructor.addConstructorProperties=true
```
### Stacktrace
Error while indexing ~/IdeaProjects/xxx/awb/svc-twee/src/lombok.config
To reindex this file IDEA has to be restarted

```

java.lang.ExceptionInInitializerError
	at de.plushnikov.intellij.plugin.language.LombokConfigSyntaxHighlighterFactory.getSyntaxHighlighter(LombokConfigSyntaxHighlighterFactory.java:13)
	at com.intellij.openapi.fileTypes.SyntaxHighlighterFactory.getSyntaxHighlighter(SyntaxHighlighterFactory.java:39)
	at com.intellij.openapi.fileTypes.LanguageFileTypeHighlighterProvider.create(LanguageFileTypeHighlighterProvider.java:31)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.openapi.util.KeyedExtensionFactory.getByKey(KeyedExtensionFactory.java:91)
	at com.intellij.openapi.util.KeyedExtensionFactory.access$000(KeyedExtensionFactory.java:22)
	at com.intellij.openapi.util.KeyedExtensionFactory$1.invoke(KeyedExtensionFactory.java:45)
	at com.sun.proxy.$Proxy116.create(Unknown Source)

```

**Comment by mplushnikov** [comment]
Did it occured only one time or every time your are opening the project? Did you have some example to reproduce this issue?

**Comment by mplushnikov** [comment]
Close as outdated
