### ISSUE TITLE
SIMPLE_BAD_CHARACTER error thrown during IntelliJ startup

### ISSUE THREAD

**Issue by maksimu** [mplushnikov/lombok-intellij-plugin#577]
### Short description
IntelliJ Throws error when opening it. 
TextAttributeKey(name:'SIMPLE_BAD_CHARACTER', fallbackAttributeKey:'null')  was already registered with the other fallback attribute key: 

### Version information
 * **IDEA Version:** IntelliJ IDEA 2018.3.3 (Ultimate Edition), Build #IU-183.5153.38, built on January 9, 2019
 * **JDK Version:** 1.8.0_152-release-1343-b26 x86_64
 * **OS Type & Version:** macOS 10.12.6
 * **Lombok Plugin Version:** v0.23-2018.3
 * **Lombok Dependency Version:** _Not applicable. In the current project I don't have Java._

### Steps to reproduce

Just open IntelliJ (see versions above)

### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```
java.lang.IllegalStateException: TextAttributeKey(name:'SIMPLE_BAD_CHARACTER', fallbackAttributeKey:'null')  was already registered with the other fallback attribute key: BAD_CHARACTER
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:214)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:200)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getOrCreate(TextAttributesKey.java:200)
	at com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey(TextAttributesKey.java:166)
	at de.plushnikov.intellij.plugin.language.LombokConfigSyntaxHighlighter.<clinit>(LombokConfigSyntaxHighlighter.java:24)
	at de.plushnikov.intellij.plugin.language.LombokConfigSyntaxHighlighterFactory.getSyntaxHighlighter(LombokConfigSyntaxHighlighterFactory.java:13)
	at com.intellij.openapi.fileTypes.SyntaxHighlighterFactory.getSyntaxHighlighter(SyntaxHighlighterFactory.java:39)
	at org.jetbrains.plugins.ruby.ruby.lang.highlighter.RubyEditorHighlighter.<init>(RubyEditorHighlighter.java:44)
	at org.jetbrains.plugins.ruby.ruby.lang.highlighter.RubyEditorHighlighterProvider.getEditorHighlighter(RubyEditorHighlighterProvider.java:18)
	at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.java:78)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.loadEditorInBackground(TextEditorImpl.java:75)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.java:51)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$tryLoadEditor$3(AsyncEditorLoader.java:162)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$4(PsiDocumentManagerBase.java:491)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:977)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:489)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$tryLoadEditor$4(AsyncEditorLoader.java:167)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:123)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.tryLoadEditor(AsyncEditorLoader.java:166)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.lambda$scheduleLoading$2(AsyncEditorLoader.java:120)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:200)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mplushnikov** [comment]
Thank you @maksimu for reporting this. It should be fixed in the next plugin release 0.24.
