### ISSUE TITLE
An error message when  using `val`  in a lambda expression

### ISSUE THREAD

**Issue by jearton** [mplushnikov/lombok-intellij-plugin#635]
### Short description
_Provide a short description of the issue here. Do not include stacktraces in this sectrion_

### Expected behavior
_Is there a specific expected behavior?_

### Version information

 * **IDEA Version:** 2019.1.2
 * **JDK Version:** 1.8
 * **OS Type & Version:** mac os 10.14.4
 * **Lombok Plugin Version:** v0.25-2018.3
 * **Lombok Dependency Version:** 1.18.8

### Additional information

 use `val`  in a lambda expression.

### Stacktrace

```
java.lang.Throwable: poly expression evaluation during overload resolution
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:170)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl$TypeEvaluator.fun(PsiMethodCallExpressionImpl.java:141)
	at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:94)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.getType(PsiMethodCallExpressionImpl.java:40)
	at de.plushnikov.intellij.plugin.processor.ValProcessor$2.compute(ValProcessor.java:187)
	at de.plushnikov.intellij.plugin.processor.ValProcessor$2.compute(ValProcessor.java:184)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:98)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:53)
	at de.plushnikov.intellij.plugin.processor.ValProcessor.processLocalVariableInitializer(ValProcessor.java:184)
	at de.plushnikov.intellij.plugin.processor.ValProcessor.inferType(ValProcessor.java:141)
	at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.inferType(LombokAugmentProvider.java:76)
	at com.intellij.psi.augment.PsiAugmentProvider.lambda$getInferredType$1(PsiAugmentProvider.java:87)
	at com.intellij.psi.augment.PsiAugmentProvider.forEach(PsiAugmentProvider.java:119)
	at com.intellij.psi.augment.PsiAugmentProvider.getInferredType(PsiAugmentProvider.java:86)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.calculateType(PsiTypeElementImpl.java:68)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.lambda$getType$0(PsiTypeElementImpl.java:63)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at com.intellij.psi.impl.source.PsiTypeElementImpl.getType(PsiTypeElementImpl.java:63)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:50)
	at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:46)
	at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.getType(PsiLocalVariableImpl.java:97)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$TypeEvaluator.fun(PsiReferenceExpressionImpl.java:396)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$TypeEvaluator.fun(PsiReferenceExpressionImpl.java:370)
	at com.intellij.psi.impl.source.resolve.JavaResolveCache.getType(JavaResolveCache.java:94)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.getType(PsiReferenceExpressionImpl.java:437)
	at com.intellij.psi.scope.util.PsiScopesUtil.setupAndRunProcessor(PsiScopesUtil.java:317)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolveToMethod(PsiReferenceExpressionImpl.java:308)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolve(PsiReferenceExpressionImpl.java:286)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:47)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:190)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:179)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$1(ResolveCache.java:203)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:98)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:202)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:714)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:705)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:354)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.advancedResolve(PsiReferenceExpressionImpl.java:526)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.resolveMethodGenerics(PsiMethodCallExpressionImpl.java:51)
	at com.intellij.psi.PsiDiamondType.getDiamondsAwareResolveResult(PsiDiamondType.java:193)
	at com.intellij.codeInsight.ExceptionUtil.getUnhandledExceptions(ExceptionUtil.java:450)
	at com.intellij.codeInsight.ExceptionUtil.getUnhandledExceptions(ExceptionUtil.java:438)
	at com.intellij.codeInsight.ExceptionUtil.getOwnUnhandledExceptions(ExceptionUtil.java:417)
	at com.intellij.codeInsight.ExceptionUtil$1.visitElement(ExceptionUtil.java:378)
	at com.intellij.psi.JavaElementVisitor.visitExpression(JavaElementVisitor.java:102)
	at com.intellij.psi.JavaElementVisitor.visitCallExpression(JavaElementVisitor.java:186)
	at com.intellij.psi.JavaElementVisitor.visitMethodCallExpression(JavaElementVisitor.java:182)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:127)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:70)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:27)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:79)
	at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitElement(JavaRecursiveElementWalkingVisitor.java:41)
	at com.intellij.codeInsight.ExceptionUtil$1.visitElement(ExceptionUtil.java:379)
	at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:66)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:212)
	at com.intellij.codeInsight.ExceptionUtil.getUnhandledExceptions(ExceptionUtil.java:401)
	at com.intellij.psi.impl.source.resolve.graphInference.constraints.CheckedExceptionCompatibilityConstraint.reduce(CheckedExceptionCompatibilityConstraint.java:112)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.reduceConstraints(InferenceSession.java:992)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.repeatInferencePhases(InferenceSession.java:975)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.processOneConstraint(InferenceSession.java:1451)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.proceedWithAdditionalConstraints(InferenceSession.java:1421)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.doInfer(InferenceSession.java:377)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.performGuardedInference(InferenceSession.java:315)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.infer(InferenceSession.java:305)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSession.infer(InferenceSession.java:297)
	at com.intellij.psi.impl.source.resolve.graphInference.InferenceSessionContainer.infer(InferenceSessionContainer.java:128)
	at com.intellij.psi.impl.source.resolve.graphInference.PsiGraphInferenceHelper.inferTypeArguments(PsiGraphInferenceHelper.java:54)
	at com.intellij.psi.impl.source.resolve.PsiResolveHelperImpl.inferTypeArguments(PsiResolveHelperImpl.java:192)
	at com.intellij.psi.infos.MethodCandidateInfo.lambda$inferTypeArguments$3(MethodCandidateInfo.java:424)
	at com.intellij.psi.infos.MethodCandidateInfo.computeForOverloadedCandidate(MethodCandidateInfo.java:274)
	at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:411)
	at com.intellij.psi.infos.MethodCandidateInfo.inferTypeArguments(MethodCandidateInfo.java:392)
	at com.intellij.psi.infos.MethodCandidateInfo.getSubstitutor(MethodCandidateInfo.java:316)
	at com.intellij.psi.infos.MethodCandidateInfo.getSubstitutor(MethodCandidateInfo.java:301)
	at com.intellij.codeInsight.daemon.impl.quickfix.AddTypeArgumentsFix.addTypeArguments(AddTypeArgumentsFix.java:89)
	at com.intellij.codeInsight.intention.impl.AddExplicitTypeArgumentsIntention.isAvailable(AddExplicitTypeArgumentsIntention.java:53)
	at com.intellij.codeInsight.intention.BaseElementAtCaretIntentionAction.isAvailable(BaseElementAtCaretIntentionAction.java:40)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:127)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$1(ShowIntentionsPass.java:284)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:152)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:282)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:254)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:220)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by jearton** [comment]
![image](https://user-images.githubusercontent.com/10370433/58470199-c18d5d00-8173-11e9-80bc-73725ee0a812.png)

**Comment by mplushnikov** [comment]
Looks like example for #364
