### ISSUE TITLE
UnsatisfiableDependenciesException updating to 0.8.8-11 in Idea 11

### ISSUE THREAD

**Issue by wrongdoer** [mplushnikov/lombok-intellij-plugin#64]
2014-10-01 11:46:05,288 [   5314]  ERROR - ij.components.ComponentManager - IntelliJ IDEA 11.1.5  Build #IU-117.1043 
2014-10-01 11:46:05,288 [   5314]  ERROR - ij.components.ComponentManager - JDK: 1.6.0_65 
2014-10-01 11:46:05,288 [   5314]  ERROR - ij.components.ComponentManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2014-10-01 11:46:05,288 [   5314]  ERROR - ij.components.ComponentManager - Vendor: Apple Inc. 
2014-10-01 11:46:05,288 [   5314]  ERROR - ij.components.ComponentManager - OS: Mac OS X 
2014-10-01 11:46:05,289 [   5315]  ERROR - ij.components.ComponentManager - createComponent() returns null for: class com.intellij.openapi.vfs.encoding.EncodingProjectManager 
com.intellij.util.IncorrectOperationException: createComponent() returns null for: class com.intellij.openapi.vfs.encoding.EncodingProjectManager
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponentFromContainer(ComponentManagerImpl.java:179)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:201)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:196)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponents(ComponentManagerImpl.java:269)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.initComponents(ComponentManagerImpl.java:343)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:85)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:293)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:277)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:356)
	at com.intellij.ide.UiActivityMonitorImpl.initComponent(UiActivityMonitorImpl.java:85)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.b(ComponentManagerImpl.java:216)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.access$1100(ComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:643)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:578)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:242)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:229)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
	at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:399)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:107)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.initComponents(ComponentManagerImpl.java:342)
	at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:515)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
	at com.intellij.idea.MainImpl$3.run(MainImpl.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:420)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2014-10-01 11:46:05,289 [   5315]  ERROR - ij.components.ComponentManager - IntelliJ IDEA 11.1.5  Build #IU-117.1043 
2014-10-01 11:46:05,289 [   5315]  ERROR - ij.components.ComponentManager - JDK: 1.6.0_65 
2014-10-01 11:46:05,289 [   5315]  ERROR - ij.components.ComponentManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2014-10-01 11:46:05,289 [   5315]  ERROR - ij.components.ComponentManager - Vendor: Apple Inc. 
2014-10-01 11:46:05,289 [   5315]  ERROR - ij.components.ComponentManager - OS: Mac OS X 
2014-10-01 11:46:05,302 [   5328]   INFO - .intellij.ide.XmlRpcServerImpl - XmlRpc server listening at /127.0.0.1:63342 
2014-10-01 11:46:05,352 [   5378]  ERROR - plication.impl.ApplicationImpl - com.intellij.util.indexing.FileBasedIndex has unsatisfied dependency: class com.intellij.openapi.fileTypes.FileTypeManager among unsatisfiable dependencies: [[class com.intellij.openapi.vfs.ex.VirtualFileManagerEx, class com.intellij.openapi.fileEditor.FileDocumentManager, class com.intellij.openapi.fileTypes.FileTypeManager, interface com.intellij.util.messages.MessageBus, class com.intellij.psi.stubs.SerializationManager]] where AreaPicoContainer.MyPicoContainer[null] was the leaf container being asked for dependencies. 
org.picocontainer.defaults.UnsatisfiableDependenciesException: com.intellij.util.indexing.FileBasedIndex has unsatisfied dependency: class com.intellij.openapi.fileTypes.FileTypeManager among unsatisfiable dependencies: [[class com.intellij.openapi.vfs.ex.VirtualFileManagerEx, class com.intellij.openapi.fileEditor.FileDocumentManager, class com.intellij.openapi.fileTypes.FileTypeManager, interface com.intellij.util.messages.MessageBus, class com.intellij.psi.stubs.SerializationManager]] where AreaPicoContainer.MyPicoContainer[null] was the leaf container being asked for dependencies.
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getGreediestSatisfiableConstructor(ConstructorInjectionComponentAdapter.java:191)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:210)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at org.picocontainer.defaults.DecoratingComponentAdapter.getComponentInstance(DecoratingComponentAdapter.java:60)
	at org.picocontainer.defaults.CachingComponentAdapter.getComponentInstance(CachingComponentAdapter.java:58)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:630)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:578)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:242)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:229)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
	at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:399)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:107)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.initComponents(ComponentManagerImpl.java:342)
	at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:515)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
	at com.intellij.idea.MainImpl$3.run(MainImpl.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:420)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2014-10-01 11:46:05,353 [   5379]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 11.1.5  Build #IU-117.1043 
2014-10-01 11:46:05,353 [   5379]  ERROR - plication.impl.ApplicationImpl - JDK: 1.6.0_65 
2014-10-01 11:46:05,353 [   5379]  ERROR - plication.impl.ApplicationImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
2014-10-01 11:46:05,353 [   5379]  ERROR - plication.impl.ApplicationImpl - Vendor: Apple Inc. 
2014-10-01 11:46:05,353 [   5379]  ERROR - plication.impl.ApplicationImpl - OS: Mac OS X

**Comment by mplushnikov** [comment]
It looks like a problem with IntelliJ self. I can't reproduce it with newer versions of IntelliJ like 14 or 13. Maybe you can try to update your installation.
