### ISSUE TITLE
click "build Project", it the lombok processor coult not be initialized.

### ISSUE THREAD

**Issue by rainplus** [mplushnikov/lombok-intellij-plugin#667]
### Short description
click "build Project", it the lombok processor coult not be initialized. 

### Expected behavior

cat not run the project

### Version information

 * **IDEA Version:** 
IntelliJ IDEA 2019.2.2 (Ultimate Edition)
Build #IU-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 4062M
Cores: 4
Registry: ide.mac.allowDarkWindowDecorations=true
Non-Bundled Plugins: IdeaVIM, Lombook Plugin, com.alibaba.p3c.smartfox, com.steve.plugins.recentprojects, com.jetbrains.upsource, io.edgeg.gtm.intellij, mobi.hsz.idea.gitignore, net.hexar.json2pojo, cn.wuzhizhan.plugin.mybatis, com.intellij.plugins.html.instantEditing, com.zhaow.restful.toolkit, in.1ton.idea.spring.assistant.plugin

 * **JDK Version:** 
jdk8

 * **OS Type & Version:** _Are you on Mac/Windows/Linux? Provide as much information as possible about versions_
 * **Lombok Plugin Version:** 
0.26.2
0.27 
 * **Lombok Dependency Version:** 
1.16.20
### Stacktrace
If you are experiencing an issue and IntelliJ throws an error please provide the stacktrace.

```

Warning:(14, 8) java: lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation: java.lang.IllegalArgumentException: com.sun.proxy.$Proxy25 extends java.lang.reflect.Proxy implements javax.tools.StandardJavaFileManager
  	at lombok.javac.apt.LombokFileObjects.getCompiler(LombokFileObjects.java:148)
  	at lombok.javac.apt.InterceptingJavaFileManager.<init>(InterceptingJavaFileManager.java:40)
  	at lombok.javac.apt.LombokProcessor.placePostCompileAndDontMakeForceRoundDummiesHook(LombokProcessor.java:165)
  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:87)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:140)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:69)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:678)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:778)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:873)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1214)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1326)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:195)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:460)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:330)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:255)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:213)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1324)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1004)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1071)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:965)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:794)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:376)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:139)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:288)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:121)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:228)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by DavyGuedes** [comment]
Hi @rainplus 
I was facing the same issue with jdk8 in a Spring Boot project.
Update lombok manually to 1.18.10 solve it in my project. 

```xml
<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<optional>true</optional>
	<version>1.18.10</version>
</dependency>
```

Source: https://github.com/rzwitserloot/lombok/issues/1541#issuecomment-521916503

> I have a similar error with:
> Lombok Version: 1.16.20
> IntelliJ: 2019.2
> JDK: 9

**Comment by rainplus** [comment]
tks, i fixed it already. use same way @DavyGuedes
