### ISSUE TITLE
lombok.config doesn't works in IntelliJ Ultimate 2019.2

### ISSUE THREAD

**Issue by sachingorade** [mplushnikov/lombok-intellij-plugin#697]
### Short description
Create lombok.config with following properties in root directory,
```
config.stopBubbling = true
lombok.addLombokGeneratedAnnotation = true
```
Generated classes don't have JSON/Jackson related annotations.

### Version information
IDEA Version: Intellij Idea Ultimate EAP 2019.2.3
JDK Version: 1.8
OS Type & Version: Mac OS
Lombok Plugin Version: 0.27-2019.2
Lombok Dependency Version: 1.16.20

### Steps to reproduce
1. Create a new maven project
2. Add Lombok and Jackson dependencies in pom.xml
3. Create lombok.config in root directory with following properties

Model class
```java
@Value
@JsonIgnoreProperties(ignoreUnknown = true)
public class Price {

    private Long priceId;

}
```
Code in ```Main``` class
```
public class Main {

    private static final String TEST_JSON_INPUT = "{" +
            " \"priceId\" : 1 " +
            "}";

    public static void main(String[] args) throws JsonProcessingException {
        ObjectMapper mapper = (new ObjectMapper())
                .registerModule(new JavaTimeModule())
                .registerModule(new Jdk8Module())
                .registerModule(new ParameterNamesModule(Mode.PROPERTIES)));
        System.out.println(mapper.readValue(TEST_JSON_INPUT, Price.class));
    }

}
```
Executing main throws following exception,
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.testing.jackson.model.Price` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{ "priceId" : 1 }"; line: 1, column: 3]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1429)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1059)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at com.testing.jackson.Main.main(Main.java:35)

```

**Comment by mplushnikov** [comment]
Your runtime error has nothing to do with plugin for IntelliJ.

If you are using lombok 1.16.20, it contains:

> BREAKING CHANGE: lombok config key lombok.anyConstructor.suppressConstructorProperties is now deprecated and defaults to true, that is, by default lombok no longer automatically generates @ConstructorProperties annotations. New config key lombok.anyConstructor.addConstructorProperties now exists; set it to true if you want the old behavior. Oracle more or less broke this annotation with the release of JDK9, necessitating this breaking change.

https://github.com/rzwitserloot/lombok/issues/1563#issuecomment-358403046

**Comment by sachingorade** [comment]
> Your runtime error has nothing to do with plugin for IntelliJ.
> 
> If you are using lombok 1.16.20, it contains:
> 
> > BREAKING CHANGE: lombok config key lombok.anyConstructor.suppressConstructorProperties is now deprecated and defaults to true, that is, by default lombok no longer automatically generates @ConstructorProperties annotations. New config key lombok.anyConstructor.addConstructorProperties now exists; set it to true if you want the old behavior. Oracle more or less broke this annotation with the release of JDK9, necessitating this breaking change.
> 
> [rzwitserloot/lombok#1563 (comment)](https://github.com/rzwitserloot/lombok/issues/1563#issuecomment-358403046)

Okay, thanks for the immediate reply. I will check using new configuration :)
