### ISSUE TITLE
IDEA 2019.3 Exception

### ISSUE THREAD

**Issue by Skeletak** [mplushnikov/lombok-intellij-plugin#709]
### Short description
Exception during IDE startup. Plugin is automatically disabled. 

```

2019-11-29 09:32:49,230 [  24955]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.StartupAbortedException: Fatal error initializing plugin Lombook Plugin 
java.util.concurrent.CompletionException: com.intellij.ide.plugins.StartupAbortedException: Fatal error initializing plugin Lombook Plugin
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:383)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl$1.proceed(MainImpl.java:102)
	at com.intellij.ide.b.b.a2.proceed(a2.java:129)
	at com.intellij.ide.b.b.I.d(I.java:490)
	at com.intellij.ide.b.b.I.c(I.java:210)
	at com.intellij.ide.b.b.I.a(I.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl.start(MainImpl.java:94)
	at com.intellij.idea.StartupUtil.lambda$startApp$5(StartupUtil.java:248)
	at com.intellij.util.ui.EdtInvocationManager.executeWithCustomManager(EdtInvocationManager.java:73)
	at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:243)
	at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:215)
	at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:39)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.ide.plugins.StartupAbortedException: Fatal error initializing plugin Lombook Plugin
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:55)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.kt:247)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.registerComponents(PlatformComponentManagerImpl.kt:113)
	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:115)
	at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 23 more
Caused by: com.intellij.diagnostic.PluginException: While loading class de.plushnikov.intellij.plugin.LombokPluginApplicationComponent$1: class de.plushnikov.intellij.plugin.LombokPluginApplicationComponent$1 overrides final method com.intellij.serviceContainer.BaseKeyedLazyInstance.getInstance()Ljava/lang/Object; [Plugin: Lombook Plugin] [Plugin: Lombook Plugin]
	... 29 more
Caused by: com.intellij.diagnostic.PluginException: While loading class de.plushnikov.intellij.plugin.LombokPluginApplicationComponent$1: class de.plushnikov.intellij.plugin.LombokPluginApplicationComponent$1 overrides final method com.intellij.serviceContainer.BaseKeyedLazyInstance.getInstance()Ljava/lang/Object; [Plugin: Lombook Plugin]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:223)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:167)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.registerComponent(PlatformComponentManagerImpl.kt:203)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.registerComponents(PlatformComponentManagerImpl.kt:109)
	... 26 more
Caused by: java.lang.VerifyError: class de.plushnikov.intellij.plugin.LombokPluginApplicationComponent$1 overrides final method com.intellij.serviceContainer.BaseKeyedLazyInstance.getInstance()Ljava/lang/Object;
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:359)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:355)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:319)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:220)
	... 33 more
2019-11-29 09:32:49,234 [  24959]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2019.3  Build #IU-193.5233.102 
2019-11-29 09:32:49,235 [  24960]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-11-29 09:32:49,235 [  24960]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2019-11-29 09:32:49,285 [  25010]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Lombok Plugin version: 0.19-LATEST-EAP-SNAPSHOT 

```

**Comment by nbuesing** [comment]
I never upgrade Intellij until after I see things working here.  mplushnikov, you do such an awesome job with this plugin and getting it up to date quickly, but I worry that you always have to struggle with changes made by Intellij.  Is there any API IntelliJ could officially support to make this not a constant battle?  If so, would love to do a +1 on any reported issues to make things easier.

**Comment by YLombardi** [comment]
I just upgrade to IntelliJ 2019.3 and I have the same exception.

**Comment by SimonCigoj** [comment]
same here

**Comment by SimonCigoj** [comment]
@YLombardi I have IntelliJ IDEA 2019.3 (Ultimate Edition) Build #IU-193.5233.102 ... have uninstalled the plugin but I am not able to install it again, there is no plugin available in the marketplace ... @YLombardi  how have you installed it again?

**Comment by SimonCigoj** [comment]
I needed to delete some custom VM option in Help -> Edit Custom VM options to be able to reinstall the plugin. This hepled me https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004275380-Marketplace-Plugins-are-not-loaded

**Comment by mplushnikov** [comment]
@Skeletak You are using very old version of plugin (0.19-LATEST-EAP-SNAPSHOT). This is incopatible to new IntelliJ Version. 
Please update it. 

You can update it under Settings->Plugin->Marketplace automatically or download it manually from https://github.com/mplushnikov/lombok-intellij-plugin/releases

(Be sure to use right version for your installation! For IntelliJ 2019.3 you have to choose lombok-plugin-0.27-EAP.zip for  for example)
