### ISSUE TITLE
PsiInvalidElementAccessException psi is outdated

### ISSUE THREAD

**Issue by sneakythr0ws** [mplushnikov/lombok-intellij-plugin#821]
IntelliJ IDEA 2020.2 EAP (Ultimate Edition)
Build #**IU-202.5792.28**, built on June 18, 2020
Runtime version: 11.0.5+10-b617.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.0-37-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 3433M
Cores: 8
Current Desktop: ubuntu:GNOME

lombok plugin **0.30-EAP**
```
com.intellij.psi.PsiInvalidElementAccessException: Element: class de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder #JAVA  because: psi is outdated
invalidated at: no info
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:477)
	at com.intellij.psi.impl.PsiClassImplUtil.lambda$createMembersMap$4(PsiClassImplUtil.java:346)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.get(PsiClassImplUtil.java:326)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.access$000(PsiClassImplUtil.java:318)
	at com.intellij.psi.impl.PsiClassImplUtil.getMap(PsiClassImplUtil.java:175)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllByMap(PsiClassImplUtil.java:166)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllMethods(PsiClassImplUtil.java:58)
	at com.intellij.psi.impl.source.PsiClassImpl.getAllMethods(PsiClassImpl.java:335)
	at com.intellij.execution.junit.JUnitUtil.hasTestOrSuiteMethods(JUnitUtil.java:211)
	at com.intellij.execution.junit.JUnitUtil.lambda$isTestClass$0(JUnitUtil.java:207)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:153)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:76)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:150)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:120)
	at com.intellij.execution.junit.JUnitUtil.isTestClass(JUnitUtil.java:206)
	at com.intellij.execution.junit.JUnitUtil.isTestMethod(JUnitUtil.java:134)
	at com.intellij.execution.junit.JUnitUtil.isTestMethod(JUnitUtil.java:128)
	at com.intellij.execution.junit.JUnitUtil.isTestMethod(JUnitUtil.java:124)
	at com.intellij.execution.junit.JUnitUtil.isTestMethodOrConfig(JUnitUtil.java:406)
	at com.intellij.execution.junit2.inspection.JUnitEntryPoint.isEntryPoint(JUnitEntryPoint.java:65)
	at com.intellij.codeInspection.deadCode.UnusedDeclarationInspectionBase.isEntryPoint(UnusedDeclarationInspectionBase.java:324)
	at com.intellij.codeInspection.deadCode.UnusedDeclarationInspectionBase.isDeclaredAsEntryPoint(UnusedDeclarationInspectionBase.java:353)
	at com.intellij.codeInspection.unusedReturnValue.UnusedReturnValueLocalInspection.checkMethod(UnusedReturnValueLocalInspection.java:51)
	at com.intellij.codeInspection.AbstractBaseJavaLocalInspectionTool$1.visitMethod(AbstractBaseJavaLocalInspectionTool.java:52)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:288)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:294)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:263)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:155)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:147)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by austinarbor** [comment]
This brings my whole IDE to a halt when it occurs. Need to completely exit and restart. Only workaround I've found is to add new lombok annotations to the source using a different editor

**Comment by komorebi64** [comment]
> This brings my whole IDE to a halt when it occurs. Need to completely exit and restart. Only workaround I've found is to add new lombok annotations to the source using a different editor

I can just restart IDEA, get back to work
No other way, just restart the IDE

**Comment by austinarbor** [comment]
> I can just restart IDEA, get back to work
> No other way, just restart the IDE

The annotations work after restarting the IDE?

**Comment by komorebi64** [comment]
> > I can just restart IDEA, get back to work
> > No other way, just restart the IDE
> 
> The annotations work after restarting the IDE?
Yes i just restart the IDE..

**Comment by austinarbor** [comment]
Doesn't work for me. I'm unable to add Lombok annotations even after restart. I can only add annotations from another IDE.

**Comment by komorebi64** [comment]
> Doesn't work for me. I'm unable to add Lombok annotations even after restart. I can only add annotations from another IDE.

After an error, things related to Lombok cannot be used normally...

**Comment by marcotama** [comment]
I am experiencing the same. Not sure how to reproduce, I was just working. To expand on the OP post, all IDE support for coding seems to stop working (e.g. hinting, usages, jumping around, etc.)
Restarting the IDE seems to fix the problem, but all progress is lost 😢 

I am pretty sure this is the third time this has happened to me in the last few days, but I cannot promise since I had not checked then.

**IDEA Version**: 2020.2 (Build #IU-202.6397.94)
**JDK Version**: 11
**OS Type & Version**: mac 10.14.6
**Lombok Plugin Version**: 0.30-EAP
**Lombok Dependency Version**: 1.18.12
