### ISSUE TITLE
Lombok annotations not consistent while typing in Intellij

### ISSUE THREAD

**Issue by nullptr7** [mplushnikov/lombok-intellij-plugin#839]
### Short description
Lombok Annotations are not working consistently with 2020.2 RC version

### Expected behavior
Issue is mentioned in https://youtrack.jetbrains.com/issue/IDEA-246663

### Version information

 * **IDEA Version:** IU-202.6397.59
 * **JDK Version:** 14
 * **OS Type & Version:** Win10 64 bit
 * **Lombok Plugin Version:** 0.30-EAP
 * **Lombok Dependency Version:** 1.18.12

### Steps to reproduce

Create a model class and annotate it with @ Data

 1. Once it is annotated with @ Data, start typing @ Builder the IDE does not give suggestion
[idea.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/4982011/idea.zip)

### Sample project
Please provide a sample project that exhibits the problem.

### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_

### Stacktrace

```

com.intellij.diagnostic.PluginException: Element: class de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder #JAVA  because: psi is outdated
invalidated at: no info [Plugin: Lombook Plugin]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:290)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:67)
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:478)
	at com.intellij.psi.impl.PsiClassImplUtil.lambda$createMembersMap$4(PsiClassImplUtil.java:346)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.get(PsiClassImplUtil.java:326)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.access$000(PsiClassImplUtil.java:318)
	at com.intellij.psi.impl.PsiClassImplUtil.getMap(PsiClassImplUtil.java:175)

```

**Comment by TheBestPessimist** [comment]
see: https://github.com/mplushnikov/lombok-intellij-plugin/issues/829#issuecomment-660442053

**Comment by nullptr7** [comment]
It is already reference #840
