### ISSUE TITLE
Support change signature refactoring for getters/setters of @Data classes

### ISSUE THREAD

**Issue by akozlova** [mplushnikov/lombok-intellij-plugin#85]
Now IDEA treats generated methods as normal physical methods and fail in different places, e.g.
java.lang.NullPointerException
	at com.intellij.refactoring.changeSignature.JavaChangeSignatureUsageProcessor.processPrimaryMethod(JavaChangeSignatureUsageProcessor.java:740)
	at com.intellij.refactoring.changeSignature.JavaChangeSignatureUsageProcessor.processPrimaryMethod(JavaChangeSignatureUsageProcessor.java:571)
	at com.intellij.refactoring.changeSignature.ChangeSignatureProcessorBase.performRefactoring(ChangeSignatureProcessorBase.java:179)
	at com.intellij.codeInsight.daemon.impl.quickfix.ChangeMethodSignatureFromUsageFix$2.performRefactoring(ChangeMethodSignatureFromUsageFix.java:236)
	at com.intellij.refactoring.BaseRefactoringProcessor$7.run(BaseRefactoringProcessor.java:475)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
	at com.intellij.refactoring.BaseRefactoringProcessor.doRefactoring(BaseRefactoringProcessor.java:448)
	at com.intellij.refactoring.BaseRefactoringProcessor.access$100(BaseRefactoringProcessor.java:75)
	at com.intellij.refactoring.BaseRefactoringProcessor$3.run(BaseRefactoringProcessor.java:293)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:117)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.refactoring.BaseRefactoringProcessor.execute(BaseRefactoringProcessor.java:289)
	at com.intellij.refactoring.BaseRefactoringProcessor.doRun(BaseRefactoringProcessor.java:226)
	at com.intellij.refactoring.BaseRefactoringProcessor.run(BaseRefactoringProcessor.java:559)
	at com.intellij.codeInsight.daemon.impl.quickfix.ChangeMethodSignatureFromUsageFix.performChange(ChangeMethodSignatureFromUsageFix.java:239)
	at com.intellij.codeInsight.daemon.impl.quickfix.ChangeMethodSignatureFromUsageFix.invoke(ChangeMethodSignatureFromUsageFix.java:178)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler$2.run(ShowIntentionActionsHandler.java:179)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:198)
	at com.intellij.codeInsight.intention.impl.IntentionListStep$2$1.run(IntentionListStep.java:260)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Should I provide veto-change-signature extension for you? Or how do you expect this to work?
Thanks

**Comment by mplushnikov** [comment]
Hello Anna,

yes sure, I can use this extension to prevent such exceptions.

At the moment I use only RenameHandler to prevent methods generated by plugin to be renamed. But there are many places, where other Intellij refactoring actions can take places, it a sore point of the  plugin:(

Thank you for your help!

**Comment by akozlova** [comment]
Michail,

it would be cool if rename of getter would rename corresponding property, change signature (but only parameter type/return type) - change the type of the property, encapsulate fields - show notification/exclude fields from the list, etc. Unfortunately I can't promise that corresponding API would appear shortly, sorry, it's complicated to make changes and preserve compatibility. I'll give you a link for veto-extension, as soon as I push it.

Thanks,
Anna
