### ISSUE TITLE
Plugin crash: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation

### ISSUE THREAD

**Issue by seanf** [mplushnikov/lombok-intellij-plugin#98]
Plugin crashed when opening a project, with this exception: provider: `de.plushnikov.intellij.plugin.provider.LombokAugmentProvider@684b5a7c`: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation

IntelliJ IDEA: 14.1.1
Lombok plugin: 0.9.2

	com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
		at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:854)
		at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:803)
		at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:787)
		at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:250)
		at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:238)
		at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:76)
		at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:95)
		at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:227)
		at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:144)
		at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
		at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
		at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.a(JavaFileManagerImpl.java:145)
		at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:138)
		at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
		at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:99)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:385)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:331)
		at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
		at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
		at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
		at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
		at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:767)
		at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:757)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:366)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:359)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:328)
		at com.intellij.psi.impl.source.PsiImportStatementBaseImpl.resolve(PsiImportStatementBaseImpl.java:64)
		at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.a(PsiJavaFileBaseImpl.java:314)
		at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.access$100(PsiJavaFileBaseImpl.java:58)
		at com.intellij.psi.impl.source.PsiJavaFileBaseImpl$MyCacheBuilder.compute(PsiJavaFileBaseImpl.java:480)
		at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
		at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
		at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
		at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:283)
		at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
		at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
		at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
		at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:146)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:438)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:331)
		at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
		at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
		at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
		at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
		at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:767)
		at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:757)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:366)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:359)
		at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:141)
		at com.intellij.psi.util.PsiUtil.captureToplevelWildcards(PsiUtil.java:718)
		at com.intellij.psi.impl.PsiClassImplUtil.getSuperTypes(PsiClassImplUtil.java:908)
		at com.intellij.psi.impl.source.PsiClassImpl.getSuperTypes(PsiClassImpl.java:249)
		at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:774)
		at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:709)
		at com.intellij.psi.impl.PsiClassImplUtil.a(PsiClassImplUtil.java:478)
		at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClass(PsiClassImplUtil.java:448)
		at com.intellij.psi.impl.source.PsiClassImpl.processDeclarations(PsiClassImpl.java:488)
		at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:72)
		at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:54)
		at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:215)
		at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:146)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.a(PsiJavaCodeReferenceElementImpl.java:438)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:55)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:339)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:331)
		at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:191)
		at com.intellij.psi.impl.source.resolve.ResolveCache$4.compute(ResolveCache.java:188)
		at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
		at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
		at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:767)
		at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:757)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:366)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:359)
		at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:328)
		at de.plushnikov.intellij.plugin.processor.ValProcessor.isVal(ValProcessor.java:92)
		at de.plushnikov.intellij.plugin.processor.ValProcessor.inferType(ValProcessor.java:106)
		at de.plushnikov.intellij.plugin.provider.LombokAugmentProvider.inferType(LombokAugmentProvider.java:122)
		at com.intellij.psi.augment.PsiAugmentProvider.getInferredType(PsiAugmentProvider.java:73)
		at com.intellij.psi.impl.source.PsiTypeElementImpl.e(PsiTypeElementImpl.java:80)
		at com.intellij.psi.impl.source.PsiTypeElementImpl.getType(PsiTypeElementImpl.java:74)
		at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:46)
		at com.intellij.psi.impl.source.tree.JavaSharedImplUtil.getType(JavaSharedImplUtil.java:42)
		at com.intellij.psi.impl.source.PsiParameterImpl.getType(PsiParameterImpl.java:195)
		at com.intellij.psi.util.PsiFormatUtil.formatVariable(PsiFormatUtil.java:56)
		at com.intellij.psi.util.PsiFormatUtil.formatVariable(PsiFormatUtil.java:43)
		at com.intellij.psi.util.PsiFormatUtil.formatMethod(PsiFormatUtil.java:191)
		at com.intellij.psi.util.PsiFormatUtil.formatMethod(PsiFormatUtil.java:132)
		at com.intellij.psi.util.PsiFormatUtil.formatMethod(PsiFormatUtil.java:123)
		at com.intellij.ide.structureView.impl.java.PsiMethodTreeElement.getPresentableText(PsiMethodTreeElement.java:76)
		at com.intellij.ide.projectView.PresentationData.updateFrom(PresentationData.java:183)
		at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.update(TreeElementWrapper.java:41)
		at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
		at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
		at com.intellij.ide.util.treeView.AbstractTreeBuilder.updateNodeDescriptor(AbstractTreeBuilder.java:588)
		at com.intellij.ide.util.treeView.AbstractTreeUi$22.perform(AbstractTreeUi.java:944)
		at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
		at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
		at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:940)
		at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:892)
		at com.intellij.ide.util.treeView.AbstractTreeUi.collectNodesToInsert(AbstractTreeUi.java:2256)
		at com.intellij.ide.util.treeView.AbstractTreeUi.access$4500(AbstractTreeUi.java:62)
		at com.intellij.ide.util.treeView.AbstractTreeUi$30.perform(AbstractTreeUi.java:1399)
		at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
		at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:59)
		at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:69)
		at com.intellij.openapi.util.ActionCallback$3.run(ActionCallback.java:233)
		at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:101)
		at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:108)
		at com.intellij.openapi.util.ActionCallback.notify(ActionCallback.java:153)
		at com.intellij.ide.util.treeView.AbstractTreeUi$34.perform(AbstractTreeUi.java:1783)
		at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
		at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2091)
		at com.intellij.ide.util.treeView.AbstractTreeUi.access$5900(AbstractTreeUi.java:62)
		at com.intellij.ide.util.treeView.AbstractTreeUi$38$1.perform(AbstractTreeUi.java:1983)
		at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
		at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:433)
		at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2186)
		at com.intellij.ide.util.treeView.AbstractTreeUi$38.perform(AbstractTreeUi.java:1978)
		at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
		at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:53)
		at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:50)
		at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:98)
		at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:36)
		at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:57)
		at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
		at java.awt.EventQueue.access$200(EventQueue.java:103)
		at java.awt.EventQueue$3.run(EventQueue.java:694)
		at java.awt.EventQueue$3.run(EventQueue.java:692)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
		at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by loolooyyyy** [comment]
This started happening after the latest update to OpenJDK on fedora. Do you think it's related? (probably just an accident!)

**Comment by mplushnikov** [comment]
Should be fixed in the next release 0.9.3
